### ISSUE TITLE
jre msi

### ISSUE THREAD

**Issue by lifeinwild** [corretto/corretto-8#108]
### Is your feature request related to a problem?
This sentence is through Google Machine Translation.
I am not a Java expert and I am not sure if these opinions are valid.

https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html
Why is Windows jre only zip? oracle jre had been installed on the end user's OS side. In distributing Java8 + JavaFX application or JME3 game application to end users, I would like to instruct end users to download msi from the above URL. msi is in demand.

### Describe a solution you would like
installers and uninstallers of each platform for end-user. 

### Describe alternatives you have considered
jdk may be upward compatible with jre. but jdk have many unnecessary features at runtime. It allows excessive functionality for Java apps that is downloaded from the Internet. Is this an excessive worry?

### Additional context
I expect the Java environment to be this way.
I think two Java should coexist. OS side Java8 JRE + self-contained latest JRE. Jigsaw makes Java 9+ suitable for self-contained. Backward compatibility is maintained by the OS's Java 8 JRE. Self-contained apps are more likely to leave JRE vulnerabilities. OS side JRE should exist. It should be Java 8 for backwards compatibility. Several famous projects have struggled or failed to migrate from Java 8 to Java 9+. If my idea is correct, I think that Java 8's jre installer and uninstaller will be permanently required in the future.

**Comment by jguo11** [comment]
@lifeinwild Thanks for the suggestion. We will evaluate the request and get back to you soon.

**Comment by 4rz0** [comment]
Any news on this?
The "Amazon Corretto 8 Installation Instructions for Windows 7 or Later" (https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/windows-7-install.html) is incorrect for the JRE installation since there's no JRE MSI installers.

**Comment by straffin** [comment]
Bump. Would very much appreciate an MSI installed for just the JRE or, failing that, a command-line option on the JDK MSI to install only the JRE portion. Thank you.

**Comment by duel007** [comment]
I'm also here because the instructions say there is an MSI yet none exists. It would be nice to have an installer for just the JRE.

**Comment by yamiel-abreu** [comment]
I arrived here after also being looking for a msi installation of just JRE. I also think it would be nice to have an installer just for the JRE.

**Comment by viderme** [comment]
One alternative is to use https://chocolatey.org/packages/corretto8jre, for those seeking alternatives.

**Comment by Shrill-Girl** [comment]
Bump. End user friendly installer would help to make Corretto more popular.

**Comment by benty-amzn** [comment]
I'm pleased to share that JRE MSIs for Windows x86 and x64 are available as part of the latest [8u302 release](https://github.com/corretto/corretto-8/releases/tag/8.302.08.1)

Please feel free to try them and provide feedback.
