### ISSUE TITLE
JDK distribution does not include jmc and jvisualvm

### ISSUE THREAD

**Issue by jikuja** [corretto/corretto-8#109]
### Describe the bug
Both Windows and OS X JDK builds of  8u202 does not include jmc and jvisualvm

### To Reproduce
Install Corretto 8u202. Check available tools and notice that jmc and jvisualvm are missing.

### Expected behavior
Tools should be available

### Screenshots
```
$  ls -l /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin/
total 7408
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 appletviewer
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 extcheck
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 idlj
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jar
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jarsigner
-rwxr-xr-x  1 root  wheel   93556 Jan 24 03:21 java
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 javac
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 javadoc
-rwxr-xr-x  1 root  wheel    2293 Jan 24 03:08 javafxpackager
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 javah
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 javap
-rwxr-xr-x  1 root  wheel    2293 Jan 24 03:08 javapackager
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jcmd
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jconsole
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jdb
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jdeps
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jhat
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jinfo
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jjs
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jmap
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jps
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jrunscript
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jsadebugd
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jstack
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jstat
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 jstatd
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 keytool
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 native2ascii
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 orbd
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 pack200
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 policytool
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 rmic
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 rmid
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 rmiregistry
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 schemagen
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 serialver
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 servertool
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 tnameserv
-rwxr-xr-x  1 root  wheel  106768 Jan 24 03:21 unpack200
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 wsgen
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 wsimport
-rwxr-xr-x  1 root  wheel   93620 Jan 24 03:21 xjc
```

### Platform information
Windows Server 2016
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)

and

OS X 10.14.3
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)

### Additional context
Windows version downloaded directly from Amazon Corretto website, OS X version by using homebrew package

**Comment by davecurrie** [comment]
@jikuja Thanks for the feedback. Neither of the tools you mention are part of the OpenJDK project, which is why they are not included. Both Java Mission Control and Java VisualVM as shipped in Oracle's JDK 8 are proprietary tech.

We can consider the request to bring both into Corretto, although JMC in particular likely won't happen without JFR.

VisualVM is also available as a standalone product from https://visualvm.github.io/ - we'd be interested to hear if you try it and it works well for you.

**Comment by rdp** [comment]
current error message isn't very intuitive  "jvisualvm  Unable to locate an executable at "/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin/jvisualvm" (-1)"

**Comment by telebog** [comment]
VisualVM is not working with Corretto 8. It can connect to the app but cpu sampler and profiler is not working.

**Comment by rdp** [comment]
cpu sampler works OK here, profiler seemed to just lock up the profiled app LOL.

**Comment by telebog** [comment]
![image](https://user-images.githubusercontent.com/7736319/67105661-77138800-f1c9-11e9-9a33-37650b69f6a3.png)
with Sampler is empty no threads. I tried with default and JMX same result

**Comment by telebog** [comment]
It is working for me also, I forgot to add my package to profile settings

**Comment by gowthamv** [comment]
Is it possible to patch visualVM and JMC in Amazon correcto openJDK8? If so how to do it?

**Comment by rdp** [comment]
downloading visualVM from its website seemed to work fine with corretto for me...

**Comment by davecurrie** [comment]
@gowthamv VisualVM should work fine, please let us know if you have problems. Java Mission Control is designed to work with Java Flight Recorder, which is available in Corretto 11.

**Comment by gowthamv** [comment]
In my case, visualVM asking for accept licence after that yourname and password in welcome screen. 
Most of times it hangs, only welcome screen is showing.  How to resolve it?

**Comment by davecurrie** [comment]
@gowthamv I can't reproduce this issue. Could you please:
1. Confirm that you are using visualVM downloaded from https://visualvm.github.io/download.html (and if not, try that one)
2. Tell us what versions of OS, Corretto, and visualVM you are using?

**Comment by gowthamv** [comment]
@davecurrie  I've downloaded it from https://visualvm.github.io/download.html only.
 i could see below error in visualVM user directory **visualVM\1.3.9\var\log\messages.log**

INFO [org.netbeans.modules.autoupdate.updateprovider.DownloadListener]: Reading URL https://visualvm.github.io/uc/release139/updates.xml.gz?unique=033cba2ea-225a-4662-b8cd-df03b93765cc_897ec682-b625-4ad7-9329-7be3c396e860 failed (java.io.IOException: Timeout while opening connection to https://visualvm.github.io/uc/release139/updates.xml.gz?unique=033cba2ea-225a-4662-b8cd-df03b93765cc_897ec682-b625-4ad7-9329-7be3c396e860)
INFO [org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler]
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$1.run(NetworkAccess.java:109)
Caused: java.io.IOException: Timeout while opening connection to https://visualvm.github.io/uc/release139/updates.xml.gz?unique=033cba2ea-225a-4662-b8cd-df03b93765cc_897ec682-b625-4ad7-9329-7be3c396e860
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$1.run(NetworkAccess.java:129)
Caused: java.io.IOException: Timeout while opening connection to https://visualvm.github.io/uc/release139/updates.xml.gz?unique=033cba2ea-225a-4662-b8cd-df03b93765cc_897ec682-b625-4ad7-9329-7be3c396e860
	at org.netbeans.modules.autoupdate.updateprovider.DownloadListener.notifyException(DownloadListener.java:103)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.copy(AutoupdateCatalogCache.java:246)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.writeCatalogToCache(AutoupdateCatalogCache.java:99)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogProvider.refresh(AutoupdateCatalogProvider.java:154)
	at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.refresh(UpdateUnitProviderImpl.java:180)
	at org.netbeans.api.autoupdate.UpdateUnitProvider.refresh(UpdateUnitProvider.java:196)
[catch] at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler$4.run(AutoupdateCheckScheduler.java:155)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by davecurrie** [comment]
@gowthamv from the exceptions you send, it looks like a problem in visualvm rather than Corretto. You can try to refer to their website, where they have a troubleshooting section.

**Comment by ziyiluo** [comment]
Hi We are not planning to integrate JVisualVM into Corretto. However we do provide a separate build of JMC that supports both Corretto 8 & 11. You can download Corretto for JMC from our Github release page:
https://github.com/corretto/corretto-jmc/releases

**Comment by jdonnelly-apixio** [comment]
Thinking Oracle might have broken the newer versions of visualvm when connecting from and to corretto8 jvms on purpose. From their [docs](https://visualvm.github.io/download.html):
```
VisualVM startup terminates by Error Starting VisualVM Dialog - unsupported version of Java: this typically happens when JRE or incorrect JDK version is used to run VisualVM, make sure VisualVM is running using Oracle JDK 8+
```

I can connect just fine with corretto to openjdk, but not corretto to corretto. 

VisualVm 1.4.4 works just fine when connecting from/to corretto 8. Older version downloads can be found [here](https://visualvm.github.io/releases.html).
