### ISSUE TITLE
Windows MSI in unbranded and doesn't show what version I'm installing.

### ISSUE THREAD

**Issue by EricEdens** [corretto/corretto-8#112]
When installing on Windows using the MSI installers, it's unclear what version of Amazon Corretto I'm installing (8? 8.202? 8.192?), and there's a huge opportunity to improve the branding experience in terms of graphics.

![image](https://user-images.githubusercontent.com/575626/56168835-2c525280-5f91-11e9-9ce1-ed932d68419e.png)

**Comment by ziyiluo** [comment]
Mac installer also misses the version info, we shall fix both platforms.

**Comment by ziyiluo** [comment]
Reopen the issue as this has not been fixed on Windows.

**Comment by cliveverghese** [comment]
This issue was resolved in 8.222.x.x. Closing the issue.
