### ISSUE TITLE
Windows UAC popup is cryptic and unbranded.

### ISSUE THREAD

**Issue by EricEdens** [corretto/corretto-8#113]
When using the Windows MSI installer (amazon-corretto-8.202.08.2-windows-x64.msi), the [UAC popup Window](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works) is unbranded and doesn't tell me what I'm approving. It just says: "a9aec.msi".

![image](https://user-images.githubusercontent.com/575626/56168986-9c60d880-5f91-11e9-9ee5-dcadea24b57c.png)

**Comment by cliveverghese** [comment]
This issue was resolved in 8.222.x.x Closing the issue.
