### ISSUE TITLE
Upstream Corretto to major distros

### ISSUE THREAD

**Issue by jancona** [corretto/corretto-8#114]
### Is your feature request related to a problem?
It's important to be able to install and receive new versions and security patches in an automated fashion.

### Describe a solution you would like
Theoretically Corretto should be eligible to live in the upstream Debian and Redhat repos. That would enable users installing and receiving updates through the normal process for their OS, without having to take any additional steps. So I wanted to raise it as an option to be considered as part of the [Auto-updates milestone](https://github.com/corretto/corretto-8/milestone/5).

### Describe alternatives you have considered
The [Auto-updates milestone](https://github.com/corretto/corretto-8/milestone/5) has a number of alternatives including an [Ubuntu PPA](https://github.com/corretto/corretto-8/issues/29) and a [Debian repo](https://github.com/corretto/corretto-8/issues/99).

**Comment by ziyiluo** [comment]
@jancona Thanks for reaching out. I'll put this issue into the auto-update milestone. Meanwhile, to make sure our I understand your expectation thoroughly, would you please enumerate the "major distros" you would like to see Corretto lives? You mentioned Redhat (RHEL & CentOS yum repo) and Debian repo, is your request specific to Linux artifact repositories?

**Comment by jancona** [comment]
I am mostly concerned with Linux. You already have an issue for Homebrew on MacOS. I'm not sure what the equivalent for Windows would be. I assume there are devotees of other Linux distros that might be interested, but CentOS, Debian and Ubuntu would meet my use cases.

**Comment by Refalm** [comment]
> 
> 
> I am mostly concerned with Linux. You already have an issue for Homebrew on MacOS. I'm not sure what the equivalent for Windows would be. I assume there are devotees of other Linux distros that might be interested, but CentOS, Debian and Ubuntu would meet my use cases.

The Windows equivalent is Chocolatey, see:
https://chocolatey.org/packages/correttojdk

**Comment by davecurrie** [comment]
@jancona We announced Yum and Apt repos for Corretto today, which should meet your use cases -- see https://aws.amazon.com/blogs/opensource/new-update-channels-for-amazon-corretto-releases/.

Note that we are happy for distro owners to package and include Corretto but we are providing this so you are not dependent on your distro if you'd like to use Corretto seamlessly.
