### ISSUE TITLE
Bug or Feature - MSI upgrade does not remove old version

### ISSUE THREAD

**Issue by jdonny12** [corretto/corretto-8#115]
I was expecting that installation of 8.212 would remove 8.202. 

Upgrade code is the same, so it should, but 8.202 remains.

**Comment by davecurrie** [comment]
@jdonny12 Thanks for the feedback, we're looking into it.

**Comment by cliveverghese** [comment]
This issue was resolved in 8.222.x.x. Closing the issue.
