### ISSUE TITLE
JDK MSI Installer Registry Keys

### ISSUE THREAD

**Issue by timothyd09** [corretto/corretto-8#122]
### Describe the bug
When installing the JDK MSI (amazon-corretto-8.212.04.2-windows-x64.msi), the registry keys are created (HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment).  However, the sub-key below this root that is being made containing the version number is not in the correct format.  The sub-key is "1.8.0.212" when the Oracle Java method is "1.8.0_212".  This is causing some application to be unable to determine if the JRE is installed and fails to run.  Renaming the key to use the underscore instead of the period allows the applications to function properly.

### To Reproduce
Install JDK MSI and look at the registry key name.  Modify the registry key name to resolve.

### Expected behavior
Applications using Java Runtime Environment should launch properly if they are using the registry keys to check for version of Java installed.

### Screenshots
Invalid registry key format:
![image](https://user-images.githubusercontent.com/50115760/56915103-515bc080-6a7b-11e9-917e-1d16841cf23f.png)

Correct registry key format:
![image](https://user-images.githubusercontent.com/50115760/56915205-89fb9a00-6a7b-11e9-81cc-66a0381a09f0.png)

### Platform information
    OS: Windows 10 x64
    Version: amazon-corretto-8.212.04.2-windows-x64.msi

### Additional context
This is just going to impact poorly written applications, but is causing issues nonetheless.

**Comment by yoroto** [comment]
Thanks for reporting it!  We will look into improving it if it helps solving customer pains.

**Comment by timothyd09** [comment]
I also see that the registry keys under the Java Development Kit are the same way.  Haven't run into an issue with this, but it could impact someone.

**Comment by cliveverghese** [comment]
This issue was resolved in 8.222.x.x. Closing the issue.
