### ISSUE TITLE
Link of older Corretto builds

### ISSUE THREAD

**Issue by arpitgautam** [corretto/corretto-8#125]
I am  trying to locate Corretto 8.202.08.2 build for download. This was the first GA build.
However only latest build is published at location below. 
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

From where can I download the older corretto builds?

**Comment by davecurrie** [comment]
@arpitgautam We are working on making archived downloads available. They will be available shortly and I'll update this issue when that happens. Thanks for the feedback.

**Comment by davecurrie** [comment]
We have started posting releases on our GitHub releases page. From now on, links to previous releases will be available from here.
