### ISSUE TITLE
Core dump with correto

### ISSUE THREAD

**Issue by ferozed** [corretto/corretto-8#129]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug

We are getting code dumps when our service runs in production. Our service runs on EC2 instances, and connects to Kinesis and Firehose.

here is the head of the file

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbbd8bf57e0, pid=20469, tid=0x00007fbac10d2700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 22629 C2 sun.security.ssl.InputRecord.decrypt(Lsun/security/ssl/Authenticator;Lsun/security/ssl/CipherBox;)V (303 bytes) @ 0x00007fbbd8bf57e0 [0x00007fbbd8bf57c0+0x20]
#
# Core dump written. Default location: /opt/zillow/services/keystone-sink-standalone/keystone-sink-standalone-1.0.224.master.a539190~ae1~spring_5.2c6f6ed/service/core or core.20469 (max size 8388608 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

### To Reproduce
Steps and (source) code to reproduce the behavior.

NA

### Expected behavior

No core dumps
### Platform information
```
$ uname -a
Linux  3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
```
### Additional context

[orb-del-ksf-001_jboss_hs_err_2019-05-11-182515_pid_20469.log](https://github.com/corretto/corretto-8/files/3209545/orb-del-ksf-001_jboss_hs_err_2019-05-11-182515_pid_20469.log)

**Comment by EricEdens** [comment]
Thanks @ferozed . A couple of items:

1. It'd be really helpful to get a minimal repro program that we can run on our side.
2. Which installation of Corretto 8 are you using? Eg: From the Amazon Linux 2 yum repo, or from the [downloads](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html) page, or somewhere else?

**Comment by EricEdens** [comment]
One more thing: Your bug report talks about 8u192, but the metadata in your core dump doesn't match what's used by Corretto. Here are some snippets:

Core dump:
```
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)

OpenJDK 64-Bit Server VM (25.212-b04) for linux-amd64 JRE (1.8.0_212-b04), 
built on Apr 19 2019 23:23:17 by "root" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
```

Corretto 8u212 metadata:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed mode)
```

Any ideas?

**Comment by ferozed** [comment]
> Thanks @ferozed . A couple of items:
> 
> 1. It'd be really helpful to get a minimal repro program that we can run on our side.
> 2. Which installation of Corretto 8 are you using? Eg: From the Amazon Linux 2 yum repo, or from the [downloads](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html) page, or somewhere else?

I am not sure, but I think it was from the downloads page. Unfortunately, I do not have an easy repro. But we have consistent crashes.

**Comment by ferozed** [comment]
> One more thing: Your bug report talks about 8u192, but the metadata in your core dump doesn't match what's used by Corretto. Here are some snippets:
> 
> Core dump:
> 
> ```
> # JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
> # Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
> 
> OpenJDK 64-Bit Server VM (25.212-b04) for linux-amd64 JRE (1.8.0_212-b04), 
> built on Apr 19 2019 23:23:17 by "root" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
> ```
> 
> Corretto 8u212 metadata:
> 
> ```
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)
> OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed mode)
> ```
> 
> Any ideas?

I forgot to edit the bug template correctly. It is 8u212

**Comment by ferozed** [comment]
Here is another core.
[orb-del-ksf-001_jboss_hs_err_2019-05-09-222947_pid_1989.log](https://github.com/corretto/corretto-8/files/3209638/orb-del-ksf-001_jboss_hs_err_2019-05-09-222947_pid_1989.log)

**Comment by ferozed** [comment]
Here is some analysis from the core file....

   0x7fbbd8bf57c0:      mov    r10d,DWORD PTR [rsi+0x8]
(gdb)
   0x7fbbd8bf57c4:      shl    r10,0x3
   0x7fbbd8bf57c8:      cmp    rax,r10
   0x7fbbd8bf57cb:      jne    0x7fbbd5045ba0
   0x7fbbd8bf57d1:      data32 xchg ax,ax
   0x7fbbd8bf57d4:      nop    DWORD PTR [rax+rax*1+0x0]
(gdb)
   0x7fbbd8bf57dc:      data32 data32 xchg ax,ax
   0x7fbbd8bf57e0:      mov    DWORD PTR [rsp-0x14000],eax
   0x7fbbd8bf57e7:      push   rbp
   0x7fbbd8bf57e8:      sub    rsp,0xb0
   0x7fbbd8bf57ef:      mov    r8,rcx

According to the error log, crash occured at 
`   0x7fbbd8bf57e0:      mov    DWORD PTR [rsp-0x14000],eax`

RSP is....

`RSP=0x00007fbac10d0bf8 is pointing into the stack for thread: 0x00007fbb9c00f800`

**Comment by navyxliu** [comment]
I read your  two crash reports.  it looks like JIT C2 compiler error.

They both crashed in this compiled method. 
# J 22629 C2 sun.security.ssl.InputRecord.decrypt(Lsun/security/ssl/Authenticator;Lsun/security/ssl/CipherBox;)V (303 bytes) @ 0x00007fbbd8bf57e0 [0x00007fbbd8bf57c0+0x20]

A good start is to use CompileCommand to pinpoint the problematic method first.  
-XX:CompileCommand=command,method[,option]
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html#BABDDFII

**Comment by ferozed** [comment]
What exact command should I use for the `command` value of the `-XX:CompileCommand` option? Also, dont we already know the method? Isn't it`sun.security.ssl.InputRecord::decrypt()` ?

**Comment by navyxliu** [comment]
You can take a trial which exclude it.  if it works, it's a workaround too.
-XX:CompileCommand="exclude,sun.security.ssl.InputRecord.decrypt"

-XX:+PrintCompilation should give you more information what JIT compiler does.

**Comment by EricEdens** [comment]
@ferozed : Is the crash limited to Corretto 8u212? Or are you seeing it on other JVMs?

**Comment by ferozed** [comment]
> @ferozed : Is the crash limited to Corretto 8u212? Or are you seeing it on other JVMs?

We get crashes with Oracle's official VM, but those are not the same as this one.

Here are a couple of crashes with Correto:

# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x138580]
#

# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 23532 C2 sun.security.ssl.InputRecord.decrypt(Lsun/security/ssl/Authenticator;Lsun/security/ssl/CipherBox;)V (303 bytes) @ 0x00007f5ce86e8220 [0x00007f5ce86e8200+0x20]

# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 18865 C2 sun.security.ssl.CipherBox.applyExplicitNonce(Lsun/security/ssl/Authenticator;BLjava/nio/ByteBuffer;)I (325 bytes) @ 0x00007f6d1dbc6a00 [0x00007f6d1dbc69e
0+0x20]

Following crashes with Oracle JDK

# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 17533 C2 sun.security.ssl.SSLSocketImpl.readRecord(Lsun/security/ssl/InputRecord;Z)V (872 bytes) @ 0x00007fdd9c578ffb [0x00007fdd9c578640+0x9bb]
#

# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x138580]

**Comment by EricEdens** [comment]
@ferozed, we've had a few people take a look at this internally, and we can't reproduce the issue. In addition, since you're seeing related crashes on other JVMs, our thought is that the issue is not specific to Corretto, but either related to a configuration on your side, or a broader issue within OpenJDK itself.

Given this, we're going to close the issue. If you're able to create a minimal reproduction, feel free to re-open the issue and we'll take a look.
