### ISSUE TITLE
sun.dc.DuctusRenderingEngine GUI Hanging with Correto

### ISSUE THREAD

**Issue by MarChab** [corretto/corretto-8#130]
In the current live system of GUI application where we use Oracle Java 1.8 latest update, the application is normally launched using Oracle javaws.exe by launching the vendor supplied JNLP

When using Oracle Java the application by default it is using sun.dc.DuctusRenderingEngine and everything is working fine as expected.

When using Azul Java the application by default it chooses sun.java2d.marlin.MarlinRenderingEngine and everything is working fine (please note Azul also bundle a copy of their own Java webstart based on icedTea both worked)

When trying to migrate using Java Correto (we have two ways to launch the application here - using a parser that parse the JNLP file and then launch natively the main Java class and the other way is to use Correto/IcedTea)
in the all cases we notice that the application uses by default the sun.java2d.pisces.PiscesRenderingEngine and then the GUI completely hangs throwing those errors

sun.java2d.pisces.PiscesRenderingEngine.getAATileGenerator(java.awt.geom.GeneralPath, AffineTransform[[1.0, 0.0, 1.0], [0.0, 1.0, 1.0]], Region[[0, 0 => 13, 10]], java.awt.BasicStroke@1200000, wide, normalized)
sun.java2d.pisces.PiscesRenderingEngine.strokeTo(java.awt.geom.Line2D$Float, AffineTransform[[1.0, 0.0, 0.0], [0.0, 1.0, 713.0]], java.awt.BasicStroke@74b9c864, wide, normalized, non-AA, sun.java2d.pipe.ShapeSpanIterator)
sun.java2d.pisces.PiscesRenderingEngine.strokeTo(java.awt.geom.Line2D$Double, AffineTransform[[1.0, 0.0, 0.0], [0.0, 0.55, 0.0]], java.awt.BasicStroke@269b13e, thin, normalized, non-AA, sun.java2d.pipe.ShapeSpanIterator)

We also downloaded different Jars that uses different rendering engine including Ductus but they all exhibit the same hanging issues when we used with Correto (https://github.com/bourgesl/marlin-renderer)

We appreciate support to find the reason why the Corretto Java is causing the hangs of the GUI when is trying to use any equivalent of 
sun.dc.DuctusRenderingEngine  

Thank you for helping in this issue.

Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### To Reproduce
Steps and (source) code to reproduce the behavior.

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

**Comment by EricEdens** [comment]
Can you attach a sample to reproduce the issue?

**Comment by alvdavi** [comment]
Hi,

A way for us to reproduce the issue would be key in order to understand it. Also, could you try to test the problem with Corretto while using a release of Marlin?. In order to do it, you will need to get [marlin-0.9.4-Unsafe.jar](https://github.com/bourgesl/marlin-renderer/releases/download/v0_9_4_b2/marlin-0.9.4-Unsafe.jar) from the Marlin releases and then execute corretto with these two extra arguments:
```
-Xbootclasspath/a:{PATH_TO_MARLIN}/marlin-0.9.4-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine
```

Please, let us know if the application still hangs in that scenario.

**Comment by EricEdens** [comment]
Closing since we haven't heard back. Feel free to re-open with a reproduction for us to test it on our side.

**Comment by MarChab** [comment]
Thanks for your reply. We tried this and the issue is still the same. The dev team confirmed that application did not experience any issues with Oracle or Azul. Only when we drop the the Amazon correton Java the issue seems to appear. Thanks for any further support you can provide.

**Comment by MarChab** [comment]
Eric Kindly re-open the ticket.

**Comment by EricEdens** [comment]
Thanks for the response @MarChab -- Can you help us with a reproduction? A small java file that we can compile and run would be ideal.

**Comment by davecurrie** [comment]
@MarChab A reminder that we're not able to reproduce this issue ourselves and need a repro case from you in order to evaluate what to do next.
