### ISSUE TITLE
javacpl.exe missing in corretto-8 

### ISSUE THREAD

**Issue by CHANDU3686** [corretto/corretto-8#133]
Hi Team,

I downloaded and installed corrector 8. Unable to see javacpl.exe in jre of corretto 8. Actually I want to enable "Enable Java content in the browser" option. For that I try to open javacpl.exe (Java Control Panel), but I didn't find it in Corretto 8. 

Please let me know how to enable java content in browser using corretto 8.

**Comment by EricEdens** [comment]
Thanks for the report -- we'll take a look and get back soon.

**Comment by ziyiluo** [comment]
@CHANDU3686 Java Control Panel is a commercial feature in Java Deployment Technologies. It is not implemented in OpenJDK8 (and further versions). Feel free to reopen the issue if you have any further questions.

**Comment by vishalgoel1988** [comment]
@ziyiluo Is there any other way or workaround for this?
