### ISSUE TITLE
Enhance Installer to add standard registry keys on Windows for compat

### ISSUE THREAD

**Issue by bdw429s** [corretto/corretto-8#14]
When installing Oracle Java, there are specific registry keys created which are required for binaries like those created with Launch4J to "find" java.  Can Corretto create the same registry keys so it's a drop in replacement on Windows?  

Here is an example of the registry keys needed to make Corretto get picked up automatically by Launch4j and other libraries.  

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft]

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment]

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8]
"JavaHome"="C:\\Program Files\\Amazon Corretto\\jre8"
"MicroVersion"="0"
"RuntimeLib"="C:\\Program Files\\Amazon Corretto\\jre8\\bin\\server\\jvm.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_192]
"JavaHome"="C:\\Program Files\\Amazon Corretto\\jre8"
"MicroVersion"="0"
"RuntimeLib"="C:\\Program Files\\Amazon Corretto\\jre8\\bin\\server\\jvm.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_192\MSI]
"AUTOUPDATECHECK"="0"
"AUTOUPDATEDELAY"=""
"EULA"=""
"FROMVERSION"="NA"
"FROMVERSIONFULL"=""
"FullVersion"="1.8.0_192"
"INSTALLDIR"="C:\\Program Files\\Amazon Corretto\\jre8"
"JAVAUPDATE"="0"
"JU"=""
"OEMUPDATE"=""
"PRODUCTVERSION"="8.0.1920.12"

```

**Comment by bdw429s** [comment]
In testing, I have found that Azul doesn't add all the keys above, but it does add a subset of them in its MSI installer which is enough to make launchers like Launch4J work out of the box.

**Comment by jim-pickering** [comment]
It would also be nice if Corretto would set the JAVA_HOME environment variable with the installer too. Zulu does that.

**Comment by bdw429s** [comment]
Hi @EricEdens , sandly Launch4j has pretty empty docs when it comes to exactly where in the registry it looks.  The keys above were figured out by people in the community by just comparing their registry before and after installing Java.  I know minimally, Launch4j looks at the smaller set of registry keys in my second post, which is what Azul adds.  The first set of keys were everything added in an Oracle installation of Java.

Here's the Launch4j docs
http://launch4j.sourceforge.net/docs.html
but they only even mention the fact that the registry is used in passing.

> In the standard JRE search based on registry the wrapper detects the type of JRE itself and uses the 32-bit heap limit when needed.

**Comment by yoroto** [comment]
Fixed in Preview 2.

**Comment by ziyiluo** [comment]
This issue is fixed in the new Corretto preview release (1.8.0_192-amazon-corretto-preview2-b12). Change log of this release is now [available](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html). You can find the builds in the [Corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html). Please let us know if you have any further questions. We appreciate your suggestion!

**Comment by bdw429s** [comment]
Thanks so much guys!  Great turn around.

**Comment by cakruege** [comment]
@ziyiluo 

preview2 fixes this problem only half.
1.8.0_192 is created but not 1.8

For example microsoft build agents didn't pickup the existance of corretto:
https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1

**Comment by ziyiluo** [comment]
@cakruege Thanks for reporting, I opened #40 to track your issue.
