### ISSUE TITLE
Java configure exception for cert validation for specific sites

### ISSUE THREAD

**Issue by michalgarcarz** [corretto/corretto-8#142]
Hello Team,

We  are testing Corretto 8 and can not run some of our java applications because of certificate validation errors. With Oracle Java we have been using "Java configure" to add exception for specific sites/URLs so those validations could be bypassed. How to achieve the same with Corretto ?

Example error:
<img width="908" alt="Screen Shot 2019-06-13 at 09 04 33" src="https://user-images.githubusercontent.com/43064944/59412973-e7933e00-8dbe-11e9-9324-2178e503c3a2.png">

Thanks,
Michal

**Comment by yoroto** [comment]
Hi @michalgarcarz 

Can you provide the stacktrace in text? The screenshot you uploaded does not have the full text. Thanks!

**Comment by michalgarcarz** [comment]
Hi @yoroto,

This is exception related to certificate validation. There might be multiple similar errors. This specific one claims that certificate does not have a SAN extension which is referencing used domain name, but we could have another error claiming certificate is not trusted (for example because it's self signed).

In Oracle Java (Control Panel) i always had a chance to disable most of those validations by adding specific URL to exceptions. This way all java applets downloaded from that site would bypass certificate validation.

Is the problem defined clearly ?

We need to be able to do the same in Corretto. I was able to locate java key store so we could manipulate list of trusted CAs, but that is not enough.

Thanks,
Michal

**Comment by yoroto** [comment]
Hi @michalgarcarz 

Have you tried to manually editing the exception.sites list file? The Oracle Java Control Panel actually just editing this list. The default location would be C:\Users\<Your user>\AppData\LocalLow\Sun\Java\Deployment\security\exception.sites . If it does not exist, you can just created it.

**Comment by michalgarcarz** [comment]
Hi @yoroto 
Yes - i've tried that, did not work out, i do not believe Oracle ported that to OpenJDK. Would be great to have any confirmation on that. Thanks !

**Comment by davecurrie** [comment]
Adding functionality to bypass useful security checks is not something we'd do without a very big reason. Closing this issue.
