### ISSUE TITLE
In Fedora, JVM crashes while taking snap of screen with Robot class and createScreenCapture method

### ISSUE THREAD

**Issue by Sabir001** [corretto/corretto-8#159]
### Describe the bug
JVM crashes or PC hangs if app tries to capture snap of screen. 

### To Reproduce
Try capturing screen with Robot class and createScreenCapture  method in Fedora. 

### Expected behavior
Wayland mode prevents app from taking snap. But, JVM should not crash.

### Platform information
    OS: [Fedora]

### Additional context
https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Screen_capture_is_not_available_with_usual_apps

https://bugs.openjdk.java.net/browse/JDK-8171000 (This solved crash issue in Open JDK)

https://bugs.openjdk.java.net/browse/JDK-8196571

**Comment by davecurrie** [comment]
@Sabir001 Is your report concerning JDK-8171000 or JDK-8196571?

If it's the first, could you please make sure you're testing with the latest release of Corretto (8u222)? That fix is included.

If it's the second, that is still an open issue in OpenJDK. We can try to locate a solution or workaround if it's available.

**Comment by Sabir001** [comment]
Well, so I was testing with 212 build. In, 222, it does not  crash. And JDK-8196571 is still open as you said.

One thing, where can I find which OpenJDK bug was fixed in which version of corretto?

**Comment by davecurrie** [comment]
The list of OpenJDK issues included in Corretto is in the release notes here: https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-July/009840.html

**Comment by yishaigalatzer** [comment]
@Sabir001 can you take a look please?

**Comment by Sabir001** [comment]
> @Sabir001 can you take a look please?

Thanks
