### ISSUE TITLE
Debian Package distribution

### ISSUE THREAD

**Issue by JSchoreels** [corretto/corretto-8#16]
Hello there,

Debian-Like system would benefits a lot to have a Debian Package distrubtion of Corretto 8 !

~~The ideal would be a PPA to add in our apt source lists in Ubuntu, to have updates handled by apt :) I can split that feature request in two (one for a .DEB, another for the PPA) if it's more convenient for you.~~ See #29 

Jonathan

**Comment by davecurrie** [comment]
Hi.

We plan to have Ubuntu support in Q1 of 2019. Can I ask what version you are using?

**Comment by JSchoreels** [comment]
XUbuntu 18.04, Kernel 4.15/4.17 on amd64 architecture !

**Comment by bric3** [comment]
In the meantime one can do the following with more or less success : https://stackoverflow.com/a/53502207/48136

**Comment by davecurrie** [comment]
I'm assigning this issue to the General Availability milestone, since we are planning to deliver .debs, as I said earlier. @JSchoreels feel free to open a different issue for PPA since that is a different item that isn't planned for now.

**Comment by JSchoreels** [comment]
Right, I've created #29 and soft-removed the line from my issue description.

Thank you for the feedback about the milestone !

**Comment by alvdavi** [comment]
With the release of Corretto8 preview2 we now have a deb package on the [downloads page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html).

We have tested them on Debian and Ubuntu.
