### ISSUE TITLE
可以给一个和oraclejdk之间源码的区别清单么

### ISSUE THREAD

**Issue by Z-torres** [corretto/corretto-8#160]
Could you give a list of the difference between the source code and oraclejdk,please?

**Comment by navyxliu** [comment]
我们没有oracleJDK的源代码。你要有的话，可以跟我们的代码比较一下，也share一份给我们。。。

We don't have the source of oracleJDK. If you have one, could compare it with our source code here and share it with us?

**Comment by navyxliu** [comment]
We don't have the source of oracleJDK, so we can't provide source code differences.
