### ISSUE TITLE
NPE while trying to getScene from initialize block (JavaFX)

### ISSUE THREAD

**Issue by berry-thawson** [corretto/corretto-8#161]
I'm getting NPE when trying get the scene object in initialize block for a JavaFX application. This works perfectly fine in Oracle JDK.

**Comment by berry-thawson** [comment]
Java version:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment Corretto-8.222.10.1 (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM Corretto-8.222.10.1 (build 25.222-b10, mixed mode)

**Comment by berry-thawson** [comment]
I'm working on system with ubuntu 16.04

**Comment by jguo11** [comment]
berry-thawson@ Thanks reporting the issue. We will investigate this problem. In the meanwhile, can you provide us with your reproduction case?

**Comment by berry-thawson** [comment]
In the initialize block of controller of Main application, I am trying to to access the the scene object like MainApp.getStage().getScene() I am getting a NullPointerException. (We are saving the stage in variable in start block **after creating and setting the scene for it**).

But, that seems to hail from the getScene(), because MainApp.getStage() seems to work fine.

Same happens when I try to access the stage from any component FXML panes like `treeViewDockPane.getScene()`.
Hope this helps.

**Comment by berry-thawson** [comment]
Somehow, the order of execution is different from Oracle JDK. Like the controller's initialize block, executes after the start block of main application in Oracle JDK, but in Correto, initialize block of controller starts executing before start method.

Weird!

**Comment by jguo11** [comment]
I have been experimenting with the following sample application using Oracle JDK 8u221 and Corretto 8u222 on both Ubuntu 16.04 and MacOS:

**Controller.java**

```
package sample;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;

import java.net.URL;
import java.util.ResourceBundle;

public class Controller implements Initializable {

    @FXML
    private Button button;

    @FXML
    private GridPane gridPane;

    @FXML
    private void handleSubmitButtonAction(ActionEvent event) {
        button.setText("Clicked");
    }

    @Override
    public void initialize(URL url, ResourceBundle resource) {
        System.out.println("Controller_initialize_1");
        Scene scene = gridPane.getScene();
        System.out.println("gridPane scene: " + scene);
        System.out.println("button scene: " + button.getScene());
    }
}

```

**Main.java**

```
package sample;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;


public class Main extends Application {
    public static void main(String[] args) {
        System.out.println("java.vendor = " + System.getProperty("java.vendor"));
        System.out.println("===========================");
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        System.out.println("Main_start_1");
        Parent root = FXMLLoader.load(getClass().getResource("sample.fxml"));
        primaryStage.setTitle("TestGetScene");
        primaryStage.setScene(new Scene(root, 300, 275));
        primaryStage.show();
        System.out.println("Main_start_2");
    }
}
```

**sample.xml**

```
<?import javafx.scene.control.Button?>
<?import javafx.scene.layout.GridPane?>
<GridPane fx:controller="Controller"
          fx:id="gridPane"
          xmlns:fx="http://javafx.com/fxml" alignment="center" hgap="10" vgap="10">
    <Button text="Unclicked"
            fx:id="button"
            onAction="#handleSubmitButtonAction"/>
</GridPane>
```

---

The execution results are identical between Oracle JDK and Corretto on both OS.

**OracleJDK**

```
java.vendor = Oracle Corporation
===========================
Main_start_1
Controller_initialize_1
gridPane scene: null
button scene: null
Main_start_2
```

**Corretto**

```
java.vendor = Amazon.com Inc.
===========================
Main_start_1
Controller_initialize_1
gridPane scene: null
button scene: null
Main_start_2
```

`initialize` block of `Controller` class is always executed after `start` of the application in both Oracle JDK and Corretto.

**Comment by jguo11** [comment]
Within the `initialize()` method, the scenes of both `GridPane` and `Button` are `null`. This makes sense because the `initialize()` method is called during the call to `loader.load()`, which is before the UI defined in the FXML is placed in a scene. 

Regarding `MainApp.getStage().getScene()` returns `null`, IMHO, the same explanation can be applied. As when `initialize()` method is called, the primaryStage doesn't have a scene yet.

Above are just my understanding. As I'm not expert in JavaFX, if you can provide a reproduction sample, it'd be very helpful in further investigating this issue.

**Comment by berry-thawson** [comment]
Sorry.
I got confused by different error message and read them as one.
We use Webview that gets initialized in the start method.
But, due to https://github.com/corretto/corretto-8/issues/48, it does not get initialized, and thrown the exceptions.

Then when MainApp.getStage().getScene(), which was called from Platform.runLater() starts to get executed, it has thrown some exceptions.
At the end, they looked like this:
-Exception in Application start method
`An unexpected error occurred in Thread:java.lang.NullPointerException`
`	at ...iewController$11.run(...`

So, why is the WebView just there if it does not work. Why does the the start method does not throw the exception? Just curious. Because, it was really confusing and took a lot of time figure that out, because it was fairly big FX application and WebView initialization was buried deep within application.

Sorry and thanks for your kind support.

**Comment by jguo11** [comment]
> Why is the WebView just there if it does not work?

That's a good question. The fact is that JavaFX 8 indeed has Webkit classes. However, the native webkit core is missing. See [1] 

If I include `WebView webView = new WebView();` in my `start` method. The following message is threw:

```
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/libjfxwebkit.dylib
```

Although I'm running it on MacOS, but I'm sure the message for Linux is similar.

Hope that helps.

[1] http://hg.openjdk.java.net/openjfx/8u/rt/file/9f49e3b6147f/modules/web/src/main/java/com/sun/webkit/WebPage.java#l133
