### ISSUE TITLE
STIG Viewer 2.9 with Corretto 8

### ISSUE THREAD

**Issue by c4m31a** [corretto/corretto-8#168]
Has anyone been able to open STIG Viewer 2.9 with Corretto 8? I changed the environment variable to point to Corretto bin with no luck. Is there a way to show a debugging log to see why it is failing to open? 

Any help Thanks

**Comment by navyxliu** [comment]
Are you talking about https://public.cyber.mil/stigs/srg-stig-tools/ ? 
Could you provide hyperlink of the software and the platform you are using? 

Is there a way to show a debugging log to see why it is failing to open?
> I think this is application-specific question.  You need to refer to software manual.
