### ISSUE TITLE
Use root ca certificates from the OS

### ISSUE THREAD

**Issue by candrews** [corretto/corretto-8#171]
# Describe the bug
Currently, the provided Linux packages (deb and rpm) include bundled CA certificates. For example, the rpm install the file `/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/security/cacerts`

However, it should be configured like the distribution packaged Java (ex `java-1.8.0` on Fedora / Amazon Linux) to use the operating system provided CA certificates by symlinking `/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/security/cacerts` -> `/etc/pki/ca-trust/extracted/java/cacerts`

### To Reproduce
Steps and (source) code to reproduce the behavior.
1. `docker run -it amazoncorretto:8` (which is just amazonlinux with the rpm installed, see Dockerfile at https://github.com/corretto/corretto-8-docker/blob/cd7c7563f35cc12cf50a9a418e5ecaa73810a8e8/Dockerfile)
2. Note that `/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/security/cacerts` is a file, not a symlink

### Expected behavior
When using the rpm, `/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/security/cacerts` should be a symlink to `/etc/pki/ca-trust/extracted/java/cacerts`
When using the deb, a similar link should exist. 

### Screenshots
n/a

### Platform information
    OS: Amazon Linux 2
    Version build 1.8.0_222-b10

### Additional context
I believe that solving this issue is a prerequisite for upstreaming Corretto into Linux distributions which is tracked at https://github.com/corretto/corretto-8/issues/114

**Comment by yoroto** [comment]
Hi @candrews 

Thank you for raising the issue! We will discuss about it and get back to you.

**Comment by davecurrie** [comment]
@candrews This is by design. We purposely bundle this set of cacerts with Corretto in order to maintain a consistent experience across Operating Systems in the universal packages we distribute.

There is value in linking to the system cacerts, though, and we believe the right place to do this is in packages created by distribution owners e.g. Corretto for Amazon Linux 2.

**Comment by candrews** [comment]
> This is by design. We purposely bundle this set of cacerts with Corretto in order to maintain a consistent experience across Operating Systems in the universal packages we distribute.

I still think this behavior is surprising/confusing. When a user installs a package, there is an expectation that it will respect system configuration.

> There is value in linking to the system cacerts, though, and we believe the right place to do this is in packages created by distribution owners e.g. Corretto for Amazon Linux 2.

The packaging of Corretto for Amazon Linux 2 doesn't exist yet, right? Could you link to an issue (or somewhere else) where one could track the progress of that?

**Comment by davecurrie** [comment]
Corretto 8 and 11 are both available on AL2 already. Check out the appropriate docs at https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/amazon-linux-install.html and https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/amazon-linux-install.html.
