### ISSUE TITLE
Corretto 8u232 will not install on macOS Catalina

### ISSUE THREAD

**Issue by isaki** [corretto/corretto-8#174]
### Describe the bug

Corretto 8 will not install on Catalina (amazon-corretto-8.232.09.1-macosx-x64.pkg).

### To Reproduce

- Download Corretto 8u232
- Attempt to install Corretto 8u232

### Expected behavior
Corretto 8u232 should install and replace my 8u222 installation.

### Screenshots
![image](https://user-images.githubusercontent.com/10616227/66950757-09c7f180-f027-11e9-99d3-049543556273.png)

### Platform information
    OS: macOS 10.15
    Version: amazon-corretto-8.232.09.1-macosx-x64

### Additional context
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution
https://www.macrumors.com/2019/09/03/apple-macos-catalina-notarization-mac-apps/

**Comment by ziyiluo** [comment]
@isaki The issue of notorization on OpenJDK is still open and under discussion. See [JDK-8223671](https://bugs.openjdk.java.net/browse/JDK-8223671). We have been tracking this issue but the solution is still not clear. Therefore, we prefer to keep our current packaging logic. We are prioritizing this issue and planning to release new notarized packages when the situation is clearer. In the meantime, have you tried to right-click the installer and click "Open" to override the warning message?

**Comment by ziyiluo** [comment]
@isaki Quick update, Apple just notarized both Corretto 8 and 11 installers. You can expect no further warning message as long as your mac is connected to the network.

**Comment by isaki** [comment]
@ziyiluo I had indeed tried to right click and select open; I was unable to install. I am on the latest supplemental security patch so maybe it worked in the initial release or beta. As for right now, I am able to open the package on the command line and run the installer without issue. Thank you!
