### ISSUE TITLE
File javafx-src.zip missing: source code debugging for OpenJFX not enabled

### ISSUE THREAD

**Issue by bernd-aws** [corretto/corretto-8#19]
### Describe the bug
The preview release is missing file javafx-src.zip with the compressed source code of OpenJFX. Without it, debugging through OpenJFX code in an IDE won't work out of the box.

### Expected behavior
We found that the naming of the file must be exactly "javafx-src.zip" and it has to be sitting right next to "src.zip".

### Platform information
All platforms we ship for.

**Comment by alvdavi** [comment]
This was a build issue. it is planned to be fix in the next release.

**Comment by ziyiluo** [comment]
This is fixed in mac build but not in Windows yet.

**Comment by yoroto** [comment]
The fix has made it to the latest u202 release which we published today.
