### ISSUE TITLE
Linux localinstall is not installing deplist

### ISSUE THREAD

**Issue by CharmsStyler** [corretto/corretto-8#193]
### Describe the bug
As per instructions here https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/generic-linux-install.html
yum localinstall is not  installing openjdk deplist see  `yum deplist java-1.8.0-openjdk.x86_64`

### To Reproduce
sudo yum localinstall java-1.8.0-amazon-corretto-devel-1.8.0_232.b09-1.x86_64.rpm

Run sample java application
```
import java.awt.GraphicsEnvironment;
class FontTest{
  public static void main(String[] args) {
         String[] fonts = GraphicsEnvironment
                 .getLocalGraphicsEnvironment()
                 .getAvailableFontFamilyNames();

         for (String font : fonts) {
             System.out.println(font);
         }
         
   }
}
```

### Expected behavior
install corretto8 along with its(openjdk) package dependencies

### Platform information
    OS: Centos
    Version java-1.8.0-amazon-corretto-devel-1.8.0_232.b09-1.x86_64.rpm

**Comment by alvdavi** [comment]
Hi,

Thanks for pointing this out. Back in the day we took the decision to make Corretto RPMs not to depend on anything as they were just the tgz repackaged. We are reconsidering this position right now, we will keep this ticket updated.
