### ISSUE TITLE
Support distribution via tar.gz/ZIP archives

### ISSUE THREAD

**Issue by joschi** [corretto/corretto-8#2]
Amazon Corretto is currently distributed in 4 flavors:

* RPM for RedHat-based Linux distributions: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/amazon-linux-install.html
* PKG (installer) for macOS: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/macos-install.html
* MSI for Windows 7 and higher: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/windows-7-install.html
* Docker image based on Amazon Linux 2: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/docker-install.html

In order to support other distribution systems (eg: Docker images, SDKMan) it would be great if it was offered in "plain" archives (tar.gz, ZIP) containing the binaries for the respective operating systems additionally to the aforementioned distributions.

**Comment by EricEdens** [comment]
Great request! 

I'm going to break this into individual items so that we can track them and gather feedback on each. I think we can break it down into three:
1. Provide archive files in addition to system installers. (Paring down this issue)
2. Vend Corretto through SDKMan. (Split to #11)
3. Provide a portable Linux binary that can work on multiple distributions. (Split to #10)

**Comment by bric3** [comment]
How can we make sure the dependencies are right, like `libfontconfig1` or the java `cacerts` file.

Centos dcoker image packages a cacerts in /etc/pki/java/cacerts, but other Linux distributions on docker don't, like Debian where you need to install the ca-certificates-java which absolutely require their own headless jre openjdk among others.

**Comment by marc0der** [comment]
Normally the JDK zip/tarball distributions are packaged as self contained binaries without any external dependencies. For reference, have a look at the internals of the [OpenJDK tarball distribution](http://jdk.java.net/11/).

**Comment by davecurrie** [comment]
We have slated this for GA, so I have added it to that milestone.

**Comment by vijayyadav06** [comment]
So I see a tar version on the download page today for Linux. https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

Linux x64 JDK TGZ | amazon-corretto-preview2-8u192-linux-x64.tar.gz (https://d3pxv6yz143wms.cloudfront.net/amazon-corretto-preview2-8u192-linux-x64.tar.gz) | 7769adffefce042663e5c6df64c092e4 | Download
-- | -- | -- | --

**Comment by alvdavi** [comment]
As part of Corretto8 preview2 we have made a TGZ version available for generic Linux systems. We will proceed to close this issue, but let us know if you have any further comments

**Comment by glucas** [comment]
Will there be a zip distro for Windows as well? 

Per #40, #39, #43  -- The Windows installer is making a log of system-wide changes that may not be desirable, particularly on machines with multiple JVMs installed. A zip distro would be a welcome alternative -- or perhaps I should file a separate issue to support a Windows installer option to *not* make system-wide environment changes?

**Comment by davecurrie** [comment]
@glucas There are JDK and JRE zips for Windows available on the [downloads page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html). These are going to continue being updated at the same time as the Windows installers.

We also have more issues about changes to the installer, some of which you've commented on. We also plan to keep enhancing the installer in future releases.

Do these actions address your concerns?

**Comment by glucas** [comment]
Yes, thanks. Sorry for the noise, not sure how I overlooked that.
