### ISSUE TITLE
On Linux Support, Older Versions of GLIBC

### ISSUE THREAD

**Issue by lordbuddha** [corretto/corretto-8#20]
Raising this as a new issue as #17 was closed I think incorrectly.  

Yes want a tgz artifact,  but my point was that we need the Linux binaries linked such that those binaries will run on older versions of Linux which have older versions of GLIBC.

The current RPM contains binaries that require GLIBC_2.14.   

But RHEL 6 only has GLIBC_2.12.   Sure I could use LD_LIBRARY_PATH to supply my own GLIBC version, but that is more awkward then just being able to use what is there.

I pointed out in #17 that OpenJDK from Azul will work on GLIBC_2.5.   

So there really seems to be no reason why Corretto-8 could not be built such that it will run on RHEL 6 (or other antiques of that ilk).

**Comment by davecurrie** [comment]
Thank you for your suggestion. I see that this is different from #10, so we'll keep this enhancement request open too.

**Comment by alvdavi** [comment]
Corretto8 preview2 has been released. Versions listed as "Linux x64" target GLIBC_2.11.

That should allow its execution on RHEL6 and also on Ubuntu 14.04 (Trusty Tahr) and Debian Jessie.
