### ISSUE TITLE
Few random threads from ThreadPoolExecutor in WAITING state report higher CPU usage for prolonged period compared to Oracle Java 8u65

### ISSUE THREAD

**Issue by dhruvil-93** [corretto/corretto-8#202]
### Describe the bug
Few random threads from ThreadPoolExecutor in WAITING state report higher CPU usage for prolonged period in Amazon Corretto 8u232 compared to Oracle Java 8u65.

top output -
```
10641 app        20   0 30.4g  21g 112m S 47.9 70.2 657:12.56 657:12 pool-5-thread-1
10914 app        20   0 30.4g  21g 112m R 33.7 70.2 508:25.46 508:25 pool-5-thread-1
10009 app        20   0 30.4g  21g 112m R 33.7 70.2 454:39.50 454:39 pool-5-thread-5
10220 app        20   0 30.4g  21g 112m S 33.7 70.2 444:55.14 444:55 pool-5-thread-7
12230 app        20   0 30.4g  21g 112m R 32.8 70.2 438:18.02 438:18 pool-5-thread-2
```

It can be seen that some random threads are utilizing 32.8-47.9% CPU for prolonged time (>400 minutes). However, the thread dump at the same time proves otherwise. The threads are in WAITING state as per thread dump.

```
pool-5-thread-1
priority:5 - threadId:0x00007f13b0033000 - nativeId:0x8c9 - nativeId (decimal):2249 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000037ca83da0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

pool-5-thread-5
priority:5 - threadId:0x00007f13a0020800 - nativeId:0x8cd - nativeId (decimal):2253 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000037ca83da0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

pool-5-thread-7
priority:5 - threadId:0x00007f139c021800 - nativeId:0x8cf - nativeId (decimal):2255 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000037ca83da0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

pool-5-thread-2
priority:5 - threadId:0x00007f13bc021800 - nativeId:0x8ca - nativeId (decimal):2250 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000037ca83da0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### Platform information
    OS: Amazon Linux 2 (Docker image: debian:8.11)
    Version: OpenJDK 64-Bit Server VM Corretto-8.232.09.1 (build 25.232-b09, mixed mode)

### Additional context
Same behavior is not observed when switching back to Oracle Java 8u65.

Have raised a question on StackOverflow as well - https://stackoverflow.com/questions/59467696/linux-top-command-reporting-high-cpu-usage-for-java-threadpoolexecutor-thread-in

**Comment by navyxliu** [comment]
hi, @dhruvil-93 
In my understanding,  a thread doesn't consume any cpu if it's in waiting(park) state. if you use top, the cpu time shouldn't increase. The column TIME is total consumed CPU time when it was running. 

I don't quite understand your top message. Could you provide the table header and your top command?  Why there're 2 pool-5-thread-1?  If 47.9 is %CPU,  I don't understand why sleeping thread took 47.9% CPU time. Could you elaborate your top output? 

> 10641 app        20   0 30.4g  21g 112m S 47.9 70.2 657:12.56 657:12 pool-5-thread-1
> 10914 app        20   0 30.4g  21g 112m R 33.7 70.2 508:25.46 508:25 pool-5-thread-1
> 10009 app        20   0 30.4g  21g 112m R 33.7 70.2 454:39.50 454:39 pool-5-thread-5
> 10220 app        20   0 30.4g  21g 112m S 33.7 70.2 444:55.14 444:55 pool-5-thread-7
> 12230 app        20   0 30.4g  21g 112m R 32.8 70.2 438:18.02 438:18 pool-5-thread-2

**Comment by dhruvil-93** [comment]
Hey @navyxliu please find below the latest top output from a different application instance. 

Also, the TIME column is not constant in this case and is increasing indicating thread using CPU. 

However, thread dump and Visual VM prove otherwise as stated in the original post.
```
top - 12:16:34 up  5:03,  0 users,  load average: 10.64, 9.74, 9.72
Threads: 7123 total,  10 running, 7113 sleeping,   0 stopped,   0 zombie
%Cpu(s): 28.3 us, 16.0 sy,  0.0 ni, 54.8 id,  0.0 wa,  0.0 hi,  0.9 si,  0.0 st
KiB Mem:  32121548 total, 26088752 used,  6032796 free,   134028 buffers
KiB Swap:        0 total,        0 used,        0 free.  2008744 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 5660 app        20   0 30.582g 0.021t  97556 S 47.0 69.6 128:42.34 pool-5-thread-3
 4804 app        20   0 30.582g 0.021t  97556 R 49.6 69.6  98:41.07 pool-5-thread-1
 2695 app        20   0 30.582g 0.021t  97556 R 49.9 69.6  93:10.97 pool-5-thread-5
 2392 app        20   0 30.582g 0.021t  97556 S 48.0 69.6  79:47.46 pool-5-thread-9
 2284 app        20   0 30.582g 0.021t  97556 S  3.2 69.6  13:04.52 pool-5-thread-2
```

**Comment by dhruvil-93** [comment]
Currently, the JVM flags being used are as following in case it helps -

```
-XX:+UseG1GC
-XX:InitiatingHeapOccupancyPercent=70
-Xss228k
-XX:G1HeapRegionSize=4
-XX:MaxGCPauseMillis=200
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:NativeMemoryTracking=detail
-XX:+PrintTenuringDistribution
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=20
-XX:GCLogFileSize=512M
-Xloggc:/home/app/logs/gc/${CURRENT_DATETIME}.log
-Xms100m
-Xmx${JAVA_XMX}m
-XX:ActiveProcessorCount=${CPUS}
-XX:MaxMetaspaceSize=256m
-XX:CompressedClassSpaceSize=200m
-Dcom.sun.management.jmxremote=true
-Dcom.sun.management.jmxremote.port=6001
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.rmi.port=6001
-Djava.rmi.server.hostname=${HOST}
-XX:+UsePerfData

```

**Comment by dhruvil-93** [comment]
Attaching a screenshot from EC2 monitoring tab showing CPU usage of the host machine.
Because CPU never comes down due to this issue, the ASG keeps launching additional instances and it's a cascading effect until it reaches Max ASG size.

<img width="913" alt="Screen Shot 2019-12-24 at 1 05 12 PM" src="https://user-images.githubusercontent.com/6476145/71506202-f7c7c200-28a5-11ea-8914-b8773cfef7ec.png">

**Comment by navyxliu** [comment]
hi, @dhruvil-93, 

Thank you for providing some more details. 
 Let me I try to explain it. Presumably, you are using linux kernel and NPTL pthread. 

If the stacktrace of a thread looks like this, it must yield CPU at that time. 
> stackTrace:
> java.lang.Thread.State: WAITING (parking)
> at sun.misc.Unsafe.park(Native Method)
> - parking to wait for <0x000000037ca83da0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
> at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)

'park' is a JVM term. you can think it yields cpu and wait for a conditional variable.  The status 'S' of top has nothing to do with  JVM. Top gets the status from linux kernel.  'S' indicates the 'task' (A term of linux kernel, maybe a process or a thread) is in waiting queue instead of in running queue.  It shouldn't consume any CPU time if it is sleeping. 
 
My theory is that you observed a 'S' thread consumes 47.0% CPU comes from the skew view of top. By default, the sampling interval of top is 3s. The CPU utilization is defined by the running time divided by the total sample time.  My guess is that the thread has at least one context-switch in the middle of the sampling time.  You can keep an eye on that thread and see if it flips to 'R'.  In another way, you can read the field nr_switches from /proc/$pid/task/$tid/sched.

This stackoverflow question discussed a very similar issue. I think we can take it as reference. 
https://stackoverflow.com/questions/12972918/why-does-park-unpark-have-60-cpu-usage

My guess is that your application has some workloads for your thread execution service. That's why it consumed a lot of  CPU time. How about you remove all your workloads and observe it again?  If the cpu utilization disappear for the worker threads, then JVM acts by design. It's because they are never waken up and work on any workload.  If it is not the case, feel free to post more information of your application. 

thanks,
--lx
