### ISSUE TITLE
Cannot browse the Corretto Debian repository

### ISSUE THREAD

**Issue by seanabraham** [corretto/corretto-8#203]
### Describe the bug
I was happy to see that there is now a Corretto debian repository and it looks like it works when interact with it via the provided instructions (using apt-get). However, I'm unable to browse the repository when I navigate to it in the browser and also unable to proxy it from an artifact store (Artifactory in this case). Based on what I've seen with other debian repositories, I'd expect to be able to do both of those things.

### To Reproduce
Navigate to https://apt.corretto.aws in the browser, see "Access Denied".

### Expected behavior
I'd expect to be able to browse packages in the browser or at least proxy it from Artifactory. For example, visiting http://archive.canonical.com/ubuntu in the browser allows you to browse through the repository.

### Screenshots
What I see when visiting https://apt.corretto.aws:
![image](https://user-images.githubusercontent.com/1400053/71941453-9f7aa500-316e-11ea-9305-1f8d93888a0b.png)

An example of another debian repository where this works as expected:
![image](https://user-images.githubusercontent.com/1400053/71941510-d8b31500-316e-11ea-9297-94dd077b3289.png)

**Comment by cliveverghese** [comment]
Hi @seanabraham 

Thank you for using the Corretto Debian repository. We currently do not have this UI. But, we are interested to know more about how you would be using this UI.

**Comment by ziyiluo** [comment]
@seanabraham I created a separate issue #213 to address the Artifactory proxy issue. However, we currently do not have plan to implement the repository browser UI. I'm closing this issue, but feel free to reopen it if you have other use cases that must require this UI.
