### ISSUE TITLE
Issue while connecting to Web-service where SSL certificate is installed, getting DH key Pair issue

### ISSUE THREAD

**Issue by ashutosh-debug** [corretto/corretto-8#205]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug
We are running our application with Amazon coretto JDK 8 and getting the below issue while connecting the other webservice through the webservice client. We have used Apache Axis 1.3 to call the webservice. The webservice is called from a Linux server. The SSL certifcate is installed in the server where the webservice is deployed. Basically our application is running in a Linux server and calling the remote webservice where the SSL certificate is installed. The certifcate Public key size is 2048 bits. Please help on this.

[taskExecutor-2] INFO  com.t.at.ws.client.TosStub - start[1574925203281] time[450] tag[TosStub - GetOrganizationsByCode]
[2019-11-28 07:13:23,734] [taskExecutor-2] INFO  2329010-ME-MSA-20191128_011200_000-13458308 - Transition modify user in tos system failed.
com.t.at.msa.queue.TransitionFailedException: Failed to modify user in Tos: org.apache.axis2.AxisFault: java.lang.RuntimeException: Could not generate DH keypair
        at com.t.at.msa.queue.controllers.transitions.ModifyTosUser.applyTransition(ModifyTosUser.java:144)
        at com.tf.athena.mtsa.queue.impl.QueueConsumer.processTransaction(QueueConsumer.java:153)
        at com.t.at.msa.queue.impl.QueueConsumer.run(QueueConsumer.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
**Caused by: com.t.at.ws.client.CallFailedException: org.apache.axis2.AxisFault: java.lang.RuntimeException: Could not generate DH keypair
        at com.t.at.ws.client.TosStub.getCompanyById(TosStub.java:286)
        at** com.t.at.msa.queue.controllers.transitions.ModifyTosUser.applyTransition(ModifyTosUser.java:85)
        ... 5 more
Caused by: org.apache.axis2.AxisFault: java.lang.RuntimeException: Could not generate DH keypair
        at org.apache.axis2.AxisFault.makeFault(AxisFault.java:417)
        at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:72)

Please help on this. We need it urgently

### To Reproduce
Steps and (source) code to reproduce the behavior.

Create a soap web service and deployed it in a system. Where SSL certificate is installed.
Create a webservice client using Apache Axis 1.3 and call the webservice.

### Expected behavior
It should connect the remote  webservice and successfully send the request to the Webservice.

### Platform information
    OS: Red hat Linux
    Version [amazon-corretto-8.232.09.1-linux-x64.tar.gz" (output from "java -version")]

**Comment by AzeemJiva** [comment]
Hi,
  From my understanding this points to either the DH modulus being improperly setup (check for leading zeros) or is larger than 2048 bits.  Have you tried this with Corretto 11 or OpenJDK8?

**Comment by ashutosh-debug** [comment]
I have checked the server certificate where the web-service has been deployed and found that the the public RSA key size is 2048 bits. I am connecting to the https link through my webservice client and getting the above error. where to check the leading zeros or key size which is more then 2048 bits in client machine. Also with coretto 11, Openjdk9,10,13 I am not able to build the application gettin the below error. Only coretto jdk 8 is successfull in build but failing at runtime.

How to set up the DH modules as per your comment please let me know.
build error in coretto 11, Openjdk9,10,13
*******************************************************
java.lang.NoClassDefFoundError: sun/misc/Service
        at org.apache.neethi.AssertionBuilderFactory.<clinit>(AssertionBuilderFa
ctory.java:57)
        at org.apache.neethi.PolicyEngine.<clinit>(PolicyEngine.java:51)
        at org.apache.axis2.util.PolicyUtil.getPolicyComponent(PolicyUtil.java:1

**Comment by AzeemJiva** [comment]
Have you tried OpenJDK8?  The reason you can't build is that it looks like your code depends on sun.misc.Service which was removed from Java9 onwards.   You may have to rewrite your code, to support the newer Java implementations or reduce your DH size to under 2048bits.  

Also have you seen this?  https://stackoverflow.com/questions/6851461/why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception.

**Comment by ashutosh-debug** [comment]
Hi Azeem,
I have used coretto JDK 8 which is openjDK implementation as you know, I am able to build it but during runtime means connecting the webservice through client getting DH key issue. The link the one  I am trying to connect is the Https link.  Also want to know how to reduce the DH Size.

Regards,
Ashutosh

**Comment by davecurrie** [comment]
@ashutosh-debug I have some questions to help us understand the problem:
Does this issue happen using builds of OpenJDK8 other than Corretto? Is this something new that used to work before? It looks like a reasonable application-level error, would you expect it to work?

**Comment by ziyiluo** [comment]
If you have further questions, feel free to reopen.

**Comment by bilgehanm** [comment]
I have a similar problem. An application that works fine with oracle jre1.8.0_73 started throwing ssl peer not authenticated errors when upgraded to corretto jre_1.8.0_282.
