### ISSUE TITLE
Update OS detection code to recognize Windows Server 2019

### ISSUE THREAD

**Issue by sangirash** [corretto/corretto-8#207]
We are using Corretto 8 u 202 in our application. Just want to ensure that the issue https://bugs.openjdk.java.net/browse/JDK-8220415 is addressed in update 202 or not.
as per update @ https://github.com/corretto/corretto-8/issues/92 the issue is resolved in u212 but want o check whether the fix is ported in 202 as well or not. 

Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### To Reproduce
Steps and (source) code to reproduce the behavior.

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

**Comment by alvdavi** [comment]
Hi,

[JDK-8220415](https://bugs.openjdk.java.net/browse/JDK-8220415) is only in Corretto versions 8.212.x.x and higher. Once a version of Corretto with a new minor version is released (the second component in the version number), no further changes are done to old versions.
