### ISSUE TITLE
GPG key used to sign debian repository changed

### ISSUE THREAD

**Issue by stbuehler** [corretto/corretto-8#209]
A key rollover should be documented, and I can't find any note regarding it. Also please don't create a new key every month:

Old key:
```
pub   rsa4096 2019-11-22 [SCEA] [expires: 2024-11-20]
      CC160DF5CEF1B148857EBA29F9CC653EBE9CF76D
uid           Amazon Services LLC (Amazon Corretto release) <corretto-team@amazon.com>
```

New key (downloaded from https://apt.corretto.aws/corretto.key):
```
pub   rsa4096 2019-12-05 [SCEA] [expires: 2024-12-03]
      6DC3636DAE534049C8B94623A122542AB04F24E3
uid           Amazon Services LLC (Amazon Corretto release) <corretto-team@amazon.com>
```

I'm pretty sure I observed the old key "Dec 21" (not quite sure how long apt has been complaining).

**Comment by cliveverghese** [comment]
hi @stbuehler 

Both the keys are owned by us and safe to use. The key currently in place is what we will keep signing future releases with  (i.e. 6DC3636DAE534049C8B94623A122542AB04F24E3) although we previously released our apt-repos signed with our pre-release key (i.e. key id: CC160DF5CEF1B148857EBA29F9CC653EBE9CF76D ). We will update our change log to make this clear. Thanks for pointing it out.

**Comment by stbuehler** [comment]
Thanks for the clarification!

**Comment by osoriano** [comment]
It's now `2024-12-03` and the key shows as expired @cliveverghese 

```
❯ wget -q -O - https://apt.corretto.aws/corretto.key | gpg --show-key  | grep expired
pub   rsa4096 2019-12-05 [SCEA] [expired: 2024-12-03]
```

**Comment by davidxia** [comment]
related issue https://github.com/corretto/corretto-21/issues/82

**Comment by thaycafe** [comment]
Based on a related issue https://github.com/corretto/corretto-21/issues/82 should be fixed but I'm using `maven:3.9.6-amazoncorretto-8-debian` and still not working.

**Comment by lutkerd** [comment]
You may need up update the existing key to match the new key in the repo with the following:

```
wget -O - https://apt.corretto.aws/corretto.key | sudo gpg --dearmor -o /usr/share/keyrings/corretto-keyring.gpg && \
echo "deb [signed-by=/usr/share/keyrings/corretto-keyring.gpg] https://apt.corretto.aws stable main" | sudo tee /etc/apt/sources.list.d/corretto.list
```

**Comment by lfcaldeira** [comment]
Adding the new key does not work. Is this image being supported?
