### ISSUE TITLE
Support Windows 32bit binaries

### ISSUE THREAD

**Issue by yishaigalatzer** [corretto/corretto-8#22]
Track the request to support Windows 32bits from Windows 7 and on as asked on https://stackoverflow.com/questions/53420091/amazon-corretto-8-32-bits by https://stackoverflow.com/users/1579823/jose-renato

**Comment by mar1u50** [comment]
Is there already a plan?

We cannot deliver our software with Oracle JDK anymore but we must deliver a 32 bit version ....

Thank you for info.

**Comment by davecurrie** [comment]
@mar1u50 we are planning to have a Windows 32-bit binary for General Availability. Adding to that milestone for tracking.

**Comment by yoroto** [comment]
Released x86 Windows installer in Preview 2. Closing it now.
