### ISSUE TITLE
Corretto 8's EOL

### ISSUE THREAD

**Issue by yamadamn** [corretto/corretto-8#225]
This issue is just a question.

### Is your feature request related to a problem?
No.

### Describe a solution you would like
Red Hat OpenJDK Life Cycle and Support Policy[1] have changed, and the EOL of Java SE 8 has extended until May 2026.
Also, AdoptOpenJDK has changed the End of Availability[2] for Java 8.

Do you have any plan to extend Corretto 8's EOL?
According to FAQ[3], it's still "until at least June 2023"

[1] https://access.redhat.com/articles/1299013
[2] https://adoptopenjdk.net/support.html
[3] https://aws.amazon.com/corretto/faqs/#support

### Describe alternatives you have considered
Use another JDK distribution.

### Additional context
I think Corretto's EOL depends on OpenJDK upstream led by Red Hat.
https://shipilev.net/jdk-updates/map/

**Comment by navyxliu** [comment]
Thank you for the consideration of Corretto-8.  I've got your question and I will consult our project manager. stay tuned.

**Comment by davecurrie** [comment]
@yamadamn We are looking into extending our support to match. We will likely take a few weeks to come up with a decision on extending Corretto 8 support into 2026 and will consider Corretto 11 also. LTS is an area where we continuously evaluate community needs now and as we move forward.

**Comment by yamadamn** [comment]
Hi, I found the news "Amazon Corretto 8 & 11 support extended"[1].
Thank you for your great decision!
I will close this issue.

[1] https://aws.amazon.com/jp/about-aws/whats-new/2020/08/amazon-corretto-8-11-support-extended/
