### ISSUE TITLE
Mac codesigning and notarization issues with certain dylibs

### ISSUE THREAD

**Issue by jsimmondsIDBS** [corretto/corretto-8#227]
### Describe the bug
Issues with codesigning and notarization on Apple Macs due to a certain set of `dylib` files in the latest Mac 64-bit JRE. This applies to the following:
- libsplashscreen.dylib
- libawt_libawt.dylib
- server/libjvm.dylib
- libfreetyp.dylib.6
- libmimage.dyliv
- libfontmanager.dylib
- libjpeg.dylib
- liblcms.dylib
- libosxapp.dylib
- libawt.dylib
- libprism_sw.dylib

#### Codesigning
Attempting to perform Mac codesigning on the latest version `8.242.08.2` returns errors on a number of dylibs in the Mac JRE (within the Frameworks" folder), e.g.
```java
Our.app: main executable failed strict validation
In subcomponent: /Users/build/Our.app/Contents/Frameworks/jre/Contents/Home/lib/libjpeg.dylib
```

#### Notarization
Returns the following error for all `dylib` files listed above when JRE is in the "Plugins" folder:
```javascript
    {
      "severity": "error",
      "code": null,
      "path": "App.zip/Our.app/Contents/Plugins/jre/Contents/Home/lib/libjpeg.dylib",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "App.zip/Our.app/Contents/Plugins/jre/Contents/Home/lib/libjpeg.dylib",
      "message": "The signature algorithm used is too weak.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "App.zip/Our.app/Contents/Plugins/jre/Contents/Home/lib/libjpeg.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    
```

#### Codesigning
Perform codesigning on a Mac JRE embedded within a Mac app (`.app` extension), via:
```
codesign --sign "cert-here" --entitlements app.entitlements --deep --options=runtime --timestamp --force --keychain "keychain-here" "Our.app"
```

#### Notarization
Perform notarization on the `.app` file inside a zip with:
```
xcrun altool --notarize-app --primary-bundle-id "com.our.app" --username apple-dev@email.com --password password-here --file App.zip
```

### Expected behavior
Mac codesigning and notarization should pass without errors

### Platform information
    OS: [Mac OS X 10.15]
    Version [Mac 64-bit JRE 8.242.08.2]

### Additional context
Codesigning was working on previous version `8.202.08.2`
I put both of these in the same issue since they both relate to the exact same set of `dylib` files so its probably the same issue causing both.

**Comment by ziyiluo** [comment]
Thanks for reaching out. Quick question, from the error message you posted: `The signature of the binary is invalid.`, looks to me the library is broken. Could you try to verify the signature of the library by running:
```
codesign -dv <path_to_jre>/Contents/Home/lib/libjpeg.dylib
```
I guess you extract the JRE from the Corretto JDK8 and bundle in your app. Here's the codesign output of the latest `8.242.08.2` build:
```
$ codesign -dv amazon-corretto-8.jdk/Contents/Home/jre/lib/libjpeg.dylib
Executable=/tmp/amazon-corretto-8.jdk/Contents/Home/jre/lib/libjpeg.dylib
Identifier=jre#lib#libjpeg
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=1435 flags=0x10000(runtime) hashes=36+5 location=embedded
Signature size=9047
Timestamp=Feb 21, 2020 at 10:07:50 AM
Info.plist=not bound
TeamIdentifier=94KV3E626L
Runtime Version=10.10.0
Sealed Resources=none
Internal requirements count=1 size=176
```
Each Corretto macOS build is notarized by Apple before release. Invalid signature should have been detected by Apple.

**Comment by jsimmondsIDBS** [comment]
Thanks for your response @ziyiluo.
I think this is the key of the issue for some reason within our workflow, those certain dylibs are either:
- not signed due to `main executable failed strict validation` (happens when I try and do them individually as well as within the "Frameworks" folder mentioned above)
- skipped in the signing process, thus causing the notarization errors later

Running the command you sent just confirms this since after performing the codesigning within the "Plugins" folder (where it seems to get skipped), the libs return:
```
.../Contents/Home/jre/lib/libjpeg.dylib: code object is not signed at all
```
Other files in the same folder return what you showed for a successfully signed file (as expected).

So this is a codesigning issue rather than a notarization issue, if codesigning were to succeed then notarization would most likely also succeed (as it does for all the other files in the JRE). 

Is there anything different about those specific dylibs listed previously that could be causing this?
Could it be because we are using a Mac on more recent version (`10.15.3`)?

**Comment by jsimmondsIDBS** [comment]
I've been looking at this more today and found out why it wasn't working for us. After looking at the [Apple codesigning docs](https://developer.apple.com/library/archive/technotes/tn2206/_index.html) they state:

> **codesign says my main executable failed strict validation.**
> - Your Mach-O executable does not conform to modern Mach-O layout rules.
> - You may be using a third party development product that hasn't been brought up to date, or post-processed your file in unsupported ways.

This made me change a couple things in our Maven build which was copying the Mac JRE to the correct folder which looks likes was messing with some of the files (still unsure exactly why and only with specific files), but all in all codesigning/notarization now works for us with the latest JRE 😅 

Thanks again for your quick response, confirming that it should work with all the processes you have in place to support this on Mac, much appreciated.
