### ISSUE TITLE
Windows: Corretto sets wrong MSI UninstallString; msiexec uninstall fails

### ISSUE THREAD

**Issue by rseuchter** [corretto/corretto-8#228]
### Describe the bug
I've recently had difficulties uninstalling Corretto 8 through the CLI (using msiexec in PowerShell through an SSM session).
Basically, when using `msiexec` you can use `/x {UUID}` or `/x path-to-correttos.msi` Using the UUID that just won't work. I got the UUID following [advice from Microsoft's PowerShell docs](https://docs.microsoft.com/en-us/powershell/scripting/samples/working-with-software-installations?view=powershell-7#listing-all-uninstallable-applications):

    PS C:\Windows\system32> New-PSDrive -Name Uninstall -PSProvider Registry -Root HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
    PS C:\Windows\system32> dir Uninstall:

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

    Name                           Property
    ----                           --------
    {0D179FFA-5BD7-4775-83C2-7770E AuthorizedCDFPrefix :
    FF5D7EC}                       Comments            :
                                  Contact             :
                                  DisplayVersion      : 1.8.0.242
                                  HelpLink            :
                                  HelpTelephone       :
                                  InstallDate         : 20200406
                                  InstallLocation     :
                                  InstallSource       : C:\Windows\TEMP\Amazon\SSM\Download\
                                  ModifyPath          : MsiExec.exe /I{0D179FFA-5BD7-4775-83C2-7770EFF5D7EC}
                                  Publisher           : Amazon
                                  Readme              :
                                  Size                :
                                  EstimatedSize       : 321656
                                  UninstallString     : MsiExec.exe /I{0D179FFA-5BD7-4775-83C2-7770EFF5D7EC}
                                  URLInfoAbout        :
                                  URLUpdateInfo       :
                                  VersionMajor        : 1
                                  VersionMinor        : 8
                                  WindowsInstaller    : 1
                                  Version             : 17301504
                                  Language            : 1033
                                  DisplayName         : Amazon Corretto 8 (x64)

You see that `UninstallString     : MsiExec.exe /I{0D179FFA-5BD7-4775-83C2-7770EFF5D7EC}` looks odd (and even `ModifyPath` looks suspicious).

However, passing the MSI file rather than the UUID to msiexec does work.
Uninstall through the UI seems to work. Typically, I don't have the UI available, only SSM sessions.

### To Reproduce
1. Install [Corretto 8 on Windows from the .msi](https://corretto.aws/downloads/resources/8.242.08.1/signed.amazon-corretto-8.242.08.1-windows-x64.msi)
1. Try uninstall it through `msiexec /x {UUID}` e.g. `msiexec.exe /x {0D179FFA-5BD7-4775-83C2-7770EFF5D7EC} /QN /L*V "C:\msilog.log" /norestart` (adapted from advice at https://stackoverflow.com/a/1055933 number 3, option 5).

### Expected behavior
Uninstallation through msiexec should work without having to guess parameters.

### Platform information
    OS: Microsoft Windows Server 2016 Datacenter (10.0.14393 N/A Build 14393)
    Version OpenJDK Runtime Environment Corretto-8.242.08.1 (build 1.8.0_242-b08)

**Comment by yoroto** [comment]
Hi @rseuchter 

Thank you for reporting this! We will look into it and get back to you shortly.

**Comment by rseuchter** [comment]
Well, that's interesting. However, I've had difficulties uninstalling Corretto despite going from `/i` to `/x`. Would you mind sharing your complete uninstall string so I can give it a shot and confirm it as a workaround?
In most cases I ended up with a msiexec process that hang - probably showing something on the UI which I just don't have when running through SSM.

**Comment by ziyiluo** [comment]
@rseuchter Have you tried to run the command without the brackets in the GUID string? The following command works for me:
```
msiexec /x 86C0B400-6A93-4979-8E5E-46152223B361
```
