### ISSUE TITLE
Ubuntu 18.04.1 minor compile issues

### ISSUE THREAD

**Issue by dacut** [corretto/corretto-8#23]
### Describe the bug
Compiling Corretto on Ubuntu 18.04 fails with two compilation errors:
```
/home/dacut/projects/corretto-8/src/hotspot/src/share/vm/code/dependencies.cpp: In function ‘static void Dependencies::write_dependency_to(xmlStream*, Dependencies::DepType, GrowableArray<Dependencies::DepArgument>*, Klass*)’:
/home/dacut/projects/corretto-8/src/hotspot/src/share/vm/code/dependencies.cpp:498:6: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 9 [-Werror=format-overflow=]
 void Dependencies::write_dependency_to(xmlStream* xtty,
      ^~~~~~~~~~~~
/home/dacut/projects/corretto-8/src/hotspot/src/share/vm/code/dependencies.cpp:498:6: note: directive argument in the range [0, 2147483647]
```

```
/home/dacut/projects/corretto-8/src/hotspot/src/share/vm/runtime/fprofiler.cpp: In member function ‘void ThreadProfiler::vm_update(TickPosition)’:
/home/dacut/projects/corretto-8/src/hotspot/src/share/vm/runtime/fprofiler.cpp:638:56: error: argument 1 null where non-null expected [-Werror=nonnull]
   bool vm_match(const char* name) const { return strcmp(name, _name) == 0; }
                                                  ~~~~~~^~~~~~~~~~~~~
```

### To Reproduce
1. Install Ubuntu 18.04.1. (I'm using the Dell Developer-provided version for their XPS line)
2. Install required dependencies. In my case, most of these were already installed except libcups2-dev and libasound2-dev
3. `cd src; ./configure; make`

### Expected behavior
Compilation succeeds.

### Screenshots
N/A

### Platform information
    OS: 18.04.1 LTS (Bionic Beaver)
    Version: build 1.8.0-internal-dacut_2018_11_24_13_21-b00

### Additional context
A couple minor code changes appear to fix this issue and creates an apparently working Corretto build:
https://github.com/dacut/corretto-8/commit/68c43e760ff22dfd94ab6f2c05cea3d53190439a

I'm not submitting this as a pull request because I'm dubious whether this should be fixed in code vs. compilation flags or other annotations.

Output from ./configure, in case it's helpful:
```
A new configuration has been successfully created in
/home/dacut/projects/corretto-8/src/build/linux-x86_64-normal-server-release
using default settings.

Configuration summary:
* Debug level:    release
* JDK variant:    normal
* JVM variants:   server
* OpenJDK target: OS: linux, CPU architecture: x86, address length: 64

Tools summary:
* Boot JDK:       openjdk version "1.8.0_181" OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13) OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)  (at /usr/lib/jvm/java-8-openjdk-amd64)
* Toolchain:      gcc (GNU Compiler Collection)
* C Compiler:     Version 7.3.0 (at /usr/bin/gcc)
* C++ Compiler:   Version 7.3.0 (at /usr/bin/g++)

Build performance summary:
* Cores to use:   7
* Memory limit:   15757 MB
```

**Comment by davecurrie** [comment]
Thanks! We are working on the Ubuntu release and expect to identify the right fix in the process. In any case, these changes are to the core OpenJDK code and we request that they are contributed to that project. Take a look at http://openjdk.java.net/contribute/ for details on how to do that.
