### ISSUE TITLE
defective sunec.dll in amazon-corretto-8.252.09.1-windows-x64-jdk.zip

### ISSUE THREAD

**Issue by pznknmtb** [corretto/corretto-8#230]
download:
https://corretto.aws/downloads/resources/8.252.09.1/amazon-corretto-8.252.09.1-windows-x64-jdk.zip

defective file:
jre/bin/sunec.dll

is actually a text file containing an error message starting with 
"{"request_id":"4446295","error":"Signing request failed.."

please improve your build scripts (like: quit when signing fails) and TEST the resulting image (at least a little bit).

**Comment by alvdavi** [comment]
Thanks for reporting this, we will release an updated version soon

**Comment by alvdavi** [comment]
New release is out:
https://github.com/corretto/corretto-8/releases/tag/8.252.09.2

**Comment by pznknmtb** [comment]
tested OK with https://corretto.aws/downloads/resources/8.252.09.2/amazon-corretto-8.252.09.2-windows-x64-jdk.zip

thank you for the quick fix.
