### ISSUE TITLE
Release amazon-corretto-8.252.09.2-windows-x86.msi

### ISSUE THREAD

**Issue by J-U-B** [corretto/corretto-8#231]
Even if issue #230 only affects Windows **x64,** please could you build the **MSI** package also for **x86**?

Background: Our software deployment handles both versions at the same time. This requires that they have the same version number.

Thank you in advance.

**Comment by davecurrie** [comment]
@J-U-B We follow a pattern of only updating the affected binaries when there is a problem to reduce churn for users of the unaffected ones. Users who detect the latest version and plan updates to their production systems based on that may end up planning unnecessary deployments if we do what you ask.

If you use our permanent URLs (see https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html), each link will redirect you automatically to the latest version without needing to rely on version numbers. Have you considered using those?

Thanks.

**Comment by J-U-B** [comment]
Thank you for your answer.

I can certainly understand the argumentation for your update policy. This is of course plausible.

I used the permanent URLs for downloading before. The first problem for my project (https://github.com/J-U-B/OPSI-corretto) is, that the version numbers are needed.  
The second one: The resulting deployment package for the client management system (OPSI) contains both releases (32 an 64 bit) for the given version number. This won't work anymore if one of them isn't available, and unfortunately contradicts our versioning strategy. Splitting the packages into 32 and 64 bit releases instead of a single package, leads to a couple of side effects and follow-up problems.

Currently I have no idea how to handle diverging version numbers in one OPSI package.

What will be the maximum difference to be expected (at what decimal point)? Are we talking about (for example) 8.252.09.x or 8.252.x.y?

**Comment by davecurrie** [comment]
The permanent URLs are implemented as HTTP redirects to the filename including the version, which means that you can get the version number from the URL you end up downloading the file from. That may help you out.

Regarding the maximum difference, the variance will be 8.252.09.x. The first three numbers come from the OpenJDK release version and if it changes then we will likely be re-releasing all artifacts. The last number is the Corretto version and that is where we will fix Corretto-specific bugs such as packaging issues.

**Comment by J-U-B** [comment]
> The permanent URLs are implemented as HTTP redirects to the filename including the version, which means that you can get the version number from the URL you end up downloading the file from. That may help you out.

Unfortunately this doesn't really help, because the packages are built for a certain version number. The build script should always download exactly this version.

> Regarding the maximum difference, the variance will be 8.252.09.x.

Okay, I will try to deal with this.
For the moment I think about implementing a fallback function which tries a slightly older version if the exact match isn't available. This is a quite ugly solution, but currently I have no better idea.
