### ISSUE TITLE
The tar.gz distribution does not run on my Mac

### ISSUE THREAD

**Issue by rkrisztian** [corretto/corretto-8#232]
### Describe the bug
The tar.gz distribution seems not to run on my Mac.

### To Reproduce
> amazon-corretto-8.252.09.1-macosx-x64.tar.gz-unpacked/amazon-corretto-8.jdk/Contents/Home/bin/java -version
Killed: 9

### Expected behavior
I need a standalone distribution that does not require installing a package, but I can just extract an archive, and use the extracted binaries directly.

### Platform information
> uname -a
Darwin localhost 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### Additional context
On the same machine I also tried `amazon-corretto-11.0.5.10.1-macosx-x64.tar.gz`, which works without problems. But I need JDK 8.

**Comment by bernd-aws** [comment]
Thank you for alerting us to a defective binary on download arrival!

To reproduce the error, I just tried the same steps, from the [AWS download page](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-macos-jdk.tar.gz) and from the [github release page](https://corretto.aws/downloads/resources/8.252.09.1/amazon-corretto-8.252.09.1-macosx-x64.tar.gz). Both worked.

> uname -a
Darwin ... 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

Does your download checksum match? Can you try once more, please?

**Comment by ziyiluo** [comment]
Cannot reproduce on my mac:
```
$ curl -L https://corretto.aws/downloads/resources/8.252.09.1/amazon-corretto-8.252.09.1-macosx-x64.tar.gz | tar xzf - && ./amazon-corretto-8.jdk/Contents/Home/bin/java -version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  110M  100  110M    0     0  30.7M      0  0:00:03  0:00:03 --:--:-- 30.7M
openjdk version "1.8.0_252"
OpenJDK Runtime Environment Corretto-8.252.09.1 (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM Corretto-8.252.09.1 (build 25.252-b09, mixed mode)
```
System:
```
Darwin ... 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
```

**Comment by rkrisztian** [comment]
I tried the same download on another Mac, and couldn't reproduce either:

```none
> uname -a
Darwin localhost 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

Seems like this could be an issue with the original machine I was using...

**Comment by rkrisztian** [comment]
Suddenly my original download on the original machine started working too. Sorry about this, no clue how it happened.
