### ISSUE TITLE
java.nio.Bits.unaligned() return false for ARM architecture

### ISSUE THREAD

**Issue by davidshtian** [corretto/corretto-8#248]
### Describe the bug
During the usage, a issue was encountered caused by java.nio.Bits.unaligned(). This attribute only returns true for i386|x86|amd64|x86_64|ppc64|ppc64le architecture, but not for aarch64, the issue was also described in [java.nio.Bits.unaligned() doesn't handle aarch64](http://mail.openjdk.java.net/pipermail/aarch64-port-dev/2017-May/004518.html). While AdoptOpenJDK has fixed the issue (like jdk8u191-b12 and later versions) with patches, make it return true for aarch64.

### To Reproduce
As shown in the source code in Corretto 8.252.09.1:
https://github.com/corretto/corretto-8/blob/release-8.252.09.1/src/jdk/src/share/classes/java/nio/Bits.java

### Expected behavior
Return true for aarch64 in java.nio.Bits.unaligned()

### Screenshots
N/A

### Platform information
    OS: [Debian]
    Version: [8.252.09.1]

### Additional context
AdoptOpenJDK jdk8u191-b12 - https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u191-b12

**Comment by cliveverghese** [comment]
Hi,

Thank you for reporting this issue. We are working fixing this. 

Regards,
Clive Verghese

**Comment by davecurrie** [comment]
This is fixed in Corretto 8u262. See the [Releases page](https://github.com/corretto/corretto-8/releases) for downloads.
