### ISSUE TITLE
Backport JDK-8244818 [macos] Java2D Queue Flusher crash while moving application window to external monitor

### ISSUE THREAD

**Issue by chrisvire** [corretto/corretto-8#249]
### Describe the bug
JDK-8244818 describes a crash while moving the application windows to an external monitor. In macOS 10.15 (Catalina), there is a new protection put in place:

Application Specific Information:
-[NSOpenGLContext setView:] must be called from the main thread.

The Java2D Queue Flusher thread is calling this. The fix in Java15 was to remove the call to this method since it is not needed.

References:
https://bugs.openjdk.java.net/browse/JDK-8244818
http://mail.openjdk.java.net/pipermail/2d-dev/2020-June/010838.html

### Platform information
    OS: macOS
    Version 10.15.x

### Additional context
OpenJDK is not backporting to OpenJDK 8. They are porting it back to OpenJDK 11 (11.0.9, I think).

**Comment by cliveverghese** [comment]
Hi, 

Thank you for reaching out regarding this issue, 

We will be releasing this change along with 11.0.9 and we will investigate the back-port to 8.

**Comment by chrisvire** [comment]
@cliveverghese Thank you for the quick reply.

**Comment by chrisvire** [comment]
@cliveverghese FYI, I tried to build the product (see https://github.com/corretto/corretto-8/issues/119) and submit a PR for this issue. If I could successfully build the base product in a VM of Yosemite and Xcode 4 or 5, then I could help with PRs and any testing.

**Comment by chrisvire** [comment]
@cliveverghese, I received help on #119 and was able to build Amazon Corretto 8 with the change and it fixed my crash.  Should I make a pull request? If so, against which branch?

**Comment by cliveverghese** [comment]
Thank you for proposing the changes, We ask that the changes to openjdk code are proposed directly to OpenJDK project by following the steps at http://openjdk.java.net/contribute/ . You can propose the change be merged into  http://hg.openjdk.java.net/jdk8u.

**Comment by phohensee** [comment]
Upstream backport requested, approval pending. See "jdk8u-fix-request" and Fix Request comment on https://bugs.openjdk.java.net/browse/JDK-8244818.

**Comment by phohensee** [comment]
Upstream backport pushed to jdk8u-dev jdk repo for 8u272, backport JBS issue [JDK-8250214,](https://bugs.openjdk.java.net/browse/JDK-8250214) patch https://hg.openjdk.java.net/jdk8u/jdk8u-dev/jdk/rev/5414b80b28cb.
