### ISSUE TITLE
Update FAQ for JFR on JDK 1.8

### ISSUE THREAD

**Issue by wsargent** [corretto/corretto-8#253]
In https://aws.amazon.com/corretto/faqs/ it says:

> A: Corretto is designed as a drop-in replacement for all Java SE distributions unless you are using features (e.g., Java Flight Recorder) not available in OpenJDK. Once Corretto binaries are installed on a host and correctly invoked to run your Java applications (e.g., using the alternatives command on Linux), existing command-line options, tuning parameters, monitoring, and anything else in place will continue to work as before.

Since the backport of JFR in 8.262.10.1 with JDK-8223147, Java Flight Recorder is enabled and so this is no longer accurate :-)

 https://github.com/corretto/corretto-8/blob/release-8.262.10.1/CHANGELOG.md#corretto-version-8262101

**Comment by davecurrie** [comment]
@wsargent Good catch, thanks. :) We'll get that updated.

**Comment by ziyiluo** [comment]
Hi @wsargent the doc is updated.
