### ISSUE TITLE
getStringBounds returns wrong result

### ISSUE THREAD

**Issue by navyxliu** [corretto/corretto-8#258]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug
Some return values are 0.  they are unlikely correct. 

./amazon-corretto-8.265.01.1-linux-x64/bin/java FontTest
955 0 857 0 959 0 0 0 0 0 0 0 0 988 954 0 0 641 812 0 988 923 0 923 0 818 495

for more information, refer to the original post. 
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-August/012386.html

### To Reproduce
Steps and (source) code to reproduce the behavior.
```
import java.awt.*;
import java.awt.font.*;
import java.awt.geom.*;

class FontTest {
public static void main(String[] args) {
String test = "abcdefghijklmnopqrstuvwxyz ";
Font f = new Font("Arial", 0, 1560);
int[] widths = new int[test.length()];
for (int i = 0; i < widths.length; i++) {
    FontRenderContext context = new FontRenderContext(new AffineTransform(1, 0, 0, 1, 0, 0), true, true);
    double w = f.getStringBounds(test, i, i + 1, context).getWidth();
     widths[i] = (int) w;
}

for (int i = 0; i < widths.length; i++) {
    System.out.print(widths[i] + " ");
}

}
}
```
### Expected behavior
$java FontTest
955 990 857 990 959 549 990 988 433 433 903 433 1519 988 954 990 990 641 812 611 988 923 1275 923 923 818 495

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

**Comment by alvdavi** [comment]
This could be a duplicate of #256. Using large fonts, the metrics of the font are returned as 0, which causes bad the overlap of the characters in the other issue.

**Comment by alvdavi** [comment]
Answered in the original thread:
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-August/012425.html

**Comment by alvdavi** [comment]
[JDK-8233097](https://bugs.openjdk.java.net/browse/JDK-8233097) has been approved for openjdk8u272

**Comment by pefeimagic** [comment]
I've created the original entry https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-August/012386.html for openjdk. Can someone fix this also for corretto-8?

**Comment by ziyiluo** [comment]
@pefeimagic since the patch is already landed in OpenJDK8u272, the target release date is mid Oct.
