### ISSUE TITLE
Can we use Amazon Corretto to launch Oracle EBS Forms? 

### ISSUE THREAD

**Issue by pavank900** [corretto/corretto-8#263]
Hi Team,

Can we use Amazon corretto Open JDK to launch Oracle EBS forms? Please share your views.

**Comment by navyxliu** [comment]
I don't have first-hand use experience, but this blog says java8 certifies with EBS 12.1 and 12.2.
https://blogs.oracle.com/ebstech/jre-180_251-certified-with-ebs-releases-122-and-121

Please note that corretto-8 doesnot provide neither Java Web Start(JWS) nor Java plug-in.  If it's a critical component for your use case, then Corretto-8 can't support Oracle EBS Forms.
