### ISSUE TITLE
Spurious 8.272.10-1 release

### ISSUE THREAD

**Issue by tik-stbuehler** [corretto/corretto-8#269]
For internal usage I'm using reprepro to mirror the package https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.deb redirects to; right now this has:

```
$ curl -v https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.deb
HTTP/1.1 302 Moved Temporarily
...
Location: /downloads/resources/8.265.01.1/java-1.8.0-amazon-corretto-jdk_8.265.01-1_amd64.deb
...
```

But my cron job found `java-1.8.0-amazon-corretto-jdk_8.272.10-1_amd64.deb` twice now, and afterwards reprepro complains:
```
Skipping inclusion of 'java-1.8.0-amazon-corretto-jdk' '1:8.265.01-1' in 'corretto-jdk-8|main|amd64', as it has already '1:8.272.10-1'.
```
(That is how I discovered this.)

So what is up with this spurious release?

PS: Yes, I know about the official repo. I just like having a local archive of older releases :)

**Comment by ziyiluo** [comment]
@tik-stbuehler Thanks for reporting this. The reason you saws this inconsistency was that the cache of our latest link Cloudfront distribution, which is the CDN behind corretto.aws, was not invalidated after the latest link was ROLLBACKED to 8.265 yesterday after we communicated with the OpenJDK community and found the issue described [here](https://github.com/corretto/corretto-8/releases/tag/8.272.10.1). The rollback behavior does not trigger a cache invalidation automatically. As a result, users in different geolocation may see different redirection result. This should have been fixed almost at the same time you filed this issue :) The latest links are now pointing to 8.272.10.3.
