### ISSUE TITLE
C2 compile thread consuming CPU

### ISSUE THREAD

**Issue by ferozed** [corretto/corretto-8#272]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug

The C2 compiler thread start taking up 100% cpu.

### To Reproduce
Steps and (source) code to reproduce the behavior.

This is a long running service, so we dont know how this starts happening. Even after restart, it runs fine for a while and then gets into this state.

### Expected behavior

NA

### Screenshots

NA

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed mode)
```

OS:

`Linux orb-del-ksb-101 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux`

### Additional context

Here is the output of top -bHp

```
top - 18:07:50 up 47 days, 19:49,  2 users,  load average: 11.72, 13.22, 13.69
Threads: 977 total,   4 running, 973 sleeping,   0 stopped,   0 zombie
%Cpu(s): 20.3 us,  2.3 sy,  0.0 ni, 76.2 id,  0.0 wa,  0.0 hi,  1.2 si,  0.0 st
KiB Mem : 15961172 total,  4671708 free,  7458344 used,  3831120 buff/cache
KiB Swap: 16777212 total, 16777212 free,        0 used.  8089652 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
30963 jboss     20   0 18.990g 6.723g  18748 R 99.9 44.2   1086:57 java
30945 jboss     20   0 18.990g 6.723g  18748 S 11.1 44.2 129:42.65 java
30949 jboss     20   0 18.990g 6.723g  18748 S 11.1 44.2 129:42.38 java
31579 jboss     20   0 18.990g 6.723g  18748 S 11.1 44.2 230:01.74 java
```

Looking at native stack, thread 30963 is doing this:

```
Thread 23 (Thread 0x7f28eaa65700 (LWP 30963)):
#0  0x00007f29339f6aaa in find_hihghest_bit(unsigned int) () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#1  0x00007f293347727d in PhaseChaitin::cache_lrg_info() () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#2  0x00007f293347a513 in PhaseChaitin::Register_Allocate() () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#3  0x00007f2933511608 in Compile::Code_Gen() () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#4  0x00007f293351260b in Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool) () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#5  0x00007f293345c72a in C2Compiler::compile_method(ciEnv*, ciMethod*, int) () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#6  0x00007f293351d5f6 in CompileBroker::invoke_compiler_on_method(CompileTask*) () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#7  0x00007f293351f778 in CompileBroker::compiler_thread_loop() () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#8  0x00007f2933ac346b in JavaThread::thread_main_inner() () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#9  0x00007f2933ac37b6 in JavaThread::run() () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#10 0x00007f29339654d2 in java_start(Thread*) () from /opt/zillow/services/keystone-sink-standalone/jre-8.212.71-master.97caf12/jre/lib/amd64/server/libjvm.so
#11 0x00007f29347e44a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
```

**Comment by AzeemJiva** [comment]
Hi,
  This is a very old version of Corretto8, please upgrade to Corretto8u272 and retest your application.

**Comment by lutkerd** [comment]
Closing due to no response in over a week. Please reopen if you are still seeing this issue.
