### ISSUE TITLE
AmazonCorrette missing nss.cfg

### ISSUE THREAD

**Issue by mkarimi20** [corretto/corretto-8#275]
During migration process, I wanted to use AmazonCorrette 8 instead of OpenJDK but getting this error. This is multipart as i progressed. 

1st error:
nss.cfg missing. No such a file in /usr/lib/jvm/java-8-amazon-corretto/jre/lib/security/ to execute

2nd. 
I have attempted to add nss.cfg file from other places to this directory but still getting the following error. 
 "exception.rootClass":"sun.security.pkcs11.ConfigurationException",
 "exception.rootMessage":"Invalid value for handleStartupErrors: Token[ignoreMultipleInitialisation], line 5"

Env:  Docker container
platform: Rancher

**Comment by earthling-amzn** [comment]
It looks like nss.cfg is included in the IcedTea distribution, but OpenJDK and Corretto have never included it. I think the version of nss.cfg included in the IcedTea packaging is here: https://github.com/gnu-andrew/java-1.8.0-openjdk/blob/master/nss.cfg
