### ISSUE TITLE
Roadmap page for Corretto

### ISSUE THREAD

**Issue by kunalspathak** [corretto/corretto-8#28]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your idea concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you propose it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your proposal is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
There is no Wiki or Roadmap page for this project that would describe the short/long term goals of this project.

### Describe a solution you would like
Looking forward to see a roadmap page that will list out some of the identified work items or goals. This will help better collaboration with the community who want to contribute to this project. 

### Describe alternatives you have considered
I don't see an alternative to this as of now.

### Additional context
None.

**Comment by davecurrie** [comment]
Hi @kunalspathak. Thanks for the feedback. We are working on the best way to publish roadmap information and we will update this issue when we have more to share.
