### ISSUE TITLE
Corretto 8 RPM doesn't create /usr/lib/jvm/java symbolic link

### ISSUE THREAD

**Issue by instinet-lewis-boon** [corretto/corretto-8#282]
### Describe the bug
We're using Amazon Corretto on CentOS installed via yum. 11 and 15 both create symbolic link
in `/usr/lib/jvm/`:

Corretto 11:
```bash
$ ls -l /usr/lib/jvm
total 4
lrwxrwxrwx 1 root root   26 Dec  1 10:42 java -> /etc/alternatives/java_sdk
drwxr-xr-x 9 root root 4096 Dec  1 10:42 java-11-amazon-corretto
lrwxrwxrwx 1 root root   21 Dec  1 10:42 jre -> /etc/alternatives/jre

$ ls -l /etc/alternatives/ | grep java_sdk
lrwxrwxrwx 1 root root 36 Dec  1 10:42 java_sdk -> /usr/lib/jvm/java-11-amazon-corretto
```

Corretto 8:
```bash
# ls -l /usr/lib/jvm
total 4
drwxr-xr-x 7 root root 4096 Dec  1 10:42 java-1.8.0-amazon-corretto
lrwxrwxrwx 1 root root   21 Dec  1 10:42 jre -> /etc/alternatives/jre
```

We're hoping to document installation with a note that JAVA_HOME can be set to `/usr/lib/jvm/java`.
This works on Corretto 11 and 15.

### To Reproduce
Steps and (source) code to reproduce the behavior.

Pull down the latest Corretto 8 RPM. Install it via `rpm`.

`ls -l /usr/lib/jvm` will show that the `java` symlink does not exist.

### Expected behavior

I expect the `/usr/lib/jvm/java` symbolic link to exist and point (via /etc/alternatives/)
to the Corretto installation.

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

CentOS 7. 

```
# java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment Corretto-8.275.01.1 (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM Corretto-8.275.01.1 (build 25.275-b01, mixed mode)
```

## Other Comments

I believe this is where Corretto 11 is creating the symlink: https://github.com/corretto/corretto-11/blob/develop/installers/linux/universal/rpm/scripts/postin_javac.sh.template#L3

Many thanks.

**Comment by navyxliu** [comment]
Thank you for this report. We are looking into it.

**Comment by instinet-lewis-boon** [comment]
Thanks @navyxliu, appreciate you getting this fixed so quickly! 🙂
