### ISSUE TITLE
Ubuntu Distribution : PPA Repository

### ISSUE THREAD

**Issue by JSchoreels** [corretto/corretto-8#29]
Hello there,

I created few week ago the issue #16 to create a .deb package for debian-like system (debian, ubuntu, mint ...).
However, the creation of a ppa repository would allow the people on Ubuntu to have automatic update with apt.
As far as I know, the creation of a launchpad repository is required to have a ppa.

I'm using Ubuntu 18.04 / Kernel 4.15/4.17 on AMD64 architecture.

Thank you,

Jonathan

**Comment by davecurrie** [comment]
Assigned to myself for further review.

**Comment by ishworg** [comment]
@davecurrie bump

We are happy with either - a PPA or a separate Debian repo.

Instead of providing a single Debian package, a canonical way in Debian-like distro is to either provide a deb that install the `sources.list` and/or the pgp keys or provide a URL to the deb repo so we can install the GPG key and the repo details ourselves.

Thanks

**Comment by davecurrie** [comment]
@ishworg Thanks for the comment. We're considering what the best way forward is to ensure easy upgradeability and we value your feedback.

**Comment by ishworg** [comment]
> Thanks for the comment. We're considering what the best way forward is to ensure easy upgradeability and we value your feedback.

It's ok @davecurrie. Would you able to comment on when we can expect the repo to be up? either PPA or AWS hosted..

Thanks.

**Comment by davecurrie** [comment]
Updated milestone to auto-updates. We expect to start evaluating all the items in this milestone shortly.

**Comment by abdolence** [comment]
Thanks for the great work, Corretto team.
Though, we really need this to our development machines (updating JDK from PPA). 
Any status updates for this?

By the way, if anyone needs a fast workaround for Docker + Ubuntu + Corretto, here it is:

```
FROM ubuntu:18.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    curl locales tzdata ca-certificates java-common

# Amazon Corretto
RUN JAVA_SDK_URL="https://d3pxv6yz143wms.cloudfront.net/8.212.04.2/java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb" && \
    TEMP_DEB="$(mktemp)" && curl -o "$TEMP_DEB" ${JAVA_SDK_URL} && dpkg -i "$TEMP_DEB" && rm -f "$TEMP_DEB"

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-amazon-corretto

```

**Comment by niklasholm** [comment]
In the meantime both Azul and AdoptOpenJDK offer deb repositories for their OpenJDK builds.

**Comment by Voronenko** [comment]
any update?

**Comment by davecurrie** [comment]
This is on the roadmap and we hope to be able to share more news soon.

**Comment by cliveverghese** [comment]
@JSchoreels @Voronenko @abdolence @niklasholm @ishworg 

We are happy to inform you that the new channels for installation including Apt Repositories are now available for use. Please refer to the [launch blog post](https://aws.amazon.com/blogs/opensource/new-update-channels-for-amazon-corretto-releases/) for additional information.

**Comment by Voronenko** [comment]
@cliveverghese  Thanks a lot!   What about Choco support on windows ? :))))   
https://chocolatey.org/

Question is serious.

**Comment by Voronenko** [comment]
Naming is inconsistent.
You are referring java 8 as 1.8 and java 11 as 11.

Unnecessary logic in most of provisioning recipes to distinguish.

**Comment by davecurrie** [comment]
@Voronenko Versioning is consistent with what the Java executable reports. JDK 8 self-reports as 1.8, whereas JDK 11 reports as 11.0.[x]. This is also the naming convention followed by Linux distros, so we've conformed to being idiomatic here.

**Comment by Voronenko** [comment]
@davecurrie tried - agree.  Removed note as non appropriate

( Removed:  Naming is inconsistent.
You are referring java 8 as 1.8 and java 11 as 11. )
