### ISSUE TITLE
Unable to install corretto 8.282.08.1 on win32 system

### ISSUE THREAD

**Issue by AvadheshKaria** [corretto/corretto-8#292]
### Describe the bug
**Windows version** : Microsoft Windows [Version 6.0.6002]
**Windows platform**: 32 bit
**Corretto version**:- 8.282.08.1
java is not working, when amazon-corretto-8.282.08.1-windows-x86.msi is installed on machine with  `ami-91bbcefe`, ("Windows 2008 x86 Recovery Instance CitrixXen")
![image](https://user-images.githubusercontent.com/3993041/108957835-2a32a200-7698-11eb-8c53-39cd990c13ed.png)

### To Reproduce
Installed JDK using the msi  https://corretto.aws/downloads/resources/8.282.08.1/amazon-corretto-8.282.08.1-windows-x86.msi 
![image](https://user-images.githubusercontent.com/3993041/108957987-5b12d700-7698-11eb-90a4-eda9f2735282.png)
![image](https://user-images.githubusercontent.com/3993041/108958128-8990b200-7698-11eb-8963-0a665ec40e51.png)

### Expected behavior
Working java once the installation is done.

### Screenshots
Attached above

### Platform information
    OS: [e.g. Windows 32 bit]
    Version [e.g. "build amazon-corretto-8.282.08.1-windows-x86.msi" (output from "java -version")]

### Additional context
We are trying to use install4J to bundle corretto jre `8.282.08.1` for our application and we are facing this issue.
```
C:\Users\Administrator\Desktop\Build\amazon-corretto-8.282.08.1-windows-x86-jre> ..\install4j\install4j7.0.8\bin\createbundle.exe .\jre1.8.0_282 -v 1.8.0_282
java -version output is:
Error: loading: C:\Users\Administrator\Desktop\Build\amazon-corretto-8.282.08.1-windows-x86-jre\jre1.8.0_282\bin\server\jvm.dll
Packing JAR files. This can take several minutes.
  lib/charsets.jar
java.io.IOException: File .\jre1.8.0_282\lib\charsets.jar was not packed successfully.
Error: loading: C:\Users\Administrator\Desktop\Build\amazon-corretto-8.282.08.1-windows-x86-jre\jre1.8.0_282\bin\server\jvm.dll
        at com.install4j.b.a.b.e(ejt:262)
        at com.install4j.b.a.b.run(ejt:131)
        at com.install4j.CreateBundleApplication.g(ejt:59)
        at com.install4j.CreateBundleApplication.main(ejt:154)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
        at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
        at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
There was an error when writing the JRE bundle to C:\Users\Administrator\Desktop\Build\amazon-corretto-8.282.08.1-windows-x86-jre\windows-x86-1.8.0_282.tar.gz
The error message was: File .\jre1.8.0_282\lib\charsets.jar was not packed successfully.
Error: loading: C:\Users\Administrator\Desktop\Build\amazon-corretto-8.282.08.1-windows-x86-jre\jre1.8.0_282\bin\server\jvm.dll
```

We have been using corretto jre for sometime, and we have been able to bundle the jre from https://corretto.aws/downloads/resources/8.275.01.1/amazon-corretto-8.275.01.1-windows-x86-jre.zip

**Comment by navyxliu** [comment]
@AvadheshKaria 
Thank you for using Corretto-8.
 
The error message you saw is about [this win32 api](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocessmodules).  here is the requirement: 
> Kernel32.dll on Windows 7 and Windows Server 2008 R2; Psapi.dll (if PSAPI_VERSION=1) on Windows 7 and Windows Server 2008 R2; Psapi.dll on Windows Server 2008, Windows Vista, Windows Server 2003 and Windows XP

Corretto-8 only supports Windows 7 and later([link](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/windows-7-install.html)).  Your system is Windows Server 2008 SP.   Please note that Windows Server 2008 R2 is equal to Windows 7, which is the oldest system we support.  I would suggest you to upgrade your system to at least Windows Server 2008 R2,  or you need to build Corretto-8 on your own.

**Comment by davecurrie** [comment]
I also note that our supported versions section at https://aws.amazon.com/corretto/ is missing the "R2" portion. That is a bug in the docs that I will get fixed ASAP.

**Comment by AvadheshKaria** [comment]
Thanks for the confirmation, we will build on other 32-bit OS version.

**Comment by davecurrie** [comment]
Supported versions now corrected in https://aws.amazon.com/corretto/faqs/.
