### ISSUE TITLE
Backport request for JDK-7092821(java.security.Provider.getService() is synchronized and became scalability bottleneck)

### ISSUE THREAD

**Issue by motomizuki** [corretto/corretto-8#299]
I know https://github.com/corretto/corretto-8/pull/82 is created and closed but corretto-8's `java.security.Provider.getService()` is still synchronized. 
So I want to know is there any plan to backport [JDK-7092821](https://bugs.openjdk.java.net/browse/JDK-7092821)(java.security.Provider.getService() is synchronized and became scalability bottleneck) patch to corretto-8?

### Is your feature request related to a problem?
I have a contention issue with java.security.Provider.getService() when decrypting JWT access token and creating HTTPS connection to backend service.

### Describe a solution you would like
[Corretto-11](https://github.com/corretto/corretto-11/commit/4a9d3e11048967658a2c9355e6056bb5796c2f34) and  oracle java( 8u271 )  is fixed this problem but corretto-8 still have a synchronized.
I request to apply same patch to corretto-8.

**Comment by davecurrie** [comment]
Hi.

At this point, Corretto 8 (and OpenJDK 8) are not the places to get continued performance enhancements. They are being maintained for stability of apps still using them but the preferred version right now is Corretto 11. If you need to improve performance, we recommend upgrading to 11. There are many more performance improvements than just this, including improved GC performance too.

FWIW we proposed this upstream anyway in September last year and the OpenJDK maintainer response was the same (see https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-September/012722.html)

**Comment by motomizuki** [comment]
Thanks! I will try to use Corretto 11.
