### ISSUE TITLE
Korean Font "DotumChe" is broken when bold in Swing 

### ISSUE THREAD

**Issue by Nokinu** [corretto/corretto-8#309]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8 and is not specific to Corretto 8 we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system]() or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug
When attempting to display Korean Characters in Swing with font "DotumChe" with Bold style, there are 2 issues when comparing with Oracle JDK7 in Swing.
1) The drawing liner is wider than Oracle JDK 7.
2) Some characters are failed to be rendering bold (partially)，check the third char below

### To Reproduce
Here is the code to reproduce.

```
public class FontTestClass extends JFrame {

  public FontTestClass() {
    
    JLabel jl = new JLabel("전 미향 안주현");
    // DotumChe
    Font font = new Font("DotumChe", Font.BOLD, 120);
    jl.setFont(font);
    setTitle(System.getProperty("java.version") + " Font : " + font.getName() + " Style : " + font.isBold()); //$NON-NLS-1$
    this.setLayout(null);
    setSize(3100, 1100);// 400 width and 500 height
    jl.setBounds(130, 100, 3100, 1100);// x axis, y axis, width, height
    this.add(jl);
    this.setVisible(true); 
  }

  public static void main(String[] args) {
    new FontTestClass();
  }
}
```

### Expected behavior
See the screenshot below when running above code against Oracle JDK7
![image](https://user-images.githubusercontent.com/56990955/120410095-ae7e7a80-c395-11eb-9300-ff3b81b53127.png)

### Screenshots
See the screenshot below when running above code against OpenJDK8
![image](https://user-images.githubusercontent.com/56990955/120410153-c655fe80-c395-11eb-8796-b8c37e04d382.png)

### Platform information
    OS: Windows 10 + DotumChe installed
    Version: 
![image](https://user-images.githubusercontent.com/56990955/120410240-ef768f00-c395-11eb-9e1f-2752afbf32c5.png)

### Additional context
Make sure font "DotumChe" being installed before testing

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

**Comment by TianminShi** [comment]
Hi Nokinu, thank you for reporting issue for corretto. one question have you tried the swing app with any other openjdk8 distribution?

**Comment by Nokinu** [comment]
> Hi Nokinu, thank you for reporting issue for corretto. one question have you tried the swing app with any other openjdk8 distribution?

Yes, redhat's JDK 8 also has the same issue. See below please :
![image](https://user-images.githubusercontent.com/56990955/120570550-bb65a180-c45b-11eb-9621-8b4dbdf1e380.png)

**Comment by Stu1A** [comment]
Hey guys, any update on this issue?

**Comment by Stu1A** [comment]
Hi, is there any update on this issue?

**Comment by navyxliu** [comment]
IIRC, OracleJDK8 uses proprietary font render whileas OpenJDK8 relies on FreeType. 
What you reported is a specific problem in FreeType, I guess. You may try the newer version of java, which bundles with newer version of Freetype. or your bring up this issue to openjdk mailing list and seek help to troubleshoot this issue.
