### ISSUE TITLE
macOS Corretto installer without root access

### ISSUE THREAD

**Issue by wolruf** [corretto/corretto-8#31]
### Is your feature request related to a problem?
Some environments will require Corretto to be installed without necessarily having root access

### Describe a solution you would like
Document how to install Corretto without root access or implement a feature allowing not to require root access.

### Additional context
<img width="854" alt="screen shot 2018-12-13 at 13 18 19" src="https://user-images.githubusercontent.com/13536363/49938733-0d588c80-fedb-11e8-9d23-7f90584a3f91.png">

**Comment by ziyiluo** [comment]
Hi @wolruf, we will release Corretto 8 Mac build in both pkg installer and tgz formats in the next release so you are able to place Corretto in any customized location. Does that meet your expectation?

**Comment by wolruf** [comment]
Definitely, many thanks!

**Comment by alvdavi** [comment]
@wolruf There is now a Corretto8 preview2 MacOS tar.gz package available on the [downloads page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html).
