### ISSUE TITLE
Corretto images use OpenSSL 1.0

### ISSUE THREAD

**Issue by gurudath** [corretto/corretto-8#318]
It's a bummer that for Corretto, the native part is compiled against OpenSSL 1.0. That leaves quite a gaping hole in SSL support.

Can the native part be built against 1.1 instead?

An equivalent ticket is created on   docker-library/tomcat 
[https://github.com/docker-library/tomcat/issues/233](https://github.com/docker-library/tomcat/issues/233)

**Comment by veselov** [comment]
@gurudath That's not a problem with Corretto, or the Corretto image.

**Comment by gurudath** [comment]
Closing this issue
