### ISSUE TITLE
Windows x64 Preview 2 jarsigner.exe Code Signing Problem

### ISSUE THREAD

**Issue by prevoj** [corretto/corretto-8#32]
Corretto's Win64 Preview 2 jarsigner.exe reports a problem with the Comodo time server for signing a JAR with the TSA option. The warning does not occur with Oracle's JDK or Adopt's OpenJDK. I get the following warning when I try to code sign it:

Warning:
The TSA certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I use the following command to sign the jar:

"%CORRETTO_HOME%\bin\jarsigner.exe" -keystore MySigningStore.jks -storepass MyPassword -digestalg SHA-256 -sigalg SHA256withRSA -tsa http://timestamp.comodoca.com/ my.jar MyCertAlias

I'm trying to understand if Corretto just added a warning that the other JDKs should have been reporting too or if there might actually be a problem that will affect my code running later on. I have a bunch of jar files and they will be placed on quite a few production servers and I don't want my customers suddenly calling me if the code stops working at some point. I've worked in programming long enough to know you don't ignore warnings unless you research them and know it's OK to ignore them...

This is being run on Windows Server 2019 with JDK.:
OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview2-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)

Thanks,
Joe

**Comment by prevoj** [comment]
Thanks, I got it to work but not by using that CA certificate. I had to get the UTN-USERFirst-Object CA from https://www.tbs-certificates.co.uk/FAQ/en/97.html to get the warning to go away. I checked and both Oracle and AdoptOpenJDK have it but Corretto doesn't.

While it is now fixed for me, it would be nice if Corretto's cacerts file contained the same base set of certs as the other JDKs do (and extras added by Corretto would be fine as long as the "standard" set is there). Missing certs does not make Corretto a drop-in replacement. I alone had to burn a couple of days fixing this. Comodo is one of the most popular code signing vendors out there so no doubt, many others will run into this same problem too.

All that being said, I want to thank Amazon for providing us with Corretto as an option and for you, Letu, for helping me figure out the problem.

**Comment by davecurrie** [comment]
@prevoj I addressed the cacert issue in https://github.com/corretto/corretto-8/issues/59. Bottom line, we'll look into it but there isn't a definitive solution to cacerts not being in-sync unless they become something managed in the open. We are looking into how to keep the delta low in the future though.
