### ISSUE TITLE
Can't connect to AWS MySQL RDS using SSL (Java 8 Corretto)

### ISSUE THREAD

**Issue by itaisoudry** [corretto/corretto-8#320]
I upgraded my Lambda from Java 8 Linux 1 to Java 8 Linux 2.
I'm trying to connect to my MySQL DB, using JDBI with SSL, and I'm getting the following exception:

`com.mysql.cj.exceptions.SSLParamsException: Cannot open file:/etc/pki/java/cacerts [Keystore was tampered with, or password was incorrect]`

The parameters I'm using to connect:

> autoReconnect=true&verifyServerCertificate=true&useSSL=true&requireSSL=true

I'm using mysql-connector-java version 8.0.20 (tried 8.0.16 as well).
I read this [issue](https://github.com/corretto/corretto-8/issues/300), which seems similar, but I couldn't make it work since I'm not using the same parameters.

AWS support sent me here to open a ticket. :/

Any ideas?

**Comment by alvdavi** [comment]
Hi, thanks for contacting us with this.

The message "Keystore was tampered with, or password was incorrect" can also mean that the file we are trying to open does not exist.

There are two things that would help us identify this error. First one, would it be possible to get a complete stack trace of the issue?

Second, I see in the error it is trying to open `/etc/pki/java/cacerts`. Is this a path you are explicitly setting in your application? It is possible that the file is located in that path in the Java 8 Linux 1 version, but not in the Java 8 Linux 2 one.

**Comment by itaisoudry** [comment]
Hey,

I added the full stack trace from the AWS Lambda logs, you can view them here: https://pastebin.com/2nEt7Jgf
I'm not setting any path in the application, it always used the default one...

Since it is a lambda, and I can't ssh into it, is there a way to figure out where the file is located?
The only solution I got for now is to remove the parameter "verifyServerCertificate=true" from my connection string, and I'm not sure it is the best idea.

**Comment by pushkarchawda** [comment]
@itaisoudry, just for information, incase if you are trying to update Lambda from Java8 AL1 to Java8 AL2 due to [announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto](https://aws.amazon.com/blogs/compute/announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto/) 

This migration is all about switching underlying JDK implementation from OpenJDk 1.8 to Corretto 8 and the runtime will still be Java8 AL1, would suggest to keep runtime as `Java8 AL1` and use layer `arn:aws:lambda:::awslayer:Java8Corretto` for testing the compatibility.

**Comment by navyxliu** [comment]
hi, @itaisoudry 

The stacktrace you pasted indicates that password was incorrect. 
```
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
at java.security.KeyStore.load(KeyStore.java:1445)
at com.mysql.cj.protocol.ExportControlled.getSSLContext(ExportControlled.java:539)
... 36 common frames omitted
Caused by: java.security.UnrecoverableKeyException: Password verification failed
at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
... 41 common frames omitted
```

Like the prior blog mentioned, you can use docker image to check `/etc/pki/java/cacerts`

**Comment by smirnoal** [comment]
please try using `sslMode=REQUIRED` instead of [deprecated](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-security.html) `verifyServerCertificate=true&useSSL=true&requireSSL=true`

**Comment by itaisoudry** [comment]
Thanks @smirnoal, it worked! (sorry for the late reply :))

**Comment by Ianis-ro** [comment]
They've slightly changed the link @smirnoal referenced, so [here's the new one](https://dev.mysql.com/doc/connector-j/en/connector-j-connp-props-security.html)
