### ISSUE TITLE
After upgrade to Corretto 1.8.302.08.1, input fields in application are blacked out in MacOS Dark mode

### ISSUE THREAD

**Issue by amitabhakar** [corretto/corretto-8#323]
### Describe the bug
After upgrade to Corretto 1.8.302.08.1, input fields background color in application are blacked out in MacOS Dark mode. 

### To Reproduce
Launch the application

### Expected behavior
Input fields should have a white background irrespective of macOS Dark or Light mode. This was working fine in the previous release.

### Screenshots
Please refer to the screenshot attached.
<img width="1077" alt="Screen Shot 2021-08-09 at 8 29 31 AM" src="https://user-images.githubusercontent.com/53157014/128732394-bdca3192-4b21-492f-8442-84b6556ea712.png">

### Platform information
    OS: macOS 
    Version: Big Sur, Catalina

**Comment by navyxliu** [comment]
hi, @amitabhakar , 

Thank you for using Corretto-8!

We have investigated your issue.  We believe that [JDK-8231438](https://bugs.openjdk.java.net/browse/JDK-8231438) can solve it. We are backporting this patch to Corretto-8. Please note that JDK-8231438 doesn't bring dard-mode support to OpenJDK. It casts to light-mode for Java GUI controls so the your GUI will look same as in light-mode. 

Stay tuned.

**Comment by navyxliu** [comment]
Review in progress: http://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-August/014193.html

**Comment by amitabhakar** [comment]
Thank you.

How to apply the patch? Does it need to update our codebase?

Regards,
Amitabha

**Comment by navyxliu** [comment]
hi, @amitabhakar 

Sorry for the delayed respond.

We have backported the patch into jdk8u-dev.  https://bugs.openjdk.java.net/browse/JDK-8273726
We plan to release this bugfix along with jdk8u 8u322.  here is the timeline: https://wiki.openjdk.java.net/display/jdk8u/Main

We don't expect customer code will need to change accordingly.

**Comment by navyxliu** [comment]
jdk8u 322 has been release.
