### ISSUE TITLE
Text Resolution is fuzzy

### ISSUE THREAD

**Issue by amitabhakar** [corretto/corretto-8#326]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8 and is not specific to Corretto 8 we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system]() or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug
The text content seems like that of printer with blunt head.

### To Reproduce
Generate some content in viewer.

### Expected behavior
Normal Readable text

### Screenshots
Please refer to the screenshot attached

### Platform information
OS: Windows 10
OpenJDK: 1.4.0
Amazon Corretto: 1.8.302..08.1
<img width="723" alt="Screen Shot 2021-09-01 at 11 23 45 AM" src="https://user-images.githubusercontent.com/53157014/132054903-0b8b8640-4587-4032-bb70-67ff2c708aa2.png">

**Comment by alvdavi** [comment]
Hi, thanks for reaching out with this. 

Any chance you could provide us with more information? You talk about generating some content in viewer, but I don't know which exact application we are talking about. Also, is this a problem that started happening with 8.302.08.1 but was working fine with 8.292.x.x or earlier?
