### ISSUE TITLE
Version not being populated in dmg package for Munki

### ISSUE THREAD

**Issue by Conch1338** [corretto/corretto-8#328]
### Describe the bug
When using an MDM with Munki to distribute the Mac dmg package the version is always 1.0, rather than the version of the package eg 8.302.08.1

### To Reproduce
Upload any version of the DMG JDK package and once processed in Munki for distribution it will show as version 1.0 

### Expected behavior
The version number should be increased or match the version eg 8.302.08.1 See screenshots below

### Screenshots
![Screenshot 2021-09-09 at 15 07 49](https://user-images.githubusercontent.com/74651109/132701433-6e3df9b2-c200-4d05-ac7c-bc07b2949345.png)
![Screenshot 2021-09-09 at 15 08 01](https://user-images.githubusercontent.com/74651109/132701450-03553551-412d-469c-b858-02b1458a5920.png)
![Screenshot 2021-09-09 at 15 08 28](https://user-images.githubusercontent.com/74651109/132701475-4c5daa9a-c755-4a69-a163-1ab7ec1861f0.png)

### Platform information
    OS: Macos 11.4 / 11.5
    Version current and previous version have this issue.  Haven't tested any older ones. 

I believe you need to Add full version number to PKG metadata

**Comment by eastig** [comment]
Hi @andyiizuka,
Thank you for reporting the issue. We managed to reproduce it.
We are working on a fix.

**Comment by benty-amzn** [comment]
This should be resolved by #329

**Comment by Conch1338** [comment]
Excellent, thanks very much.
