### ISSUE TITLE
Are DIZ files needed?

### ISSUE THREAD

**Issue by prevoj** [corretto/corretto-8#33]
I noticed that Corretto includes DIZ files in the bin and bin/server folders. I opened one and its a zip file containing a MAP and PDB, which I know are for debugging. Is it safe and does Amazon allow us to delete the DIZ files for a deployed JRE. We have a particular app that is very space sensitive so saving an extra 13MB would be helpful. And yes, I know hard drives are cheap but some of us still have to work in severely constrained environments. Thanks!

**Comment by navyxliu** [comment]
hi, @prevoj, 
I double-check our rpms we distributed. They don't contain any diz files.  Windows distribution might contain diz.  We will get rid of them in next release. 

Yes, DIZs are debuginfo files in compression. They are only useful in native debugger like gdb when you need to debug JVM itself.  You can remove them in your production environment for sure.

**Comment by prevoj** [comment]
I deleted the DIZs and performed a full regression test on our app and everything worked great as expected! Thanks Xin Liu!

**Comment by prevoj** [comment]
Thanks, I see that 8u202 doesn't contain the DIZ files anymore!

**Comment by Deepthi-M** [comment]
We are looking currently into the jvm crash issue during the execution of some of our applications using windows dll functions and need now a jvm.pdb file for OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04) on windows 64 bit platform. Can you support us to get this file or recommend us how to proceed further.
Thanks!

**Comment by ziyiluo** [comment]
@Deepthi-M debug symbol files are uncommon in production build of OpenJDK. For your case, it makes more sense to use a [debug build](https://hg.openjdk.java.net/jdk8/jdk8/raw-file/tip/README-builds.html#configure) version of Corretto 8 (with less optimization and more symbols and assertions). We do not provide debug builds yet. But feel free to open a feature request if that's what you are looking for.
