### ISSUE TITLE
Font rendering corruption with -302

### ISSUE THREAD

**Issue by j-christ** [corretto/corretto-8#333]
### Describe the bug

When using javafx, all fonts in the scene are illegible.  This is a known issue:  https://bugs.openjdk.java.net/browse/JDK-8234916 with a backport to 8: https://bugs.openjdk.java.net/browse/JDK-8238627, but it's still not working with coretto version 8 -302

### To Reproduce

Compile and run the code from https://stackoverflow.com/questions/67893273/javafx-font-not-being-rendered-correctly
on MacOS Catalina 10.15.7+

### Expected behavior

You know, fonts would be readable...

### Screenshots

![image](https://user-images.githubusercontent.com/20236262/135871157-de79faff-b8c5-49cd-a71a-59198ed1ba9e.png)

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

### Additional context

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

**Comment by earthling-amzn** [comment]
Thank you for bringing this to our attention. We're working on this now.

**Comment by benty-amzn** [comment]
This should be fixed by #335
