### ISSUE TITLE
Windows installer crashes/closes on wrong javapath

### ISSUE THREAD

**Issue by xasz** [corretto/corretto-8#339]
### Windows Installer closes/crashes on wrong java path
Installer just shuts exits without any prompt

### To Reproduce
Install Amazon Corretto x64 JRE with the MSI Package on a Windows Server 2019 (I did not test other system, but i am sure its not the only one). 
Click through the setup as u like and at the point where u choose your java jre path select a folder which does not contain any java or the wrong one. Example choose `C:\Program Files\Amazon Corretto\jre8\bin` instead of `C:\Program Files\Amazon Corretto\jre8`
Press next and the setup shows a message:
> **Apache Tomcat Setup**
> No Java Virutal Machine found in folder:
> C:\Program Files\Amazon Corretto\jre8\bin
And it's gone :)

### Expected behavior
At least give me one try to correct my wrong input and not make me start all over again :)

### Platform information
    OS: [Windows Server]
    Version [2019 Up2Date]

### Additional context
Not really an issue.

**Comment by alvdavi** [comment]
Hi,

Is this an error you get when installing Corretto or a problem when installing Tomcat? Based on the message it seems to be a problem with the Tomcat installer when you select where your JVM is.

Thanks,

David

**Comment by xasz** [comment]
You are correct and i just submitted on the wrong repo. I am sorry - I'am a shame.
Edit: As Apache is making it very complicated (at least for me) this will slowly be forgotten :)
