### ISSUE TITLE
Corretto build requires xcode v4 on MacOS

### ISSUE THREAD

**Issue by rpural** [corretto/corretto-8#34]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your idea concerns OpenJDK 8
and is not specific to Corretto 8
we ask that you propose it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system]() or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your proposal is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
./configure checks for and fails for not having xcode v4, but the current version of xcode is v10. Why such an old version requirement?

### Describe a solution you would like
It would be useful to validate against a current xcode, instead of one that nobody would still have lying around on their system.

### Describe alternatives you have considered
Please provide a clear and concise description
of any alternative solutions or features you have considered.

**Comment by ziyiluo** [comment]
Hi Robert,

In short, Corretto-8 is derived from OpenJDK8. OpenJDK8 code base was stabalized in 2014 and the system requirement remains unchanged. Making Corretto-8 built on a modern Xcode with a newer MacOSX SDK is not impossible but is a non-trivial and risky project that we haven’t prioritized yet. Code changes are required and the system compatibility may be broken.

Building OpenJDK8 on Mac requires the legacy MacOSX SDK 10.8. The last Xcode that contains this SDK version is Xcode 5. Theoretically you should be able to build Corretto-8 with any Xcode version that contains MacOSX SDK 10.8. Linking Corretto-8 against a newer version of SDK may require modifying a bunch of deprecated/removed C flags, macros and apis therefore is not recommended.

For your reference, the official Corretto-8 release is built and tested on OS X Yosemite with Xcode 4.6.

Btw, You can expect a much easier time when we release Corretto-11 :)

Please let us know if you have any follow up questions.
