### ISSUE TITLE
it's not compile in mac m1

### ISSUE THREAD

**Issue by Y-StrongBless** [corretto/corretto-8#346]
In mac m1 to configure this, it will throw error with "The tested number of bits in the target (64) differs from the number of bits expected to be found in the target (32)" and "The tested number of bits in the target (0) differs from the number of bits expected to be found in the target (32)"

**Comment by lutkerd** [comment]
Hello, Corretto 8 is not yet supported on Mac M1, right now just Corretto 17 is supports on that architecture. Please track https://github.com/corretto/corretto-8/issues/297 for updates.
