### ISSUE TITLE
zipped  debug symbols  only contains  bin/*.diz

### ISSUE THREAD

**Issue by caozg2021** [corretto/corretto-8#356]
zipped  debug symbols  only contains  bin/*.diz

compile Corretto 
`./gradlew   :installers:linux:universal:tar:build`
  amazon-corretto-debugsymbols-8.322.06.3-linux-x64.tar.gz  only contains bin/*.diz

### Platform information
    OS: centos 6
    Version [  "build 1.8.0_322-b06]

**Comment by caojoshua** [comment]
Thank you for the issue. I can see there are `jre/bin/*.diz` and `jre/lib/*.diz` files missing. We are looking into this right now.
