### ISSUE TITLE
jfxswt.jar missing in Amazon corretto Linux aarch64

### ISSUE THREAD

**Issue by arvin4u123** [corretto/corretto-8#364]
Thank you for taking the time to help improve OpenJDK and Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here. (You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 8 and is not specific to Corretto 8 we ask that you raise it to the OpenJDK community. Depending on your contributor status for OpenJDK, please use the [JDK bug system]() or the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo) for the given problem area or update project [jdk8u-dev](http://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev).

If your issue is specific to Corretto 8,
then you are in the right place.
Please proceed with the following.

### Describe the bug
We are downloading Amazon corretto ([https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html ](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html)) for Linux aarch64 and find out that it is missing jfxswt.jar however it is available for LINUX x64. I confirmed that it is available for everything else like in MAC aarch64, MAC x64 etc.

### To Reproduce

1. Download Amazon corretto for Linux aarch64 from https://corretto.aws/downloads/latest/amazon-corretto-8-aarch64-linux-jdk.tar.gz
2. Untar the downloaded file and get inside the directory
3. Run `find . -type f -name jf*`
4. You dont find `jfxrt.jar` file however is available for everything else like in MAC aarch64, MAC x64 etc

### Expected behavior
Should see `jfxrt.jar` file

### Screenshots
```
bash-4.2# cd -
/opt/bdc/opt/amazon-corretto-8.322.06.2-linux-aarch64
bash-4.2# find . -type f -name jf*
./bin/jfr
./jre/lib/jfr.jar
```

### Platform information
    OS: Linux
    Version: OpenJDK Runtime Environment Corretto-8.322.06.2 (build 1.8.0_322-b06)

### Additional context

**Comment by caojoshua** [comment]
Hi @arvin4u123 . This is expected behavior. We never supported JavaFX on Arm.

Our recommendation is that if JavaFX is required on Arm systems, that you upgrade to Corretto 11 or Corretto 17. From there, you can use JavaFX through maven or gradle.  See https://openjfx.io/openjfx-docs/#introduction for more information.

I'm resolving, but feel free to reopen if there are further questions.

**Comment by arvin4u123** [comment]
Thank you @caojoshua for your reply BUT I see that it is available in MAC version of Arm

**Comment by caojoshua** [comment]
Sorry, what I should have said specifically, is that we don't support JavaFx on `Linux Arm`.

This is not a limitation within arm itself, it's just that there was originally never support for Linux arm JavaFX, and we never worked on it. We don't plan to add this to Corretto-8, and instead recommend users upgrade to a newer Corretto version.

**Comment by arvin4u123** [comment]
Thank you once again @caojoshua . To me it looks like a bug as it is there everywhere and missing in Linux Arm.

**Comment by caojoshua** [comment]
It is not a bug because it is expected behavior. A more appropriate label would be "unsupported feature".
