### ISSUE TITLE
Easy identification x86/x64 in Apps & Features of Windows

### ISSUE THREAD

**Issue by yamadamn** [corretto/corretto-8#37]
### Is your feature request related to a problem?
I have installed both Corretto x86/x64 in Windows.
If I try to uninstall the one (x86 or x64), I can't identify easily.
![apps features](https://user-images.githubusercontent.com/3313661/51071557-3ca71880-1696-11e9-9766-8012119dd1ca.png)

### Describe a solution you would like
It would be better if Corretto will be added x86/x64 identification like Oracle JDK/JRE like below image.
![apps features-java](https://user-images.githubusercontent.com/3313661/51071644-c7d4de00-1697-11e9-9e8b-3e94c7eccf9e.png)

### Describe alternatives you have considered

- I confirmed the folder's size in Windows Explorer.
- I use each Corretto x86 or x64 (not install both).
- I continue to use Oracle JDK/JRE.

### Additional context
This request is related to #22 .

**Comment by yoroto** [comment]
Hi @yamadamn

We have fixed this issue in the Preview 2_1 released yesterday. You can download it now. Let me know if you have any issue. Thanks!
