### ISSUE TITLE
JavaFX Missing From Latest Corretto JDK 8

### ISSUE THREAD

**Issue by guymac** [corretto/corretto-8#370]
I just installed Corretto 1.8u322 for MacOS (aarch64) and it is missing the jre/lib/ext/jfxrt.jar library and cannot compile JavaFX code.

**Comment by navyxliu** [comment]
hi, @guymac, 
Thank you for using Corretto product.  
I can confirm that [8.32206.4](https://github.com/corretto/corretto-8/releases/tag/8.322.06.4) doesn't contain jfxrt.jar and the relevant libraries.  I will work with our team on this issue and get you back soon.

**Comment by benty-amzn** [comment]
Hi, sorry for the delay in responding to this. At this time, JavaFX is not supported by Corretto 8 on macos m1. We do not currently plan to update it to support the new platform,  and we're working on better documentation about which platforms will and will not support JavaFX moving forward. If JavaFX is a requirement for you, we suggest migrating to Corretto 17 or 11 and using the latest [OpenJFX](https://openjfx.io/).
