### ISSUE TITLE
JAVA_HOME has trailing backslash  - amazon-corretto-preview2-8u192-windows-x64.msi

### ISSUE THREAD

**Issue by ckruegerkpmg** [corretto/corretto-8#39]
### Describe the bug

amazon-corretto-preview2-8u192-windows-x64.msi
set's a trailing backslash to JAVA_HOME
JAVA_HOME                      C:\Program Files\Amazon Corretto\jdk1.8.0_192\

### To Reproduce

Install preview2 with default setup

### Expected behavior
JAVA_HOME has no trailing backslash
JAVA_HOME                      C:\Program Files\Amazon Corretto\jdk1.8.0_192

### Platform information
    OS: Windows
    Version build 1.8.0_192-amazon-corretto-preview2-b12

**Comment by yoroto** [comment]
It has been fixed in the u202 release that we published today.
