### ISSUE TITLE
Alpine package missing "provides" variable

### ISSUE THREAD

**Issue by andreldm** [corretto/corretto-8#391]
### Describe the bug
When `amazon-corretto-8` is installed in Alpine Linux, it is not considered a JDK provider, meaning  when other packages (e.g. maven) are installed they will transitively need to install the latest openjdk.

### To Reproduce
```
wget -O /etc/apk/keys/amazoncorretto.rsa.pub https://apk.corretto.aws/amazoncorretto.rsa.pub
echo "https://apk.corretto.aws/" >> /etc/apk/repositories
apk add amazon-corretto-8==8.332.08.1-r0
# java -version tells Corretto is the default JVM
apk add maven
```

Now openjdk17 is installed when it shouldn't be necessary and is the default JVM.

### Expected behavior
When maven is installed no JDK needs to be installed and Corretto remains as the default JVM.

### Screenshots
N/A

### Platform information
    OS: Alpine Linux 3.15
    Version: Corretto-8.332.08.1 (build 1.8.0_332-b08)

### Additional context
This is packaging issue, I couldn't find the APKBUILD for Corretto anywhere, with it in hands, it is just a matter of adding `provides=java-jdk`. The current `.PKGINFO` file tells it is missing:

```
apk fetch amazon-corretto-8
tar -xf amazon-corretto-8-8.332.08.1-r0.apk .PKGINFO -O

# Generated by abuild 3.7.0-r0
# using fakeroot version 1.25.3
# Tue Apr 19 02:35:52 UTC 2022
pkgname = amazon-corretto-8
pkgver = 8.332.08.1-r0
pkgdesc = Corretto-8
url = https://github.com/corretto/corretto-8
builddate = 1650335752
packager = Unknown
size = 91803648
arch = x86_64
origin = amazon-corretto-8
commit = 
license = https://github.com/corretto/corretto-8/blob/develop/LICENSE
depend = amazon-corretto-8-jre
# automatically detected:
depend = so:libc.musl-x86_64.so.1
datahash = 61da7aba29e0cf0bee27171c568a047f660100fa3f4b48f7072fc3c3644a2452
```

**Comment by lutkerd** [comment]
Thanks for reporting this. We'll have it fixed for the Q3 release on July 19th.

**Comment by lutkerd** [comment]
This is now resolved with the release yesteryday.

```
$ docker run -it amazoncorretto:8u342-alpine3.15 /bin/sh
/ # apk add maven
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
fetch https://apk.corretto.aws/x86_64/APKINDEX.tar.gz
(1/1) Installing maven (3.8.3-r0)
Executing busybox-1.34.1-r7.trigger
OK: 203 MiB in 18 packages
```
