### ISSUE TITLE
Windows 11: Update OS detection code to recognize Windows 11

### ISSUE THREAD

**Issue by durgesh-provar** [corretto/corretto-8#396]
Backport changes from PR: https://github.com/openjdk/jdk/commit/97ea9dd2f24f9f1fb9b9345a4202a825ee28e014 to latest OpenJDK 8u.
 
Issue is with System.getProperty("os.name"); is returning "Windows 10" on windows 11 machine.
And it is a known bug, for that team provided a fix on some java versions.
Already fix provided on this issue id: https://bugs.openjdk.org/browse/JDK-8274840

**Comment by caojoshua** [comment]
I can confirm that this is not backported to Corretto8 / OpenJDK8. We will prioritize this internally. Thank you for reporting this.

**Comment by rgithubli** [comment]
Should be in https://github.com/corretto/corretto-8/pull/399. Feel free to reopen if not.

**Comment by durgesh-provar** [comment]
@rgithubli @caojoshua May I know when can we expect this in the release?
Any information regarding the upcoming 8U release?

**Comment by caojoshua** [comment]
The next 8u release is on July 19th 2022 and will include this fix.

**Comment by durgeshpatidar** [comment]
@caojoshua Thanks for the update.
Cc : @dikshasachdeva

**Comment by durgesh-provar** [comment]
@caojoshua Thanks for the update.
Cc : @dikshasachdeva
