### ISSUE TITLE
Windows installer should also register key `Java Runtime Environment\1.8`

### ISSUE THREAD

**Issue by ziyiluo** [corretto/corretto-8#40]
Forked from #14 , comment from @cakruege

1.8.0_192 is created but not 1.8. The following key is missing:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8]
"JavaHome"="C:\\Program Files\\Amazon Corretto\\jre8"
"MicroVersion"="0"
"RuntimeLib"="C:\\Program Files\\Amazon Corretto\\jre8\\bin\\server\\jvm.dll"
```

For example microsoft build agents didn't pickup the existance of corretto:
https://github.com/Microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1

**Comment by ckruegerkpmg** [comment]
Same for JDK. 1.8 without build number is missing

**Comment by yoroto** [comment]
The registry keys have been added to the u202 release which we published today.
