### ISSUE TITLE
Unable to run Talend Open Studio for Data Integration (Win 64)

### ISSUE THREAD

**Issue by DominiqueDeVillepinte** [corretto/corretto-8#41]
### The bug
When I try to run Talend Open Studio for Data Integration (Win 64) - TOS_DI-20180411_1414-V7.0.1, I get the message:
`Failed to load the JNI shared library "C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_192\bin\..\jre\bin\server\jvm.dll".`

### To Reproduce
Install Talend Open Studio for Data Integration and start it.

### Expected behavior
Work as with HotSpot.

### Screenshots
The message as displayed by Windows.
![image](https://user-images.githubusercontent.com/46605499/51201287-f3580280-18fb-11e9-8863-9a3c26cdeaad.png)

### Platform information
    OS: Windows 10-64 
    Version: 
             openjdk version "1.8.0_192"
             OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview2-b12)
             OpenJDK Server VM (build 25.192-b12, mixed mode)

### Additional context
C:\Users\2>dir "C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_192\bin\\..\jre\bin\server\jvm.dll"
 Volume in drive C is Windows
 Volume Serial Number is ACB8-XXXX

 Directory of C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_192\jre\bin\server

12/14/2018  10:40 PM         6,097,848 jvm.dll
               1 File(s)      6,097,848 bytes
               0 Dir(s)  111,763,304,448 bytes free

**Comment by bekwam** [comment]
I don't think this is a Corretto problem.  There might be a problem with the Talend executable processing spaces in the path.

This worked with 7.1.  

````
D:\TOS_DI-20181026_1147-V7.1.1>TOS_DI-win-x86_64.exe

D:\TOS_DI-20181026_1147-V7.1.1>set JAVA_HOME="C:\Program Files\Amazon Corretto\jdk1.8.0_192"

D:\TOS_DI-20181026_1147-V7.1.1>set PATH=%JAVA_HOME%\bin;%PATH%

D:\TOS_DI-20181026_1147-V7.1.1>TOS_DI-win-x86_64.exe

D:\TOS_DI-20181026_1147-V7.1.1>java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)
````

**Comment by DominiqueDeVillepinte** [comment]
After installing TOS_DI 7.1 and the modifications you suggested on the environment variables, I have the same issue.

I don't think the modifications you suggest are working, as I get:
PATH="C:\Program Files\Amazon Corretto\jdk1.8.0_192"\bin;C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_192\bin; ...

I have tried to replace the  jvm.dll with the one from Hotspot. TOS_DI  is not starting but without message. So the problem should come from Talend.

**Comment by bekwam** [comment]
Are you starting TOS from the command line as in my test case?

**Comment by DominiqueDeVillepinte** [comment]
Yes.

**Comment by bekwam** [comment]
Looking at my PATH, I don't have the second Corretto folder location.  This is the one without the quotes.  Can you echo the PATH, remove the entry w/o the double quotes, then set the PATH directly, meaning without the %PATH% variable?

**Comment by yoroto** [comment]
@DominiqueDeVillepinte Are you having both x64 and x86 Corretto installed?

**Comment by DominiqueDeVillepinte** [comment]
Hi @davecurrie 
It seems to work with the amazon-corretto-8.202.08.2-windows-x64.msi. I will try to double check on a clean virtual machine.

**Comment by DominiqueDeVillepinte** [comment]
Maybe the installation program should warn the user that installing a 32-bit on a 64-bit Windows / machine can cause an issue?

**Comment by davecurrie** [comment]
@DominiqueDeVillepinte Thanks, that's definitely an interesting suggestion. I'll add it as a potential improvement to the next version of the installer.

In the meantime, I'm closing this issue since it seems there isn't any work to do. Feel free to re-open if you feel differently.
