### ISSUE TITLE
Corretto doesn't output tls pre-master key in debug los

### ISSUE THREAD

**Issue by emaayan** [corretto/corretto-8#416]
### Describe the bug
when enabling the debug system property for ssl and key gen as described here 
https://timothybasanov.com/2016/05/26/java-pre-master-secret.html
the logs do not provide the same output as the oracle jdk 

### To Reproduce
use any code that access tls, and enable the -Djavax.net.debug=ssl,keygen system property 

### Expected behavior
output in the console displaying
CONNECTION KEYGEN:

Master Secret 

Session KeyGen: 

etc.. 

### Additional context
this output is to be used later for wireshark TLS decryption

**Comment by olivergillespie** [comment]
Hmm, I'm not sure if Corretto/OpenJDK intends to have that logging. As a workaround, consider trying something like this: https://github.com/neykov/extract-tls-secrets.

**Comment by olivergillespie** [comment]
We don't plan to add this information in the logs.
