### ISSUE TITLE
Provide Homebrew formulas for Corretto

### ISSUE THREAD

**Issue by MentalPower** [corretto/corretto-8#42]
<Snipped boilerplate>

### Is your feature request related to a problem?
One of the easiest ways to install Java on macOS is via Homebrew's [`brew cask install java`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb) which tracks the latest version (currently 11) or [`brew cask install java8`](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/java8.rb) which tracks the newest version of Java8 that's available. Can we get a version of these formulas that track Corretto instead?

### Describe a solution you would like
Provide versions of the above commands that install Amazon Corretto provided binaries instead of the Oracle ones.

### Describe alternatives you have considered
The download location in the [official documentation](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/macos-install.html) is not easy to automate and we'll have to hardcode to a specific version if we want to install Java via that mechanism. Our current approach of running `brew cask install java8` makes sure that we always install the newest version without having to update the scripts to track whatever that new version might be.

### Additional context
N/A

**Comment by diroussel** [comment]
Is this done, as I can find corretto in cask.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/corretto.rb

**Comment by davecurrie** [comment]
@diroussel Corretto is in cask and looks to be the correct package, added by a community member. I'd like to leave this issue open as an enhancement request until we confirm that we are keeping it updated as part of our release process.

**Comment by bamapookie** [comment]
Amazon currently supports two versions of Corretto: One for JDK8 (supported until 2023) and one for JDK11 (supported until at least 2024).  Can we get support for both versions?

**Comment by ziyiluo** [comment]
@bamapookie Absolutely! We have another [open issue in corretto-11 repo](https://github.com/corretto/corretto-11/issues/18) tracking the homebrew formulae for 11.

**Comment by bamapookie** [comment]
Haha, didn't realize this was the repo for Corretto itself instead of for Brew. :)

Anyway, it looks like the Corretto cask in homebrew (referenced above) was just updated to point to the JDK11 version.  That would leave this version unavailable again.

**Comment by trmaphi** [comment]
@bamapookie Corretto is packed as brew cask, you might want to look at [brew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions)

**Comment by rdp** [comment]
confirmed you can get corretto8 from brew-cask-versions: `$ brew tap homebrew/cask-versions && brew cask install corretto8`

**Comment by connorjs** [comment]
Are there any updates on this? It seems that we can install Corretto via Cask, but that only works on MacOS, not Linux.

Browsing [formulae.brew.sh](https://formulae.brew.sh/) shows `openjdk` and `openjdk@version` formulae for both [MacOS](https://formulae.brew.sh/formula/) and [Linux](https://formulae.brew.sh/formula-linux/). What is required to add Corretto to these for cross-platform installs?

**Comment by benty-amzn** [comment]
Homebrew for macos is available through homebrew. At this time we do not plan to support brew installation on linux platforms. The corretto homebrew formulae are community maintained, so users are free to provide this functionality if it is desired.
