### ISSUE TITLE
macOS aarch64 release hasn't the fix for JDK-8290832

### ISSUE THREAD

**Issue by raescartin** [corretto/corretto-8#423]
### Describe the bug
macOS aarch64 release hasn't the fix for 'JDK-8290832 It is no longer possible to change "user.dir" in the JDK8'

### To Reproduce
install [amazon-corretto-8.342.07.3-macosx-aarch64.pkg](https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-macosx-aarch64.pkg) on a Mac with a M1 processor, launch a project via Gradle: "user.dir" is not changed.
If using [amazon-corretto-8.342.07.3-macosx-x64.pkg](https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-macosx-x64.pkg) "user.dir" is changed.

### Expected behavior
It should be possible to change "user.dir" 

### Platform information
    OS: MacOSX Monterey 12.3
    Version amazon-corretto-8.342.07.3-macosx-aarch64

**Comment by alvdavi** [comment]
Hi,

Based on your link, you are comparing the 8.342.07.1 release for aarch64 with the 8.342.07.3 release for x64. In the changelog you can see how version 8.342.07.3 is the one that allows for `user.dir` to be changed:
https://github.com/corretto/corretto-8/blob/develop/CHANGELOG.md#corretto-version-8342073

Please, download [amazon-corretto-8.342.07.3-macosx-aarch64.pkg](https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-macosx-aarch64.pkg) or [amazon-corretto-8.342.07.3-macosx-aarch64.tar.gz](https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-macosx-aarch64.tar.gz)

**Comment by raescartin** [comment]
Hi,
I fixed the reported links to reflect the correct tested versions. It's still a bug.

**Comment by alvdavi** [comment]
Hi,

I've reviewed the binaries. In order to test the change, I've been using the following test:
```
public class UserDirChangeTest {
    public static void main(String[] args) throws Exception {
        String keyUserDir = "user.dir";
        String userDirNew = "/home/a/b/c";
        String fileName = "./a";

        String userDir = System.getProperty(keyUserDir);
        File file = new File(fileName);
        String canFilePath = file.getCanonicalPath();

        // now reset user.dir, this will cause crash on linux without bug 8194154 fixed.
        System.setProperty(keyUserDir,  userDirNew);
        String newCanFilePath = file.getCanonicalPath();
        System.out.format("%24s %48s%n", "Canonical Path = ", canFilePath);
        System.out.format("%24s %48s%n", "new Canonical Path = ", newCanFilePath);
    }
}
```

First, I tested in x64, and I tested versions 8.332.08.1, 8.342.07.1 and 8.342.07.3, these were the results:
```
-> uname -m
x86_64
-> ./amazon-corretto-8.jdk.8.332.08.1/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                 /System/Volumes/Data/home/a/b/c/a
-> ./amazon-corretto-8.jdk.8.342.07.1/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                /Users/alvdavi/corretto-runtimes/a
-> ./amazon-corretto-8.jdk.8.342.07.3/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                 /System/Volumes/Data/home/a/b/c/a
```
`8.342.07.1` behaves differently than `8.332.08.1`, but `8.342.07.3` restores back the original behavior.

Then, I tested in aarch64
```
-> uname -m
arm64
-> ./amazon-corretto-8.jdk.8.332.08.1/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                 /System/Volumes/Data/home/a/b/c/a
-> ./amazon-corretto-8.jdk.8.342.07.1/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                /Users/alvdavi/corretto-runtimes/a
-> ./amazon-corretto-8.jdk.8.342.07.3/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                 /System/Volumes/Data/home/a/b/c/a
```
We see the same as in x64, `8.342.07.1` being different than `8.332.08.1`, but `8.342.07.3` restoring the behavior. These tests were done with the tgz files, but I also installed the pkg in arm64 to test it behaves the same as the tgz:
```
-> java -version
openjdk version "1.8.0_342"
OpenJDK Runtime Environment Corretto-8.342.07.3 (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM Corretto-8.342.07.3 (build 25.342-b07, mixed mode)
-> java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =                 /System/Volumes/Data/home/a/b/c/a
```

This doesn't mean there are no differences between x64 and aarch64. JDK-8194154 was initially added to solve a crash that would happen in linux when the `user.dir` was set to a path that ended in `/`. If we try to set the path to `"/home/a/b/c/"`, now we can see how in x64 we just get an empty value:
```
-> ./amazon-corretto-8.jdk.8.342.07.3/Contents/Home/bin/java UserDirChangeTest
       Canonical Path =                /Users/alvdavi/corretto-runtimes/a
   new Canonical Path =
```
while attempting to run this code in aarch64 will have the same issue as linux and will cause the JVM to crash. A future update for the JVM will avoid the crash while maintaining the same behavior as `8u332`
