### ISSUE TITLE
Build Pipeline failed due to missing library

### ISSUE THREAD

**Issue by Denisjc** [corretto/corretto-8#434]
### Describe the bug
This morning my Azure pipelines failed with the error 

Version was specified as '8.342.07.3'. It is possible that version
 does not exist for 'corretto8jdk' at the source specified.

### To Reproduce
nothing just run the pipeline again and somehow it is back 

### Expected behavior
Library should be available online 

### Screenshots
![image](https://user-images.githubusercontent.com/31697943/204309228-144d851a-03a0-4038-a0ac-267aa4cb9265.png)

### Platform information
Windows Server - Build Agent Azure 

### Additional context
choco install corretto8jdk --version=8.342.07.3

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this.
This looks like an issue with Chocolatey, not Corretto itself. I've confirmed that it is still possible to download Corretto 8.342.07.3 from our releases at [msi](https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-windows-x64-jdk.msi) and [zip](https://corretto.aws/downloads/resources/8.342.07.3/amazon-corretto-8.342.07.3-windows-x64-jdk.zip). 

The Corretto Chocolatey packages are community maintained. You can try reaching out to the [package maintainer on Chocolatey](https://community.chocolatey.org/packages/corretto8jdk#versionhistory), [JohanJanssen](https://community.chocolatey.org/profiles/JohanJanssen) for the appropriate place to create an issue.
