### ISSUE TITLE
tzdata version update missing from changelog

### ISSUE THREAD

**Issue by g1patil** [corretto/corretto-8#454]
https://github.com/corretto/corretto-8/blob/fc355e4e30c1a6293d5c90d015433f9d7b289333/jdk/make/data/tzdata/VERSION#L24

Release : Corretto version: 8.362.10.1 
Changelog entries shows tzdata version : tzdata2022e
Commit has update to tzdata2022g https://github.com/corretto/corretto-8/commit/c961cb9f676cbb05e8fa28b7ca9d41b02fc83d3d

**Comment by lutkerd** [comment]
Hi, 
Typically we only call out differences from the upstream OpenJDK in our Changelog. In this case we updated from tzdata2022e before it was released in OpenJDK and so it was added to the Changelog. Updating to tzdata2022g came from and upstream change and was not added.
