### ISSUE TITLE
JavaFX webkit binaries not present in Linux and Windows Java Corretto packages

### ISSUE THREAD

**Issue by bakour** [corretto/corretto-8#46]
Some JavaFX features seems to not work in Amazon Corretto.
Not that the same code works in Java Corretto package for MacOS, but not in Corretto Windows/Linux packages

Here is an very simple code to test the issue:

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.web.WebEngine;
import javafx.stage.Stage;

public class HelloWorld extends Application
{
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start( Stage primaryStage) {
        primaryStage.setTitle("Hello World!");
        new WebEngine(); // Lazy load of JavaFX webkit module

        Label label = new Label();
        label.setText( "Hello World!" );

        StackPane root = new StackPane();
        root.getChildren().add(label);
        primaryStage.setScene(new Scene( root, 300, 250));
        primaryStage.show();
    }
}
```

In traces, you can see that javaFX webkit binaries are missing:

> Caused by: java.lang.UnsatisfiedLinkError: Can't load library: <java_path>/amazon-corretto-8.192.12.2-linux-x64/jre/lib/amd64/libjfxwebkit.so
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
> 	at java.lang.Runtime.load0(Runtime.java:809)
> 	at java.lang.System.load(System.java:1086)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
> 	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
> 	at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:131)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.webkit.WebPage.<clinit>(WebPage.java:130)
> 	at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
> 	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)

**Comment by bekwam** [comment]
See issue #26

**Comment by bakour** [comment]
Yes, this is the same issue. Let's close the current one.
