### ISSUE TITLE
JVM crash

### ISSUE THREAD

**Issue by lwahonen** [corretto/corretto-8#465]
### Describe the bug

Every now and then the JVM crashes with EXCEPTION_ACCESS_VIOLATION

### To Reproduce

Restart the software at least a few dozen times

### Expected behavior
No JVM crash

### Platform information
 Windows 11
[](url)
[hs_err_pid1076.log](https://github.com/corretto/corretto-8/files/11419626/hs_err_pid1076.log)

**Comment by lwahonen** [comment]
[hs_err_pid12236.log](https://github.com/corretto/corretto-8/files/11419802/hs_err_pid12236.log)

**Comment by olivergillespie** [comment]
Thanks for reporting. It will be difficult to pinpoint without a reproducer.

I found https://bugs.openjdk.org/browse/JDK-8236693 which is somewhat similar (crashing in HashMap.putVal), but in C2 compared to C1 in your issue.

I have no reason to think it will help, but without anything else much to try, you can try the latest version - https://github.com/corretto/corretto-8/releases/tag/8.372.07.1.

I also note that the app has IntelliJ's debugger agent enabled. Can you test without this agent?

**Comment by lwahonen** [comment]
It's been very hard to reproduce reliably, but this happens a couple of times a week - just often enough to be noticeable but not often enough to be easy to investigate.  I'll update the JDK and see if that helps

**Comment by rgithubli** [comment]
Don't see updates in the past month. Closing this issue. Feel free to reopen if the issue still occurs or we have better way to reproduce.
