### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by DimitarSirakov** [corretto/corretto-8#469]
SIGSEGV (0xb) at pc=0x00007f3736a79486, pid=25, tid=0x00007f37025f9700
JRE version: OpenJDK Runtime Environment (8.0_372-b07) (build 1.8.0_372-b07)
Java VM: OpenJDK 64-Bit Server VM (25.372-b07 mixed mode linux-amd64 compressed oops)
Problematic frame:
V [libjvm.so+0x789486] JvmtiExport::post_compiled_method_load(nmethod*)+0x236

**Comment by lutkerd** [comment]
Can you provide the full hs_err log files for this crash?

**Comment by simonis** [comment]
This looks like https://bugs.openjdk.org/browse/JDK-8305165 which will be fixed in 8u382 which is planned for  July 18th 2023.

**Comment by DimitarSirakov** [comment]
Seems like it. That's great! Thanks!

**Comment by DimitarSirakov** [comment]
> This looks like https://bugs.openjdk.org/browse/JDK-8305165 which will be fixed in 8u382 which is planned for  July 18th 2023.

That's great! Thanks !
