### ISSUE TITLE
jfxwebkit.dll cannot load

### ISSUE THREAD

**Issue by jianlinshi** [corretto/corretto-8#489]
Looks my app is looking for webkit support
![image](https://github.com/corretto/corretto-8/assets/100335561/56037b17-1c79-4ad7-b4e4-62613c3a5ab1)
Any fixes?

**Comment by yftsai** [comment]
Unfortunately, there is no plan for Corretto to support JavaFX Webkit. You might like to check other options such as [OpenJFX](https://wiki.openjdk.org/display/OpenJFX).
