### ISSUE TITLE
javafx_font.dll Error when executing JavaFX tests

### ISSUE THREAD

**Issue by DavidWich** [corretto/corretto-8#49]
### Describe the bug
When executing JavaFX controller tests with Maven (either specific or through the test lifecycle) I get the following error:

    A fatal error has been detected by the Java Runtime Environment:

    EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb116650a6, pid=2984, tid=0x00000000000008c0

    JRE version: OpenJDK Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
    Java VM: OpenJDK 64-Bit Server VM (25.202-b08 mixed mode windows-amd64 compressed oops)
    Problematic frame:
    C  [javafx_font.dll+0x50a6]

This happens when a javafx.stage.Stage tries to show() a javafx.scene.Scene .

This occurs in the Amazon Corretto 8 versions u192, u202, u202.08.2 (64 Bit)

This works in the Oracle versions.

### To Reproduce
Try to show() a javafx.scene.Scene with a javafx.stage.Stage

### Expected behavior
The tests should be executed correctly like Oracle JDK x64: build 1.8.0_192-b12, Oracle JDK x86: build 1.8.0_201-b09

### Platform information
    OS: Windows 10 Enterprise (x64)
    Version: build 1.8.0_192-amazon-corretto-preview-b12 (x64), build 1.8.0_202-b08 (x64) and the new 1.8.202.08.2 (x64)
    Maven: apache-maven-3.6.0

### Additional context
As I have noticed, this bug also occurs in Azul ZuluFX 1.8.0 u192 (build 1.8.0_192-b01). As this works with the Oracle JDK it may be a bug in both distributions (Corretto and ZuluFX). If this is not related to Corretto I apologize.

This error generates a hs_err_pid.log. If this is needed for further investigations I will post it.

**Comment by DavidWich** [comment]
I created a sample project to help you recreating the issue. In the process of creating it I noticed that this is related to the Maven Surefire Plugin, or rather the execution in headless mode. That's why the error appears through Maven (command line) and not through IDE-Test-Execution (which I noticed as well that this makes a difference).

The sample project is available here:
`https://gist.github.com/DavidWich/2f26d5b19481841a7ce8b3bc967f5f12`

**Comment by yoroto** [comment]
I've tried this project in IntelliJ Idea, and also didn't reproduce the error. If I understand correctly, this only happened when you run it using the Surefire plugin from command line?

**Comment by DavidWich** [comment]
Yes, it did. Currently I have to run these kind of tests through an IDE (Eclipse in this case) and skip them in the headless environment.

**Comment by rsabhi** [comment]
Hi, Is there a plan to get this fixed in Corretto 8? or any alternate plan get rid of this error? Thanks

**Comment by TianminShi** [comment]
this has been fixed in https://github.com/corretto/corretto-8/releases/tag/8.222.10.3
