### ISSUE TITLE
 Include IcedTea-Web in Corretto

### ISSUE THREAD

**Issue by don-vip** [corretto/corretto-8#5]
It would be great if the Corretto JRE also include [IcedTea-Web](https://icedtea.classpath.org/wiki/IcedTea-Web) natively, to ease the transition from Oracle JRE for Java WebStart applications.

IcedTea-Web is developed by RedHat and works on Linux, Windows and possibly also on macOS.

See the [same request](https://github.com/AdoptOpenJDK/openjdk-installer/issues/22) for AdoptOpenJDK.

**Comment by davecurrie** [comment]
Thank you for reaching out. I have labeled this issue as an enhancement pending further review.

**Comment by lootkips** [comment]
Any updates on the status of a browser plugin (IE11) or really any browser?

**Comment by StealthyDev** [comment]
Is it possible to download IcedTea-Web and use it with the current version of Corretto to run Applets?

**Comment by subhendugn** [comment]
We are also facing the same issue while launching the .jnlp file. Can any one please help me on how to use Iced-Tea for Corretto to run jnlp?

**Comment by prabh-62** [comment]
> We are also facing the same issue while launching the .jnlp file. Can any one please help me on how to use Iced-Tea for Corretto to run jnlp?

Steps:
- Download [IcedTea Binaries](http://icedtea.wildebeest.org/download/icedtea-web-binaries/1.7.1/windows/icedtea-web-1.7.1.win.bin.zip)
- Download [Corretto Binaries](https://d2znqt9b1bc64u.cloudfront.net/amazon-corretto-8.202.08.2-windows-x64-jre.zip)
- Extract both of these zip files

- Edit `$icedTeaDirectory\bin\javaws.bat` and replace `set INST_JAVA_HOME=` with `set INST_JAVA_HOME="$correttoDirectory`" to use Corretto Java runtime


- Launch JNLP file using Java WebStart: `$icedTeaDirectory\bin\javaws.bat  somefile.jnlp`

**Comment by subhendugn** [comment]
### Did the following:

`set INST_JAVA_HOME=C:\AmazonCorretto
set BAD_SLASH_SCRIPT_DIR=%~dp0
set SCRIPT_DIR=%BAD_SLASH_SCRIPT_DIR:\=/%
set ITW_HOME=%SCRIPT_DIR%../`



### Getting this error:

`C:\WINDOWS\system32>"C:\AmazonCorretto\jdk1.8.0_192/bin/java" "-splash:C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//share/icedtea-web/javaws_splash.png" "-Xbootclasspath/a:C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//share/icedtea-web/netx.jar;C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//share/icedtea-web/plugin.jar;C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//share/icedtea-web/jsobject.jar;C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//win-deps-runtime/js.jar;C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//win-deps-runtime/tagsoup.jar;C:\AmazonCorretto\jdk1.8.0_192/lib/ext/nashorn.jar" -Xms8m  "-classpath" "C:\AmazonCorretto\jdk1.8.0_192/lib/rt.jar;C:\AmazonCorretto\jdk1.8.0_192/lib/jfxrt.jar" "-Dicedtea-web.bin.name=javaws" "-Dicedtea-web.bin.location=C:/Users/sduser/Downloads/icedtea-web-1.7.1-image/bin/..//bin/javaws.bat" "net.sourceforge.jnlp.runtime.Boot" -Xnofork "C:\Users\sduser\Downloads\temp-unique-jnlp-1550638071672 (1).jnlp"
**Error: Could not find or load main class net.sourceforge.jnlp.runtime.Boot**`

**Comment by KingBrew** [comment]
> We are also facing the same issue while launching the .jnlp file. Can any one please help me on how to use Iced-Tea for Corretto to run jnlp?
> 
> Steps:
> 
> 
> Download IcedTea Binaries
> 
> 
> Download Corretto Binaries
> 
> 
> Extract both of these zip files
> 
> 
> Edit $icedTeaDirectory\bin\javaws.bat and replace set INST_JAVA_HOME= with set INST_JAVA_HOME="$correttoDirectory" to use Corretto Java runtime
> 
> 
> Launch JNLP file using Java WebStart: $icedTeaDirectory\bin\javaws.bat  somefile.jnlp

So I am a little new with some of this...   I would like to verify the folder path this needs to be extracted to.   Should this be placed in C:\Program Files\Amazon Corretto or any folder path?  

AND   -  this is the edited file I find in the extracted path shows this...     "\icedtea-web-1.7.1.win.bin\icedtea-web-1.7.1-image\bin" = guessing that would be correct? 

And is "$correttoDirectory" the C:\Program Files\Amazon Corretto ?

**Comment by shimshon70** [comment]
What is about to launch Java Applet in IE, for Oracle it occurs in ActiveX jp2launcer.exe. Does it supported by Amazon Corretto somehow?

**Comment by davecurrie** [comment]
@shimshon70 Applet support is not part of OpenJDK and as such, is not included in Corretto. If you can get the steps given by @prabh-62 in https://github.com/corretto/corretto-8/issues/5 to work, we'd be interested to know. BTW, that issue is where we're tracking this request, feel free to add more context there. Closing this issue.

**Comment by prabh-62** [comment]
IcedTea now comes bundled with OpenJDK installer 🚀: AdoptOpenJDK/openjdk-installer#22

**Comment by fishon-dev** [comment]
We cannot get an applet web page to display with Amazon Corretto 8 installed. I tested on Windows 10 Pro 64-bit using Firefox, Chrome, IE11, and Edge. Edge cannot even connect to the page while the others redirect to;
https://www.oracle.com/technetwork/java/index.html 
I installed IcedTea-Web 1.8 using the MSI installer but this didn’t help.

Also I couldn’t find javacpl.exe, the java control panel, anywhere in the Corretto installation. Is it not included in the OpenJDK?

**Comment by yamadamn** [comment]
@fishon-dev Java Plugin (Applet) is proprietary for Oracle JDK, and it's not included in OpenJDK.
Java Plugin is NPAPI based, and it's not supported except IE11, and Oracle JDK has ended support for Applet by Mar 2019.
https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by shimshon70** [comment]
It is clear that Oracle JDK supports Java Applets according to their policies.
The question does it possible to use IcedTea when running with Amazon Corretto.
I didn't succeed to do this

**Comment by smeggysmeg** [comment]
For my org, we utilize the IcedTea-Web standalone MSI installer for AdoptOpenJDK in conjunction with Amazon Corretto. Since the Corretto installer sets the Java environment variable, the two work together seamlessly.

https://github.com/AdoptOpenJDK/IcedTea-Web/releases

**Comment by hendrikebbers** [comment]
I'm a contributor to https://github.com/AdoptOpenJDK/IcedTea-Web and https://github.com/karakun/OpenWebStart. Instead of adding IcedTea-Web to Amazon Corretto I assume that it would be a better idea to try [OpenWebStart](https://openwebstart.com) with Coretto. By doing so you and your clients do not need to handle JDK updates on the client anymore since this will be done by OpenWebStart. If any feature for a seamless Coretto implementation is missing please open an issue at the Github repo or ping us directly :)

**Comment by krishnamanchikalapudi** [comment]
No resolution on 18+ months issue.

**Comment by davecurrie** [comment]
We're not likely to include IcedTea-Web in Corretto, so I'm closing this issue.

@hendrikebbers Thanks for the suggestion, we're looking at OpenWebStart and will get in touch if we have any questions.
