### ISSUE TITLE
Windows Defender Reports Virus for New JDK 8.202.08.2 MSI for x86

### ISSUE THREAD

**Issue by prevoj** [corretto/corretto-8#51]
Windows Defender keeps reporting a virus in the new JDK 8.202.08.2 MSI for x86, when I download it from your site. Here's the output that is repeatedly produced when I attempt to download amazon-corretto-8.202.08.2-windows-x86.msi:

>>> Trojan: Win32/Spursint.F!cl
>>> Alert level: Severe
>>> Status: Failed
>>> Date: 01/30/2019 13:47
>>> Category: Trojan
>>> Details: This program is dangerous and executes commands from an attacker.
>>>
>>> Affected items:
>>> containerfile: C:\Users\user1\Downloads\amazon-corretto-8.202.08.2-windows-x86.msi
>>> file: C:\Users\user1\Downloads\amazon-corretto-8.202.08.2-windows-x86.msi->Data1.cab->fil01E7047CF0BF93FEA9106E6DA209E042
>>> file: C:\Users\user1\Downloads\amazon-corretto-8.202.08.2-windows-x86.msi->Data1.cab->filFxPackager
>>> file: C:\Users\user1\Downloads\amazon-corretto-8.202.08.2-windows-x86.msi->Data1.cab->filPackager
>>> webfile: C:\Users\user1\Downloads\amazon-corretto-8.202.08.2-windows-x86.msi|https://d2znqt9b1bc64u.cloudfront.net/amazon-corretto-8.202.08.2-windows-x86.msi|pid:12760,ProcessStart:131933408237544035

I debated on whether to post this here or just email it to aws-security. In the end, I decided to post it here too so other end users would be aware of the potential issue. I know there is always the chance that it is just a false positive. If it's not a false positive, I would want to be aware if others knew of the issue and if it were being worked on.

To reproduce it, I simply download amazon-corretto-8.202.08.2-windows-x86.msi from https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html on a Windows system that has Defender enabled.

This can be repeated on a Windows Server 2019 system and a Windows 10 system. I have verified that both systems have the latest virus signatures.

Thanks,
Joe Prevo

**Comment by prevoj** [comment]
I have heard back from AWS security and it sounds like this is most likely a false positive and they are working with Microsoft to resolve the issue. I'll keep you posted when I hear more.

**Comment by davecurrie** [comment]
@prevoj It does look like a false positive and we are working to make sure it stops happening. Stay tuned to this issue.

>

**Comment by prevoj** [comment]
I got the latest Windows Defender updates and was able to download the 32-bit JDK without any issues now. Thanks for the help on clearing this up!

**Comment by davecurrie** [comment]
@prevoj Thanks for letting us know!
