### ISSUE TITLE
[Question] How to build release JDK

### ISSUE THREAD

**Issue by RaymondLam1** [corretto/corretto-8#516]
### Background
I use dragonwell8 latest version [8.432.06.1]([amazon-corretto-8.432.06.1-linux-x64.tar.gz](https://corretto.aws/downloads/resources/8.432.06.1/amazon-corretto-8.432.06.1-linux-x64.tar.gz)) (linux x64). It's OK. However, I try to build myself amazon-corretto-8.432.06.1-linux-x64.tar.gz by Github Actions, and I get j2sdk-image. I tried running the same code, I got error:

```
Error: dl failure on line 894
Error: failed /tmp/j2sdk-image/jre/lib/amd64/server/libjvm.so, because /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/j2sdk-image/jre/lib/amd64/server/libjvm.so)
```

### Describe a solution you would like
How do you build your release version with github action? In particular, how to handle glibc compatibility？

Looking forward to your reply~

**Comment by benty-amzn** [comment]
You can check how corretto-8 is built through Actions for pre-submit testing on linux x64 [here](https://github.com/corretto/corretto-8/blob/develop/.github/workflows/submit.yml#L164-L183). 

Can you provide more information about what steps led to the error above? It seems like your build image in Actions may be using a newer glibc than the target system where you received the failure. This can be resolved in a number of ways - building on a system with an older glibc, cross-compiling against your chosen version of glibc, updating the target system to a newer glibc, for example,

**Comment by RaymondLam1** [comment]
> Can you provide more information about what steps led to the error above? It seems like your build image in Actions may be using a newer glibc than the target system where you received the failure. This can be resolved in a number of ways - building on a system with an older glibc, cross-compiling against your chosen version of glibc, updating the target system to a newer glibc, for example,

Thanks for your reply. Fortunately, I successfully built it on centos 7 system.
