### ISSUE TITLE
Java enhanced runtime class reloading

### ISSUE THREAD

**Issue by iamdvr** [corretto/corretto-8#56]
### Is your feature request related to a problem?
No.

### Describe a solution you would like
Currently Java has capability to reload class methods through agent argument. Enhancing this functionality to littler further and make the classes reload by keeping some guidelines on how the copy of members data onto new class instance would be helpful.
How it is helpful.
 Currently, whenever a small change in code happen we need to shutdown and restart JVM to see the change reflected. Even though JVM is super fast to boot(with in a sec), but lot of application boot logic takes 1 to 60 seconds. So the code change need to wait long cycles to see the effect.
 Initial JVM boot time(1 second) part of it is being handled in #JavaEE but real time consumed is not by JVM cold start but by application to load lot of resources at beginning.
 By giving this option of enhanced runtime class loading, develoeprs would be 10x productive and number of test cases they run would also be doubled, which improves quality.

### Describe alternatives you have considered
 https://zeroturnaround.com/software/jrebel/ doing this hard part with lot of price.

### Additional context
 This issue was there in OpenJDK bug database as well and there is some discussion went but some how no one moved further.
 https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4910812
 http://mail.openjdk.java.net/pipermail/hotspot-dev/2011-July/004321.html
 http://mail.openjdk.java.net/pipermail/hotspot-dev/attachments/20110727/6e1fab2f/attachment.txt

**Comment by jguo11** [comment]
@iamdvr thanks for the suggestion. This looks like a suggestion for the OpenJDK project and the best way to get it addressed is to talk with the wider OpenJDK community. We suggest starting by opening an issue on http://bugs.openjdk.java.net. You can also raise the topic on the appropriate mailing list (see https://mail.openjdk.java.net/mailman/listinfo for the full list).

**Comment by iamdvr** [comment]
Thanks for response. This feature request has already there in mentioned bug database and mail chains since many years. 
By raising it here, thought would get some attention from active community and could lead to some momentum.
I am closing this ticket as this is not inline to current project scope.
