### ISSUE TITLE
javax.imageio.IIOException: Invalid argument to native writeImage

### ISSUE THREAD

**Issue by natarajbe** [corretto/corretto-8#57]
Exception is thrown when we select an image to copy to clipboard.

```
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;

import javax.swing.ImageIcon;

public class ImageSelection {
  public static void main(String[] argv) throws Exception {

	  ImageSelection1 imgSel = new ImageSelection1(new ImageIcon("C:/Users/na603925/AppData/Roaming/HarmonyScreenCapture/HSC_20190115_121315.png").getImage());
    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(imgSel, null);

    Transferable t = Toolkit.getDefaultToolkit().getSystemClipboard()
        .getContents(null);

    if (t != null && t.isDataFlavorSupported(DataFlavor.imageFlavor)) {
      Image img = (Image) t.getTransferData(DataFlavor.imageFlavor);
    }
  }
}

class ImageSelection1 implements Transferable {
  private Image image;

  public ImageSelection1(Image image) {
    this.image = image;
  }

  public DataFlavor[] getTransferDataFlavors() {
    return new DataFlavor[] { DataFlavor.imageFlavor };
  }

  public boolean isDataFlavorSupported(DataFlavor flavor) {
    return DataFlavor.imageFlavor.equals(flavor);
  }

  public Object getTransferData(DataFlavor flavor)
      throws UnsupportedFlavorException, IOException {
    if (!DataFlavor.imageFlavor.equals(flavor)) {
      throw new UnsupportedFlavorException(flavor);
    }
    return image;
  }
}
```

### Expected behavior
should be able to copy image to clipboard

### Platform information
    OS: Windows 10
    openjdk version "1.8.0_192"
    OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview2-b12)
    OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)

**Comment by natarajbe** [comment]
![exception](https://user-images.githubusercontent.com/43362458/52324897-106a8780-2a09-11e9-9317-a20e22752204.JPG)

**Comment by natarajbe** [comment]
attaching the exception for reference

**Comment by natarajbe** [comment]
closed by mistake

**Comment by davecurrie** [comment]
@natarajbe Thanks for getting in touch.

Can you please give us some more information on platform you are using (e.g. OS version, 32/64 bits)? Does this happen for all images or just one in particular? Does this same problem happen on other OpenJDK distributions?

**Comment by sameer1sharma** [comment]
Yes, it is happened for all images.
Yes, it is also persist in OpenJDK 11. I have checked with the version.
Even with amazon-corretto-8.202.08.2-windows-x64-jdk\jdk1.8.0_202, the issue persist.



![image](https://user-images.githubusercontent.com/7577553/52560278-d391fc80-2e1d-11e9-9975-7b9fdc490abe.png)

**Comment by davecurrie** [comment]
@sameer1sharma If the same thing also happens on OpenJDK distributions other than Corretto, I would recommend opening a bug with the OpenJDK project at https://bugs.openjdk.java.net/

That is the correct forum for OpenJDK issues that aren't Corretto-specific.
