### ISSUE TITLE
Providing Server JRE (tar) for Corretto 8

### ISSUE THREAD

**Issue by vijayyadav06** [corretto/corretto-8#58]
Wondering if there will be a is Server JRE version available for Corretto 8 in future? 

Oracle java 8 had specific server jre version. https://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html

What value that brings? As per Oracle's [blog](https://blogs.oracle.com/java-platform-group/understanding-the-server-jre) JDK includes additional functionality that system administrators may not need on their production systems like the Java Plugin for web browsers, auto update agents, and development tools like javadoc.

**Comment by davecurrie** [comment]
Hi @vijayyadav06. Can I ask what platform you're thinking about? Our Windows JRE packages don't include the additional functionality you mention and we are tracking the need for a Linux JRE in https://github.com/corretto/corretto-8/issues/45. Is there anything you're looking for that isn't covered in that issue?

**Comment by vijayyadav06** [comment]
Thanks for quick response, yeah tar for 64 bit linux. 
I looked at #45 although was not sure if it differentiates between [JRE](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) and [Server JRE](https://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html) distributions. The differnece been that "Server JRE" contains the monitoring tools (and optimized for production) which JRE is not.

One thing to note that Oracle only did that for version 8, Java 11 is distributed only as JDK.

**Comment by davecurrie** [comment]
@vijayyadav06 Our Linux JRE is a Server JRE in the sense that it doesn't explicitly include dependencies to thing like fonts. You can see some more about this in https://github.com/corretto/corretto-8/issues/64, for example.
