### ISSUE TITLE
Add support for Linux 32 and 64 bit arm

### ISSUE THREAD

**Issue by robnielsen** [corretto/corretto-8#60]
### Is your feature request related to a problem?
Yes, Oracle Java and Open JDK works with Linux on 32 and 64 bit processors

### Describe a solution you would like
Support both arm 32 and arm 64 bit Linux.

### Describe alternatives you have considered
Use a different distribution.

**Comment by davecurrie** [comment]
@robnielsen Thanks for getting in touch. We have a 64-bit arm version available experimentally on Amazon Linux 2 which you can try out by starting an [A1 instance](https://aws.amazon.com/ec2/instance-types/a1/) in EC2 and installing Corretto using the [Amazon Linux 2 install instructions](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/amazon-linux-install.html).

We don't have plans for supporting 32-bit ARM right now but I'm happy to hear your use-case if you'd like to share.

**Comment by robnielsen** [comment]
Oracle currently provides 32 bit arm for devices such as rasberry pi's.

**Comment by davecurrie** [comment]
@robnielsen Have you been able to look at the 64-bit ARM implementation at all?

**Comment by robnielsen** [comment]
@davecurrie, Sorry, I only have 32 bit device.

**Comment by davecurrie** [comment]
Circling back on some older issues. We have released ARM 64-bit for Linux as GA a couple of months ago. 32-bit ARM is a request we are aware of already, so closing this issue.
