### ISSUE TITLE
Add Corretto as a platform in AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by StealthyDev** [corretto/corretto-8#61]
Thank you for providing a no-cost long-term support for OpenJDK.

Feature Request:
Add Corretto as a platform in Elastic Beanstalk.

Elastic Beanstalk platforms:
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html

**Comment by davecurrie** [comment]
@StealthyDev Thanks for the request. We'll keep this issue updated with any changes in the current situation.

**Comment by Gaudon** [comment]
Has there been any updates with respect to this?

**Comment by yishaigalatzer** [comment]
Looking into it with the Elastic Beanstalk team

**Comment by lkamal** [comment]
I am looking for Corretto 11 under Elastic Beanstalk, but seems it is yet to come.

**Comment by pprahlad** [comment]
The Elastic Beanstalk team is actively considering your request and we will update this thread when ready. Thank you for this feedback.

**Comment by labisso** [comment]
A public beta version of Elastic Beanstalk Corretto 8 and 11 platforms is now available: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-elastic-beanstalk-launches-public-beta-corretto-al2-platforms/

**Comment by ziyiluo** [comment]
@StealthyDev Please take a look at the announcement labisso@ linked. I'm closing this issue but feel free to reopen it if you have any further questions.
