### ISSUE TITLE
Amazon Corretto 8 SKU (Stock keeping unit)?

### ISSUE THREAD

**Issue by DominiqueDeVillepinte** [corretto/corretto-8#62]
Question;
Does Amazon Corretto has a Stock keeping unit (SKU)?

Context:
Our Software Asset Management tool request that each product has a Manufacturer article No (SKU).

**Comment by davecurrie** [comment]
Hi @DominiqueDeVillepinte. We have not assigned an SKU to Corretto. Are you blocked by this?

**Comment by DominiqueDeVillepinte** [comment]
It was just to check. I will generate an internal code.

**Comment by davecurrie** [comment]
Sounds good, closing the issue then.
