### ISSUE TITLE
Debian jinfo file

### ISSUE THREAD

**Issue by steven-aerts** [corretto/corretto-8#63]
Unlike most other java distributions for debian, corretto does not provide a .jinfo file.
This file is used by `update-java-alternatives` to switch all java related symlinks to another distribution.

It also means that `update-java-alternatives --list` does not show corretto.

The jinfo files are installed in `/usr/lib/jvm/.${package-name}.jinfo`.
I do not think the format is somewhere specifically documented.  I think the [source](https://salsa.debian.org/java-team/java-common/blob/master/scripts/update-java-alternatives) of the update-java-alternatives script is the best reference together with other [packaging scripts](https://git.launchpad.net/~openjdk/ubuntu/+source/openjdk/+git/openjdk/tree/debian/rules?h=openjdk-11#n1488).

It would be nice if we could just type `update-java-alternatives -s java-1.8.0-amazon-corretto` to switch to corretto.

**Comment by davecurrie** [comment]
@steven-aerts Thanks for raising this issue. We'll investigate further and see if we can include this in our next release.

**Comment by jguo11** [comment]
Fixed in release 8.212.04.1.
