### ISSUE TITLE
JavaxFX app is missing MSVCR100.dll on a fresh Windows install

### ISSUE THREAD

**Issue by robnielsen** [corretto/corretto-8#69]
The JavaFX packager is not including MSVCR100.dll for apps installed with the installers it creates. This issue doesn't exist with installers created with Oracle Java. This can be reproduced by installing a test VM from Microsoft at https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.  For my testing, I used MSEdge on WIn10. After installation, I installed a JavaFX app and tried to run it. When it ran I got the error:

`app.exe - System Error : The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem.`

In order to run my app on a clean install of Windows, I installed Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update (https://www.microsoft.com/en-us/download/details.aspx?id=26999).

I encountered this with the x86 version, but the same issue might possibly exist on x64 as well.

**Comment by yoroto** [comment]
Hi @robnielsen 

Thank you for reporting it! I will look into it. BTW, which Corretto version(s) you've seen this problem?

**Comment by robnielsen** [comment]
The latest released one 1.8.0_202

**Comment by Maxoudela** [comment]
You can see my comment on this here : https://github.com/corretto/corretto-8/issues/47#issuecomment-458204539

**Comment by robnielsen** [comment]
I manually added msvcr100.dll to the root directory of the app (where the .exe and msvcp100.dll are located) and the app launches just fine.

**Comment by davecurrie** [comment]
This will be fixed in the next release.
