### ISSUE TITLE
Incorrect location of JAVA_HOME for macOS

### ISSUE THREAD

**Issue by arun-gupta** [corretto/corretto-8#7]
Doc bug reported https://twitter.com/chanezon/status/1062828331622514689

Erratum on #Corretto Mac install page https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/macos-install.html …

`JAVA_HOME` is `/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home`
not `/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/lib/jvm/openjdk8-preview` as stated on the page

cc @arungupta

**Comment by ziyiluo** [comment]
The JAVA_HOME is updated.
