### ISSUE TITLE
rt.jar doesn't use compression

### ISSUE THREAD

**Issue by EricEdens** [corretto/corretto-8#78]
(Checked on 8.202.08.2 for generic Linux, Windows, and Mac)

rt.jar is 65MB once the JDK image is extracted to the filesystem. If it is unpacked, then re-packed using `jar cf`, the size becomes 32MB.

The output of the `unzip` command shows the compression level:

```
$ unzip -v ~/jdks/amazon-corretto-8.202.08.1-linux-x64/jre/lib/rt.jar | tail
    3416  Stored     3416   0% 2019-01-18 00:27 00a6d6a1  java/lang/reflect/AnnotatedElement.class
     304  Stored      304   0% 2019-01-18 00:27 76dd77d8  java/lang/reflect/GenericDeclaration.class
   34525  Stored    34525   0% 2019-01-18 00:27 e71cb976  java/lang/Class.class
    1918  Stored     1918   0% 2019-01-18 00:27 c7ebeddd  java/lang/CharSequence.class
     235  Stored      235   0% 2019-01-18 00:27 282e3102  java/lang/Comparable.class
     113  Stored      113   0% 2019-01-18 00:27 152bb46c  java/io/Serializable.class
   18936  Stored    18936   0% 2019-01-18 00:27 aaf43fdc  java/lang/String.class
    1497  Stored     1497   0% 2019-01-18 00:27 86b63bed  java/lang/Object.class
--------          -------  ---                            -------
61566059         61566059   0%                            19745 files
```

It'd be interesting to see why compression was disabled in the first place here. Startup performance?

**Comment by EricEdens** [comment]
Did some research, and it's indeed a space-versus-performance tradeoff. The first reference is from 2008, so it'd be interesting to profile this and see if it's still relevant. Our Docker users are very keen to reduce the image's footprint.

1. https://blogs.oracle.com/jtc/reducing-your-java-se-runtime-environment-footprint-legally
2. http://mail.openjdk.java.net/pipermail/macosx-port-dev/2012-December/005215.html

**Comment by ziyiluo** [comment]
The compression variable `COMPRESS_JARS` is [hard-coded as "false"](https://github.com/corretto/corretto-8/blob/master/src/common/autoconf/jdk-options.m4#L434) in configuration.

**Comment by davecurrie** [comment]
@EricEdens Do we want to take any action on this now?

**Comment by ziyiluo** [comment]
OracleJDK8 does not use compression either. We'd like to keep the packaging of `rt.jar` consistent with other JDK distributions.
