### ISSUE TITLE
Better contribution documentation - CONTRIBUTING.md

### ISSUE THREAD

**Issue by chtompki** [corretto/corretto-8#79]
I would like to see better documentation on how to interface with the project. Specifically, how to I communication with the community, how do I log issues, how to build the project, and how do I submit patches? The github standard for this is the `CONTRIBUTING.md` file. I will take what we have in [Apache Commons Lang](https://github.com/apache/commons-lang/blob/master/CONTRIBUTING.md) and reformat it to the project and issue it as a pull request.

Clearly in this we want to ensure that people understand that for java related issues: features, updates to the api, non-security related bugfixes, etc. , that they attempt to patch upstream first before coming here.

**Comment by alvdavi** [comment]
Hi,

We will be including a CONTRIBUTING.md file shortly. However, it will be based on the general Amazon CONTRIBUTING.md file.

In any case, thank you very much for your help.

**Comment by chtompki** [comment]
Then I’ll close this. Many thanks.
