### ISSUE TITLE
TravisCI or CircleCI integration

### ISSUE THREAD

**Issue by chtompki** [corretto/corretto-8#81]
I would be convenient if the project had either [TravisCI](https://travis-ci.org/) or [Circle CI](https://circleci.com/) setup on it so that when Pull Requests come in, we can verify that the code is indeed correct. I'm happy to explore this possibility for you guys. Furthermore, it would be good if you had this capability across all of the corretto projects for the sake of code quality.

**Comment by chtompki** [comment]
Interesting...over in #80 I noticed pull request checks pop up. I can't seem to get the the details url from [code build in oregon](https://us-west-2.console.aws.amazon.com/codebuild/home?region=us-west-2#/builds/Corretto8_Github:ddb57897-27ba-4c5a-9249-5f0491a7b06d/view/new). 

I suppose you can use your own infrastructure for the PR build assist, but it's a tad more normal to use travis like you do over in your docker repo mainly because it's just what people are just used to seeing. There does seem to be a curiosity going on with TravisCI these days though https://news.ycombinator.com/item?id=19218036 so maybe CircleCI is the way of the future. Not sure though.

**Comment by alvdavi** [comment]
Thanks for opening the issue.

You are right, at some point last week, we set up CI integration with AWS Codebuild, but the logs are not readily available. We will keep this issue open as we are considering alternatives

**Comment by yishaigalatzer** [comment]
@chtompki we are looking at alternatives for public CI/nightly builds, and will update here once we make more progress.

**Comment by chtompki** [comment]
Hey. I’d be happy to help out in any capacity here.

**Comment by davecurrie** [comment]
@chtompki Thanks for volunteering. Do you have ideas on what we would need to set up in terms of infrastructure?

**Comment by chtompki** [comment]
My impression is that it should be free because your repo is open. Let me see if I can dig up the directions this evening. I’m currently AFK.

**Comment by chtompki** [comment]
@davecurrie - So the main reason to run travisCI or circleCI is for vetting pull requests. So in what environment (do you want to build to be performed in AmazonLinux) do you want the build to be performed? Lastly, it's not entirely clear to me what variety of build you want to run for PRs so any insights there would be cool. 

All that aside. I'll get two forks set up and try to get a `.travis.yml` setup and a circle build setup so you guys can pick which to use.

**Comment by chtompki** [comment]
Nudge on how to build the project. It's not all that clear from the documentation.

**Comment by davecurrie** [comment]
@chtompki We looked into this a bit further and don't think it's a great task for someone new to the project to work on. I'm looking for some good starter issues to point you at.

**Comment by chtompki** [comment]
Seems reasonable. My only suggestion here is that the docs be sufficiently descriptive in the CONTRIBUTING.md that an arbitrary developer could trivially contribute this file.

**Comment by benty-amzn** [comment]
We've added github actions support to the project. At this time there are no plans to integrate with other CI/CD offerings.
