### ISSUE TITLE
DLL version issue

### ISSUE THREAD

**Issue by jasonsobanski** [corretto/corretto-8#84]
We have a JavaFX app that we have been creating native installers with using the self-contained application packaging features of JavaFX. This has been working fine with the Oracle 8 JDK but we'd like to use Corretto instead.  We've run into a problem on the Windows platform when installing an upgrade using an MSI.  If we upgrade from our Oracle 8 JDK version of the app to the Corretto 8 JDK version, we end up with all of the DLL files missing in the packaged runtime (specifically the files from jre/bin that are packaged into runtime/bin).  This appears to be related to how the MSI does installation with version checking of DLL files and not installing "old" versions of the files.  Looking at a few of the files it seems the Corretto versions have a lower version number compared to Oracle -

attach.dll
	Oracle (1.8.0_171)
		File version    : 8.0.1710.11
		Product version : 8.0.1710.11
	Corretto (1.8.0_202)
		File version    : 8.0.202.8
		Product version : 8.0.2020.8

java.dll
	Oracle (1.8.0_171)
		File version    : 8.0.1710.11
		Product version : 8.0.1710.11
	Corretto (1.8.0_202)
		File version    : 8.0.202.8
		Product version : 8.0.2020.8

nio.dll
	Oracle (1.8.0_171)
		File version    : 8.0.1710.11
		Product version : 8.0.1710.11
	Corretto (1.8.0_202)
		File version    : 8.0.202.8
		Product version : 8.0.2020.8

I noticed that the file and product versions don't match in Corretto either.  I'm guessing if the file version of these DLLs matched the product version, I would not be running into this issue.

### To Reproduce
Use JavaFX self contained application packaging to create an MSI installer using Oracle JDK 8.  Create an upgrade to this application that uses Corretto JDK 8 and run the upgrade MSI.

### Expected behavior
All of the JRE runtime files will be installed

### Platform information
    OS: Windows 10
    Version build 1.8.0_202-b08

### Additional context
There may be a way to work around this with the MSI configuration itself, but I wanted to report this in case the file and product versions not matching was a defect.

**Comment by davecurrie** [comment]
Thanks @jasonsobanski. Taking a look and will get back to you on this issue.

**Comment by yoroto** [comment]
Hi @jasonsobanski 

We will look into this issue. It seems to be some compatibility issue between Corretto build and Oracle build. We might not be 100% compatible with Oracle on javafxpackager versions.

Are the .dll files in a different folder, or completely missing?

**Comment by jasonsobanski** [comment]
@yoroto - The dll files are completely missing.  I can send a full list of the missing dlls if that would help.  These dll files are all installed correctly on a fresh install (no old version of the app with Oracle) but will be missing on an upgrade install.

**Comment by jasonsobanski** [comment]
@yoroto - I did want to mention that while all the dll files are missing in runtime/bin after the upgrade, there is one dll that is not removed from runtime/bin/server 

jvm.dll
Oracle (1.8.0_171)
  File version : 8.0.1710.11
  Product version : 8.0.1710.11
Corretto (1.8.0_202)
  File version : 8.0.2020.8
  Product version : 8.0.2020.8

This was the only dll that had a higher file version than it's Oracle counterpart so the MSI handled it correctly.  The MSI is seeing all the other dll files as downgrades and is removing them, but this one dll gets correctly upgraded.

**Comment by davecurrie** [comment]
Just a note that we expect this to be fixed in the next release of Corretto.
