### ISSUE TITLE
Provide a Nix Package Defintion

### ISSUE THREAD

**Issue by davidbarsky** [corretto/corretto-8#89]
### Describe a solution you would like
nixpkgs is a cross-platform package manager similar to `apt-get`, `yum`, and `brew`. It'd be great if Corretto was _also_ distributed using nixpkgs. For instance, [this is the definition of JDK 11](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/11.nix) in Nix.

**Comment by davecurrie** [comment]
@davidbarsky Thanks for the suggestion. Adding this to our auto-updates milestone, which we are planning to curate and start working through soon.

**Comment by egmanoj** [comment]
@davecurrie Is Corretto available as a nix package yet? The PR targeting the official nix repo (https://github.com/NixOS/nixpkgs/pull/55156) appears to be closed; is the package available in any other repo? 

Thanks!

**Comment by davecurrie** [comment]
We aren't maintaining the nix packages for Corretto. They are likely in the same status as e.g. Homebrew or SDKMan, where members of those communities have taken on the responsibility to maintain those packages up-to-date.
