### ISSUE TITLE
Update OS detection code to recognize Windows Server 2019

### ISSUE THREAD

**Issue by antimatter84** [corretto/corretto-8#92]
The code currently can only detect Windows Server 2016, but not Windows Server 2019. The major and minor OS version of these are the same (10.0). They only have different build numbers.

Line 1756 in src/hotspot/src/os/windows/vm/os_windows.cpp should not cover for 6004 (Windows version 6.4), but for 10000 (Windows 10.0) and then distinguish the build number.

Please consider adopting the fix from official OpenJDK:
http://hg.openjdk.java.net/jdk/jdk/rev/c02aa8873ff2

**Comment by alvdavi** [comment]
Hi,

The patch you mention has been officially backported to OpenJDK8 project and it is scheduled for 212 release:
https://bugs.openjdk.java.net/browse/JDK-8220415

You can expect that patch to be included in Corretto versions that are based on the 212 release of OpenJDK.
