### ISSUE TITLE
Provide a public debian repository

### ISSUE THREAD

**Issue by jherault** [corretto/corretto-8#99]
Hi guys. 
First of all **Thanks** for your work.

### Is your feature request related to a problem?
No and Yes.

I can install Corretto on a Debian distribution manually but I have to reproduce the steps each time a new version will be release.

> Amazon Corretto is a no-cost, multi-platform, production-ready distribution of the Open Java Development Kit (OpenJDK). 

What about automatic updates (during internal patch parties)?

### Describe a solution you would like

Please, give us a mirror or a public debian repository we could add to our sources list files for a real use in production.

### Describe alternatives you have considered
Do it manually for each new version as explained [here](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/generic-linux-install.html)

**Comment by davecurrie** [comment]
@jherault Thanks for the feedback. Solving the problem of auto-updates for Corretto users is one of the high-priority items we are looking at next in our roadmap. This issue is similar to https://github.com/corretto/corretto-8/issues/29 but keeping separate for now.

**Comment by Voronenko** [comment]
any update?

**Comment by davecurrie** [comment]
This is on the roadmap and we hope to be able to share more news soon.

**Comment by stbuehler** [comment]
@Voronenko I'm not against upstream providing a proper repo in the first place :)  (Although I like the part in my setup about having an archive with older versions.)
I do disagree with your "production grade" remark though.

I also hope that my script might help solving this upstream too (by showing how easy to use `reprepro` is).

**Comment by cliveverghese** [comment]
@stbuehler @Voronenko @jherault 

We are happy to inform you that the new channels for installation including Apt Repositories are now available for use. Please refer to the [launch blog post](https://aws.amazon.com/blogs/opensource/new-update-channels-for-amazon-corretto-releases/) for additional information.

**Comment by jherault** [comment]
Hi.
Really thank you, you are the best!!!
Regards, 
Jeremy

**Comment by Voronenko** [comment]
Thanks a lot, both debian and centos pass with packages!  https://travis-ci.com/softasap/sa-java-corretto

If you have time for 2020, can you consider officially supporting choco java corretto installer for windows ? https://chocolatey.org/

it is now standard de-facto for windows environments as well.

**Comment by stbuehler** [comment]
Thanks, these are very good news!

I personally prefer to not add 3rd-party keys to the global list; the `deb822-style` format (`.sources` instead of `.list` extension) allows individual keys per repository like this:

```bash
mkdir -p /etc/apt/single-keys
wget -O/etc/apt/single-keys/corretto.key https://apt.corretto.aws/corretto.key
cat > /etc/apt/sources.list.d/corretto.sources <<EOF
Types: deb
URIs: https://apt.corretto.aws
Suites: stable
Components: main
Signed-By: /etc/apt/single-keys/corretto.key
EOF
```
